### ISSUE TITLE
The 1.1.0 release steps

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#108]
For the "1.1" release:
- [X] Update [CHANGELOG.md](https://github.com/Esri/resource-proxy/blob/master/CHANGELOG.md) with changes (via #271)
- [x] Update the version number in the three proxy files from 1.0 to 1.1.0-beta until released
- [x] Close or move all issues [marked for 1.1.0 milestone](https://github.com/Esri/resource-proxy/milestones/1.1.0).
- [x] Update the version number in the three proxy files from 1.1.0-beta to 1.1.0
- [x] Release as "1.1" - see https://github.com/Esri/resource-proxy/releases (automatically creates the "v1.1.0" tag)

**Comment by bsvensson** [comment]
@jgravois et al - I think we're getting close to releasing the 1.1.0.  Only five open issues left for 1.1.0: https://github.com/Esri/resource-proxy/milestones/1.1.0.  Mostly docs. It would also be a good time to have some additional sanity testing since there's been a lot of changes the last few weeks.

**Comment by jgravois** [comment]
i added a little markdown to your initial comment in this thread to make it a 'to do'

**Comment by bsvensson** [comment]
Version 1.1.0 is tagged and released.  

See https://github.com/Esri/resource-proxy/blob/master/CHANGELOG.md and https://github.com/Esri/resource-proxy/releases/tag/v1.1.0.   There might be some new feature functionality that's missing from those notes.

cc: @esoekianto @jgravois @afili @phpmaps

**Comment by jgravois** [comment]
nice work @bsvensson!  thanks **so** much for knocking this out.  i should be able to put together a short blog to announce on geonet soon.

**Comment by NoashX** [comment]
:+1:
