### ISSUE TITLE
.NET proxy does not document log file usage

### ISSUE THREAD

**Issue by phpmaps** [Esri/resource-proxy#127]

**Comment by augaug** [comment]
So how do I enable .NET logging exactly? I enter `logFile="C:\proxylog.txt"` into my proxy.config but I see no logs generated..thanks!

**Comment by afili** [comment]
@augaug which version of the proxy are you using? Is it Version 1.1 beta? You can see that information in the beginning of the proxy.ashx file.

**Comment by augaug** [comment]
It's the 1.1 version, where do I activate/set path for it to function? I'm looking in proxy.ashx, but admittedly don't know what I'm looking for exactly...

**Comment by afili** [comment]
The proxy.ashx already uses a method that will write to the log file. But if you want to write something extra, you can call this method logMessageToFile("Your message"); in the proxy.ashx.

**Comment by augaug** [comment]
I guess I'm wondering where the logfile is then, or where I tell it to be in the proxy.ashx? I don't need to add anything to it...and the help doc refers to "C:\temp\Shared\proxy_logs" "if this location exists" so I made that location but still don't see any logfiles being generated.

On a different note - could I ask if you know the best documentation for my situation - I'm simply 1)making a webapp with webappbuilder(dev edition) 
2)downloading and hosting that app locally (localhost/[mywebapp])
3)trying to configure .net proxy to get rid of sign-in

a colleague successfully used the php proxy on his mac, but I'm grinding away at .net on windows with no success, is there any better info (or examples) than the readme on how to configure the .net app in IIS / what to put in config.json / what to put in proxy.config in the above scenario, any tips? I feel like I'm missing something basic, thanks for any input you might have!

**Comment by guo7711** [comment]
@augaug Here is some more doc for using proxy with Web AppBuilder.http://doc.arcgis.com/en/web-appbuilder/manage-apps/use-proxy.htm
I would suggest to check if you have write permission when you set logFile="C:\proxylog.txt"

**Comment by gavinr** [comment]
My issue was that the log file was not writable by the IIS ApplicationPoolIdentity. I followed these instructions and started logging: http://stackoverflow.com/a/7334485/2039. Is this the resolution for others?

**Comment by wspiking** [comment]
Hi augaug,

Did you get the issue with the log files not being generated in C:\temp\Shared\proxy_logs figured out?  I'm running into the same problem and haven't been able to figure it out.

Thank you,

Bill

**Comment by augaug** [comment]
Hi Bill, I did not- however I did get the proxy working finally...


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by wspiking** [comment]
I finally got the logging to work by adding the log file location to the proxy.config (see below), but I’m still not able to pass my AGO credentials.  Any suggestions would be appreciated.  Thanks!

<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig mustMatch="true" logFile="C:\Temp\Shared\proxy_logs\auth_proxy.log">
  <serverUrls>
      <serverUrl url="http://services.arcgis.com/Fz6BBJUji5ArUSDM/arcgis/rest/services/"
            username="user1"
            password="pass1"
            matchAll="true">
      </serverUrl>
  </serverUrls>
</ProxyConfig>

Bill Spiking | GIS Specialist
Direct: 816.412.1780 | Main: 816.412.1741 | Cell: 816.520.9269
bill.spiking@tetratech.com<mailto:bill.spiking@tetratech.com>

Tetra Tech | Complex World, Clear Solutions™
415 Oak Street | Kansas City, MO 64106 | www.tetratech.com<http://www.tetratech.com>

PLEASE NOTE:  This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

**Comment by phpmaps** [comment]
@wspiking - I am not so sure about what you are doing but when authenticating into ArcGIS Online you should be using OAuth and have users submit their username and password - not use the proxy config containing username and password.  We've got various API's all that support OAuth and make it rather easy.  Alternatively, this proxy enables you to add a clientID and clientSecret into the config to support application logins into ArcGIS Online (ideal for premium service authentication like for routing, geocoding and geoenrichment etc).  We should probably document that better.  I just wanted to share this as a word of caution.  I would be mindful not to go into production with an ArcGIS Online named username and password in the config as it might get viewed as a terms of use issue.  If you go forward with proxying a named user, I think you should sync up with your account manager and ask if that's okay.  If you are consuming ArcGIS Server services (that have not been federated with Portal for ArcGIS), it's perfectly acceptable to use a username and password in the config.  In fact that's why we have that option to support ArcGIS Server workflows.  Hopefully I am not the bearer of bad news but the proxy is not designed to support username and password's in the config to authenticate into ArcGIS Online.  Even if it does work - for this workflow you should create and application and use clientId and clientSecret.

**Comment by phpmaps** [comment]
@bsvensson I am just seeing your comment above now.  I agree having logging in the proxy.config would be a nice option and make it easier to support / use.

**Comment by bsvensson** [comment]
See also #306

**Comment by bsvensson** [comment]
Doc'd with ac69bab582327b310e9e1cb27389f131b4803fd9 and 00e71bb5db185f4b0c2e791009ed135e504a3594.  See updated https://github.com/Esri/resource-proxy/blob/master/README.md.
