### ISSUE TITLE
global mustMatch flag must be 'true' to authenticate secure services

### ISSUE THREAD

**Issue by jgravois** [Esri/resource-proxy#129]
When you call http://mymachine/php/proxy.php?http://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World?f=json

With this in the proxy.config
```
<ProxyConfig allowedReferers="*"
             …
             mustMatch=“false">
    <serverUrls>
        <serverUrl url="http://route.arcgis.com"
                   username=“…"
                   password=“…"
                   matchAll="true"/>
    </serverUrls>
```
The following is returned
{"error":{"code":499,"message":"Token Required","details":[]}}

The same is not true of the .NET/Java proxies.  (i.e: a token is retrieved and appended whether the global mustMatch flag is set to ‘true’ or ‘false’)

We accomplish this by evaluating serverUrls in the config and looking at usernames and passwords no matter what (and waiting until afterward to throw an exception only if the flag is set to 'true').

https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.ashx#L659

**Comment by bsvensson** [comment]
This seems to work fine now.  I assume it was fixed by #169.
