### ISSUE TITLE
Referer constant is hardcoded in .ashx file  to use localhost, and should be configurable in .config

### ISSUE THREAD

**Issue by NoashX** [Esri/resource-proxy#137]
DotNet version, the PROXY_REFERER constant, should be able to bet set to user's server in proxy.config file

**Comment by bsvensson** [comment]
I agree with @phpmaps that we shouldn't make the referrer string a configurable item.  The proxy already handles using the real referrer.

I'm closing this issue.  Feel free to comment/reopen if you disagree @NoashX @jgravois
