### ISSUE TITLE
No client-side validation for expired tokens

### ISSUE THREAD

**Issue by vtforester** [Esri/resource-proxy#146]
I don't see any client-side validation (for any of the proxies) that checks to see if a token stored in the application scope has expired based on the server-side expiration. In the Silverlight proxy, we have this:
    
    // If a token has been generated, check the expire time
    if (HttpRuntime.Cache[si.Url] != null)
    {
        string existingToken = (HttpRuntime.Cache[si.Url] as Dictionary<string, object>)["token"] as string;

        DateTime expireTime = (DateTime)((HttpRuntime.Cache[si.Url] as Dictionary<string, object>)["timeout"]);

        // If token not expired, return it
        if (DateTime.Now.CompareTo(expireTime) < 0) {
            theToken = existingToken;
        } 
    }

If the token has expired we get a new one and save that into the application scope along with the timeout. 

Right now I have an application that uses the proxy and retrieves a valid token the first time but after the default expiration (1 hour) the same token is reused and I get an 'Invalid Token' from the server (as expected). Am I missing something here? I'm happy to add the validation but wanted to verify that it's not handled elsewhere first.

**Comment by cheetah90** [comment]
This issue has been fixed in JSP version. #245. Related tag can be removed. @bsvensson

**Comment by cheetah90** [comment]
This issue is seen on DotNet but **NOT** on PHP.

**Comment by cheetah90** [comment]
Fixed on all three proxies.
