### ISSUE TITLE
Allowed Referer Can Be Easily Hacked

### ISSUE THREAD

**Issue by NorthLineGIS** [Esri/resource-proxy#153]
Question:
In our scenario, we are using a service secured with token authentication on the server.  We are then using the username and password parameters in the proxy.config.  We also limit the allowedReferers to our domain. 

Using any modify header plugin, you can easily bypass the allowed referers, granting logged in access to secured services... This seems like a pretty big security hole.  Any Recommendations?

**Comment by SheikhZayed** [comment]
`One recommendation for increased security would be to secure the proxy itself`

can you please elaborate a bit more on this ?

**Comment by bsvensson** [comment]
@SheikhZayed 
You can "secure the proxy" just like any other web page.  There are multiple solutions and the exact implementation would depend on your web server.  Here's some resources for reading more:
* https://www.google.com/search?q=web+server+authentication+methods
* https://httpd.apache.org/docs/2.4/howto/auth.html
* https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/
