### ISSUE TITLE
DotNet: Using HTTP/HTTPS

### ISSUE THREAD

**Issue by msokolDOIT** [Esri/resource-proxy#156]
We've been trying to use the DotNet proxy to load both http and https rest services but it seems we can only use one or the other, not both.  I have tried using two separate proxies as well to separate out the http from https services with no lucky.  Is this a proxy issue or an unsupported feature of the Esri JS API?

**Comment by bsvensson** [comment]
Closing this issue since it doesn't seem to be reproducible.  If you have more info, feel free to re-open, or contact Esri Support for more direct help.
