### ISSUE TITLE
PHP: failed to send over long where statement 

### ISSUE THREAD

**Issue by esoekianto** [Esri/resource-proxy#162]
Working with a user who use PHP proxy, the query request work in REST end point, without proxy and DOTNET proxy, but failed in PHP proxy with invalid where parameter error message. 

Repro case at https://gist.github.com/esoekianto/860649657681560d8dd9

PHP test case
![php2](https://cloud.githubusercontent.com/assets/5265339/5076433/b24ff334-6e4f-11e4-8349-6d9fc302b482.png)

![php1](https://cloud.githubusercontent.com/assets/5265339/5076495/030774be-6e50-11e4-875a-e266aa36be06.png)

DOTNET test case
![dotnet1](https://cloud.githubusercontent.com/assets/5265339/5076456/d0df5114-6e4f-11e4-9a87-b1c2bfa27f8f.PNG)

![dotnet2](https://cloud.githubusercontent.com/assets/5265339/5076461/d44f91c4-6e4f-11e4-801a-6352cc68ebaf.PNG)

REST 
![rest](https://cloud.githubusercontent.com/assets/5265339/5076468/dbbeab52-6e4f-11e4-9774-b4bd1f3794aa.PNG)

NO proxy test case 
![noproxy1](https://cloud.githubusercontent.com/assets/5265339/5076569/d24cc5a8-6e50-11e4-83a3-1f4a02e6bd9b.PNG)

![noproxy2](https://cloud.githubusercontent.com/assets/5265339/5076572/d6b368d6-6e50-11e4-9176-1369e5d47f1d.PNG)

**Comment by bsvensson** [comment]
Closing this as a known issue for old curl versions.  See https://geonet.esri.com/thread/116158 for details.
