### ISSUE TITLE
JSP: After token expiration No new token is obtained

### ISSUE THREAD

**Issue by xalikoutis** [Esri/resource-proxy#172]
The token expires but the proxy doesn't try to get a new token until is restarted. I  have setted the expiration time to 5 minutes is the jsp. See the logs token obtained at 2014 6:47:51 and after 5 minutes the web app requires my credentials

Δεκ 02, 2014 6:47:23 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: [Info]: Service is secured by http://192.168.1.111:6080/arcgis/tokens: getting new token...
Δεκ 02, 2014 6:47:23 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Token obtained: 5fVYtgDpyXqVmkPKxEI2JSdNkHAKRiFDx4aHMvbRof0.
Δεκ 02, 2014 6:47:51 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:47:52 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:49:08 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:49:12 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:51:51 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:52:44 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:52:48 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:52:58 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:52:59 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:53:00 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:53:03 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:53:29 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:53:35 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:55:59 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:56:00 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:59:50 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer
Δεκ 02, 2014 6:59:53 ΜΜ org.apache.jsp.proxy_jsp _log
INFO: Creating request for: http://192.168.1.111:6080/arcgis/rest/services/OKXE/Attica_2010/ImageServer

**Comment by cheetah90** [comment]
This is fixed by #256 and can be closed.
