### ISSUE TITLE
Random IE issue

### ISSUE THREAD

**Issue by AdrianMarsden** [Esri/resource-proxy#173]
This is what is coming up at times in IE  - about 1 in 15 times

SCRIPT1015: Unterminated string constant 
proxy.ashx, line 1 character 114
SCRIPT1015: Unterminated string constant 
proxy.ashx, line 1 character 114
SCRIPT1015: Unterminated string constant 
proxy.ashx, line 1 character 114
SCRIPT1015: Unterminated string constant 
proxy.ashx, line 1 character 114
SCRIPT1015: Unterminated string constant 
proxy.ashx, line 1 character 114
 dojo.io.script errorRequestTimeoutError: Timeout exceeded 
 dojo.io.script errorRequestTimeoutError: Timeout exceeded 
 dojo.io.script errorRequestTimeoutError: Timeout exceeded 
 dojo.io.script errorRequestTimeoutError: Timeout exceeded 
 dojo.io.script errorRequestTimeoutError: Timeout exceeded

**Comment by bsvensson** [comment]
Closing this issue since it doesn't seem to be reproducible.  If you have more info, feel free to re-open.
