### ISSUE TITLE
Forward request headers

### ISSUE THREAD

**Issue by jwoyame** [Esri/resource-proxy#175]
To behave more like a "true" HTTP proxy, the scripts could forward all request headers from the browser which are not explicitly set by the script itself.

This would enable features such as:
- "If Modified" requests
- Partial range requests
- Cookies
- Better request logging on the destination server (e.g. User-Agent)

It would also help to prevent unforeseen issues and bugs, such as the (fixed) issue where PDF files could not be proxied due to the "Range" header getting dropped by the proxy.

**Comment by cheetah90** [comment]
I think now we are forwarding all the headers from the client request. Right? @bsvensson

**Comment by jwoyame** [comment]
I implemented the upgrade in the unacceptable pull request #186, the issue is still worth review. Headers are copied for responses but not for requests.

**Comment by bsvensson** [comment]
This has been fixed and merged - see #433.
