### ISSUE TITLE
Support for ArcGIS Server 10.3 

### ISSUE THREAD

**Issue by esoekianto** [Esri/resource-proxy#177]
DotNet and Java Proxy failed to get token to ArcGIS Server 10.3 with this error in the log file, 

```
WARNING: Token cannot be obtained: {"error":{"code":405,"message":"Method not supported","details":"Generate Token request should not contain username and password in the query string."}}
```

This is because ArcGIS Server 10.3 only supports POST request for token request and does not support username and password in query string , see this doc, http://server.arcgis.com/en/server/latest/administer/windows/acquiring-arcgis-tokens.htm

**Comment by MrPaulg** [comment]
Java Proxy Failing with Arcgis Server 10.3  - July 2015 


Jul 15, 2015 12:02:57 PM org.apache.jsp.proxy_jsp _log
WARNING: Token cannot be obtained: {"error":{"code":405,"message":"Method not supported","details":"Generate Token request should not contain username and password in the query string."}}

has this issue been fixed? as per 'esoekianto' and 'bsvensson' comments ?
if so - I appear to be having a similar issue, how do I get the latest fix for this?

**Comment by esoekianto** [comment]
@MrPaulg yes, this looks like this issue, the fix for java has not been merged yet, see this pull request #178 .

Do you mind trying make the one liner changes in your proxy.jsp? https://github.com/esoekianto/resource-proxy-1/commit/2fe189e9a9141659bedced9317adb51e8ea394bd 

Thank you,

**Comment by MrPaulg** [comment]
Thanks [esoekianto](https://github.com/esoekianto )
Apologies - I did see that yesterday and made the change however - I forgot to mention - while its does sort the issue with 10.3 service requests, some of my requests also come from 10.2 instances. With this change the 10.2 service request for basemap services  fails and the 10.3 requests  appears to work, however I cannot upgrade the 10.2 instance as it is from a third party provider.  

Any ideas would be hugely appreciated as I'm on a tight deadline and would really like to have this working properly.
many thanks for responding to my post.

**Comment by esoekianto** [comment]
@MrPaulg any chance you can call esri tech support? We can help you take a look at this quickly

**Comment by bsvensson** [comment]
@jgravois - this issue only mentions DotNet and JSP.  Does the same problem apply to the PHP proxy?

**Comment by jgravois** [comment]
i haven't tested personally, but the folks in professional services seem to think its not possible to generate tokens from 10.3.1 in PHP either.

**Comment by esoekianto** [comment]
@bsvensson @jgravois so this issue was fairly simple. 

our proxy has always been making POST request to to get token, but we failed to remove the query string parameter on the request, server 10.3 doesnt like this (having query string parameter in the URL).

this PRs (for DOTNET and JAVA) are simply to remove those query string parameter from the url, i am not sure why it would break for 10.2 or other version.

**Comment by laythg** [comment]
Erwin's explanation is exactly how I fixed the dotnet version for 10.3. 

Layth

**Comment by cheetah90** [comment]
Looks like this one has been solved thus can be closed. @bsvensson

**Comment by bsvensson** [comment]
Adding the PHP tag to make sure we test/fix PHP as well.

**Comment by bsvensson** [comment]
Fixed in all three proxies.
