### ISSUE TITLE
JSP: ERR_INVALID_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by rjsibar** [Esri/resource-proxy#187]
Hi guys,

I'm having an issue with the java proxy. Anytime I add it to access AGS resources it's throwing an "ERR_INVALID_CHUNKED_ENCODING". I saw a similar issue with the PHP version that was fixed. Any idea in how to tackle this in the Java version?

**Comment by bsvensson** [comment]
I think this works in the current JSP version.  If not, please comment/re-open the issue with more details on how to replicate the problem.

**Comment by guizgis** [comment]
@rjsibar @bsvensson I have the same issue with the java proxy of version 1.1.0 and version 1.1.1beta.
When I specify the online AGS, it works fine.While local AGS in my intranet can not be accessed with the error "ERR_INVALID_CHUNKED_ENCODING", which can be accessed by using java proxy of version 1.0.
I have tested with several versions of tomcat and jre, and all met the error.
