### ISSUE TITLE
Slow enumeration of system proxies

### ISSUE THREAD

**Issue by jwoyame** [Esri/resource-proxy#188]
See comments for pull request #168.

A feature added by pull request #168 allows the DotNet proxy script to query the system's Web proxy settings. This is necessary for some servers that have a system proxy assigned.

However, it appears that looking up the local proxy settings adds several seconds to every request made to the script, at least on my server that has no proxy specified. A potential solution is included in the comments: Look up the system proxy only once and store the result, which limits the slowdown to the very first request. This is still not an ideal solution, but it is much improved for me.

I would be interested to find out whether anyone else notices the same performance problem?

**Comment by lvdburgt** [comment]
Agree with your comment. Thanks for looking into this! 
I fetched that latest version of the .NET resource proxy and immediately noticed that proxy requests take considerably longer. Requests which should take 100s of ms now take more than 2 seconds.

After commenting out the line
req.Proxy = System.Net.HttpWebRequest.GetSystemWebProxy();

The proxy request times were reduced, so now I can use this solution in a production environment.

**Comment by bsvensson** [comment]
@jwoyame - I too see the same slow down when testing on one machine.  Do you want to submit a pull request with your code suggestion in #168 comment?
