### ISSUE TITLE
matchAll="false" not working for PHP proxy

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#189]
The php proxy is a a little confused on on the matchAll/matchall casing of this serverUrl property.  DotNet and JSP only supports the matchAll casing.

Test:

    http://localhost/proxytesting/PHP/proxy.php?http://www.example.com/index.html

with the following in the config:

    <serverUrl url="//www.example.com/" matchAll="false" />

It should fail, but doesn't for php proxy since it's confused about the casing. Currently neither casing work.

**Comment by phpmaps** [comment]
@bsvensson Is the top level mustMatch set to true or false?  

Also help me understand, this b/ I don't currently understand why this is a defect.  If someone configures the proxy and says ````matchAll=true```` that means they assert that any URL in the serverUrl list needs to match the characters in incoming URI. 

Therefore, when ````false```` isn't that like saying I don't care if the parts of the URI don't match what has been defined in the serverUrl item?

I suspect I am missing something.

**Comment by bsvensson** [comment]
@phpmaps - In my test I had `mustMatch="true"`. 

Those two property names can be a bit confusing.  

* mustMatch (on the root tag) is about whether to only allow URLs listed as serverUrl in the proxy.config to be proxied. 

* matchAll (on the serviceUrl tag) is about whether to match an exact serviceUrl or also all other requests that begin with that serviceUrl.  Think of matchAll as "match-this-and-all-others" or "starts-with", while matchAll="false" is more a "only-match-exactly".

Not sure if that's clear enough in the README - https://github.com/Esri/resource-proxy/blob/master/PHP/README.md:
* matchAll="true": When true all requests that begin with the specified URL are forwarded. Otherwise, the URL requested must match exactly.
