### ISSUE TITLE
Support federated services that are missing the tokenServicesUrl

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#191]
Problem: proxy doesn't work with analysis.arcgis.com.

When using username/password to access secure ArcGIS servers, the proxy looks in the server rest/info for the "tokenServicesUrl" to use.
http://resources.arcgis.com/en/help/arcgis-rest-api/#/Server_Info/02r300000116000000/

[As of 10.1 SP1](http://resources.arcgis.com/en/help/arcgis-rest-api/#/What_s_new_in_the_ArcGIS_REST_API/02r3000000q6000000/
), the Server Info resource also returns an owningSystemUrl property. So most servers will have both.  And the proxies happily use "tokenServicesUrl".

However, http://analysis.arcgis.com/arcgis/rest/info?f=pjson only returns owningSystemUrl.  This causes the proxy to fail for this server.

Test:

    http://localhost/DotNet/proxy.ashx?http://analysis.arcgis.com/arcgis/rest/?f=pjson

With the following in your proxy.config:

    <serverUrl url="http://analysis.arcgis.com" 
            matchAll="true"
            username="your-org-user"
            password="your-org-password"/>

See also:
https://developers.arcgis.com/rest/analysis/api-reference/programmatically-accessing-analysis-services.htm (which has python 2 and python 3 examples).

If a response has both owningSystemUrl and tokenServicesUrl, it's better to use the owningSystemUrl.

**Comment by cheetah90** [comment]
Quick note: the token system endpoint for federated system is something like "{owningSystemUrl}/sharing/generateToken"
