### ISSUE TITLE
Java proxy should be re-written as a Servlet rather than a JSP page.

### ISSUE THREAD

**Issue by yeroc** [Esri/resource-proxy#197]
The proxy does not use any templating capabilities of JSP so is a really poor fit as a JSP and should be written as a Servlet.  This would make the code much easier to follow.

**Comment by bsvensson** [comment]
@yeroc - thank you for the feedback.  I too think that the code isn't very easy to follow.  But 'm not sure changing it to a Servlet would necessarily make the code easier to follow.

As for whether it would have been better to use a servlet from the beginning, that's a different topic. We don't have any plans for rewriting it as a servlet.
