### ISSUE TITLE
The proxy ignore to set App ID and App Secret in an access to secured web map

### ISSUE THREAD

**Issue by ynunokawa** [Esri/resource-proxy#198]
I would like to access a secured web map using Application Authentication via the proxy but it ignore... 
If it correctly run, web app should access without requiring a login and not show a dialog to sign into the portal. However, it correctly run in the case of accessing a public web map with secured layers.

![access_to_securemap_via_proxy](https://cloud.githubusercontent.com/assets/3479935/6057178/70b2e3fc-ad5e-11e4-8431-6c77ebff132f.png)

The following description is the configuration into proxy.config to get a web map and layers with Application Authentication.

    <serverUrl url="http://services1.arcgis.com/***/arcgis/rest/services/" matchAll="true" clientId="***" clientSecret="***"></serverUrl>
    <serverUrl url="http://***.maps.arcgis.com/sharing/rest/content/items/" matchAll="true" clientId="***" clientSecret="***"></serverUrl>

Possibly, the proxy does not support accessing to private web map with app login?

**Comment by jgravois** [comment]
there are [documented](https://github.com/Esri/resource-proxy/blob/master/FAQ.md) limitations with regard to accessing private content in ArcGIS Online via app logins.  please let us know if something prohibits you from leveraging user credentials in a scenario like this.

**Comment by bsvensson** [comment]
@nuno0825 - It's by design for security reasons.  You can use the resource-proxy with appid to connect to platform services or public items.  To access private services, you would need to use username/password.

See also:
* https://github.com/Esri/resource-proxy/blob/master/FAQ.md 
* https://developers.arcgis.com/authentication/accessing-arcgis-online-services/ and https://developers.arcgis.com/authentication/working-with-proxies/

**Comment by nuno0825** [comment]
There is a difference of the contents between the FAQ in GitHub and the documents as "Limitations of Application Authentication" in ArcGIS for Developers page.

https://github.com/Esri/resource-proxy/blob/master/FAQ.md
https://developers.arcgis.com/authentication/limitations-of-application-authentication/

The document of Limitations of Application Authentication say "If a user has private content on their account (content that has not been shared with anyone) applications can only read or query from that content."
If it is correct, the proxy should be able to access a secure content to READ it.
Incidentally, Runtime SDK for .NET can do. It is undesirable for web?

And it is my scenario that web app can show only the specified secure map and NOT search them.

**Comment by bsvensson** [comment]
After looking into this more ... I was wrong. You are correct, the proxy should be able to access (in read-only mode) items that the appId user owns (but not things shared to that user).  I'll re-open this issue for more investigation.

**Comment by nuno0825** [comment]
Thanks for the cooperation. I am waiting for your response.

**Comment by bsvensson** [comment]
@nuno0825 - the problem is that the proxy is using a server token instead of a portal token when accessing the item. The code needs to be updated to be smart for appId and to know when to use a portal token (for /sharing/rest) and when to use a server token (for platform services like traffic and geoenrichment).

A quickfix IF you're only using your proxy for this purpose is to comment out

    token = exchangePortalTokenForServerToken(token, su);

However, that causes issues for other use cases, so it's not a complete solution. I'm still working on that.

**Comment by nuno0825** [comment]
@bsvensson - Thanks for the information. The proxy was able to access secured map after the part of the issue in proxy.ashx was commented out.
FYI It is necessary to comment out the if statement also. But I confirmed only the DotNet proxy.
```
//if (!string.IsNullOrEmpty(token))
    //token = exchangePortalTokenForServerToken(token, su);
```
I'm looking forward to the completion of report.

**Comment by themeebs** [comment]
I think this explains the exact problems I've been having with the PHP proxy.

**Comment by esoekianto** [comment]
@ynunokawa sorry for delay, are you testing this in Web App Builder?

I just tested this with secured webmap in Portal and AGOL. So I could reproduce the same issue but what we found out that you are missing "oauth2Endpoint" tag in your serverurl attribute in proxy.config.

I tried this without the changes in the code and it works, can you please try it on your end? 

``
<serverUrl url="http://***.maps.arcgis.com/sharing/rest/content/items/" matchAll="true" clientId="***" clientSecret="***" oauth2Endpoint="http://***.maps.arcgis.com/sharing/oauth2/"></serverUrl>
``

So what happens is, the proxy is getting the token  using clientid and clientsecret to the oauth2endpoint, by defaults it points to "https://www.arcgis.com/sharing/oauth2/", but in this case we need to change it to point to the organization or portal url oauth2endpoint.

**Comment by ynunokawa** [comment]
@esoekianto sorry for delay too, yes, I am testing in Web AppBuilder with the webmap in AGOL.

I have confirmed missing "oauth2Endpoint" in my proxy.config.
My app is working well via proxy with the oauth2Endpoint according to your instruction.

Thanks a lot!

**Comment by dandanaus** [comment]
Hi guys

Has anyone tried the fix above for portal 10.3.1?

I have added the oath2 endpoint and also the appid and app secret from my portal but i cannot get the secured resource.

Still getting 498 Invalid Token

Any advice?

**Comment by esoekianto** [comment]
@dandanaus can you show us the serverurl of the your proxy configuration? feel free to call esri tech support, we can help you trouble shoot for this type of issue

**Comment by gmeena** [comment]
I am trying to access ArcGIS Online Map using web builder generated app hosted on own servers. proxy.config file have setting 
<serverUrl url="https://***.maps.arcgis.com/sharing/rest/content/items/" clientId="***" clientSecret="*** oauth2Endpoint="https://***.maps.arcgis.com/sharing/oauth2/" rateLimit="600" rateLimitPeriod="60" matchAll="true">

In Config.json I have something like 
 "httpProxy": {
    "useProxy": true,
    "url": "http://localhost:56307/proxy.ashx",
    "alwaysUseProxy": true,
    "rules": [
      {
        "urlPrefix": "http://route.arcgis.com/",
        "proxyUrl": "http://localhost:56307/proxy.ashx"
      }
    ]
  }
With this, it is giving me an error "Proxy has not been set up for this URL. Make sure there is a serverUrl in the configuration file that matches: https://***.maps.arcgis.com/sharing/rest/portals/self?f=json&dojo.preventCache=1492590458623&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback
Could someone help me with this?

Thanks

**Comment by esoekianto** [comment]
@gmeena You should not use the token from arcgis online for this map service https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer?f=json 

This map service is shared publicly, I don't you even need use proxy for this map service (for token/security purpose)
