### ISSUE TITLE
link to FAQ.md in projects root README

### ISSUE THREAD

**Issue by jgravois** [Esri/resource-proxy#199]
currently you have to browse the repos content directory to find the FAQ.  would be helpful if we linked to it from the homepage.

**Comment by bsvensson** [comment]
Sounds like a good idea. Will you submit a pull request (or should I)?

**Comment by jgravois** [comment]
i'll submit shortly.

**Comment by bsvensson** [comment]
Hey @jgravois - are you still planning to submit a PR "shortly"?  :)
