### ISSUE TITLE
Using the proxy to filter requests securely

### ISSUE THREAD

**Issue by tr3vorm** [Esri/resource-proxy#200]
I have been looking at using the proxy (ASP.Net) to set layer definitions, as a way to securely filter map services based on the current user id. I currently do this from the client end in javascript but this is visible to anyone that wants to look at the requests. 

I need to look at the service name, action (export/find/identify) and rewrite/create the layerDefs query parameter for the relevant layers. 

Is this a good idea or not? Or should I write my own separate handler (assuming handlers can be chained)? Any guidance much appreciated. Possibly there are existing solutions.

**Comment by tr3vorm** [comment]
This (basic example below) worked perfectly (adding my `layerDefs` in the proxy) until I went to use a print service. Since I had moved my queries to the proxy, the client has no knowledge of layer definitions so the print service printed unfiltered layers. I am guessing that I could rewrite the print server (post) request too but that looks more difficult. 

```c#
// ~line 180 before reading the body of a POST request
    if (uri.StartsWith("https://myserver/adaptor/rest/services/MyService"))
    {
        uri += String.Format("&layerDefs=0:ProjectId={0};1:ProjectId={0}", projectId);
        log(TraceLevel.Info, uri);
    }
```
The overall goal is to use a single map service for several "projects" rather than having to generate a map service for each one. Anyway, I will close this off as it is not part of the core functionality - I still hope someone can make suggestions/recommendations. Thanks.

**Comment by jgravois** [comment]
i must confess that i don't really understand the benefit of 'securely filtering map services' when you end up drawing the output for the client, but i'm sure you have your reasons.

you can find the proxy's method for firing requests (GETs and POSTs) [here](https://developers.arcgis.com/javascript/jssamples/query_bypoly.html), and you can find an example of calling it and supplying POST content [here](https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.ashx#L335).

hope that helps.

**Comment by tr3vorm** [comment]
Thank you @jgravois, I don't think I explained this very well. The output is determined by the current user context in my web mapping application. So, a single mapservice partitioned by project/user role. Rather than put the layer definitions (determined at runtime by userid) in to the client where they can be seen, I was exploring the options for setting the layer definitions in the proxy so they were hidden and/or could be intercepted to check any "illegal" requests.

**Comment by jgravois** [comment]
thanks for clarifying.  makes a lot more sense now.
