### ISSUE TITLE
Proxy is logging users out of Esri Geoportal Server

### ISSUE THREAD

**Issue by slead** [Esri/resource-proxy#202]
I'm seeing a problem whereby passing a query to the Esri Geoportal Server's REST API, via the Esri Resource Proxy, is causing users to be logged out of the Geoportal.

I can reproduce the problem like this:

- install the Esri Geoportal Server on Windows using IIS
- install the Esri Resource Proxy on the same machine
- log in to the Geoportal (eg http://localhost:8080/geoportal/catalog/identity/login.page)
- in a new tab in the same browser, send a query to the Geoportal REST API via the Esri proxy (eg http://localhost/PHP/proxy.php?http://localhost:8080/geoportal/rest/find/document?f=pjson)
- switch back to the Geoportal tab, refresh the page, and note that the user is now logged out

This error does not occur for me using the sandbox Geoportal at http://gptogc.esri.com/geoportal/catalog/main/home.page (you can test it at http://stephenlead.com/esri-proxy/PHP/proxy.php?http://gptogc.esri.com/geoportal/rest/find/document?&max=10&rid=local&f=pjson)

Do you know why this is occurring? Is the problem occurring because the proxy is on the same machine as the Geoportal Server? Are there any known workarounds?

Thanks,
Steve

(ping @mhogeweg)

**Comment by bsvensson** [comment]
That seems rather strange.  Not that I think it matters, but which version of the PHP proxy are you using?

Does the same thing happen if you use a computer name instead of localhost in one of the tabs?

Could you try the DotNet proxy?

**Comment by phpmaps** [comment]
@slead @mhogeweg - Looking into this really quickly I notice the gptogc.esri.com ````Geoportal```` leaves behind a ````cookie```` when you load this page http://gptogc.esri.com/geoportal/catalog/main/home.page  .  Frequently cookies are responsible for persisting a logged in session.  I've been looking closely at how the php version of the resource-proxy preserves headers.  Can you test this proxy.php page - It's currently a pull request we are reviewing and my thoughts are it might be a solution, as i think it preserves headers better and ````Set-Cookie```` is suspect here.

please try replacing your proxy.php code with this code here... for a test
https://github.com/phpmaps/resource-proxy/blob/patch-1/PHP/proxy.php

Its also strange to hear the behavior is different between your localhost and http://gptogc.esri.com/geoportal/catalog/main/home.page.  What's the difference between the two installs?

**Comment by slead** [comment]
@phpmaps thanks for the pointers - the cookie definitely sounds like the cause of the problem.

Unfortunately the patch-1 version of the PHP script didn't help - the session is still cleared.

I'm not sure what the difference is with the gptogc.esri.com installation - I installed my version as per the instructions at http://www.esri.com/library/whitepapers/pdfs/how-to-set-up-geoportal-server-122.pdf - perhaps the sandbox installation doesn't use IIS?

@bsvensson I was using the 1.1 PHP proxy - the problem also occurs if I use the .Net version of the 1.1 proxy

Thanks,
Steve

**Comment by slead** [comment]
I can also confirm that the patch-1 proxy does not log me out of a session at http://gptogc.esri.com 

sample request: http://localhost/resource-proxy-patch/PHP/proxy.php?http://gptogc.esri.com/geoportal/rest/find/document?f=pjson 

So it appears the problem (possibly) only occurs when the proxy is on the same domain as the geoportal.

Does that help to narrow down the cause?

**Comment by phpmaps** [comment]
@slead - I am of the mind that the two should play nice on the same server.  

 Do you know the login credentials to http://gptogc.esri.com?  Are you using LDAP security or something else on your localhost?  Its possible that the underling security protocol is restricting access b/ the request is coming from a different place and the resource-proxy does not know how to make the handshake.

If you want to dig further 1) remove the proxy on you localhost 2) sign-in and 3) perform a query -- I suspect the expectation is you'll remain logged in.  If you look at the request and response for step 3 they should look the same as performing the query through the proxy.  If you repeat (running step 3 through the proxy) if you start to notice header differences copy and paste those differences here as i suspect they will be helpful.  

On http://gptogc.esri.com I've noted down headers associated with a non-signed in query request. I did this for the purposes of showing what to look for... See below as a reference.  

**Request Headers**
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:stephenlead.com
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Query String Parameters**
http://gptogc.esri.com/geoportal/rest/find/document?:
max:10
rid:local
f:pjson)

**Response Headers**
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Type:application/rss+xml;charset=UTF-8
Date:Wed, 11 Feb 2015 05:22:12 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=2, max=100
Pragma:no-cache
Server:Apache
Set-Cookie:JSESSIONID=39C522EF68866A45409EB7B9B6C17B37; Path=/geoportal
Transfer-Encoding:chunked
X-Powered-By:JSF/2.0

**Comment by slead** [comment]
@phpmaps I'm not entirely sure what to look for, but these stand out:

without using the proxy (http://localhost:8080/geoportal/rest/find/document?f=pjson) the header includes:

`Cookie:JSESSIONID=F17CB139CEB630B7462F3A9378B6DC12; JSESSIONID=46EB87BD31842F4EA99F29AF91DD8316; PHPSESSID=efuhc629e68nhk06iitss9pph3`

with the proxy (http://localhost/resource-proxy-patch/PHP/proxy.php?http://localhost:8080/geoportal/rest/find/document?f=pjson) the header includes:

`Cookie:PHPSESSID=efuhc629e68nhk06iitss9pph3`
... then further down ...
`Set-Cookie:JSESSIONID=163CE67F94F1BEAC796F31B8448B0FA1; Path=/geoportal/; HttpOnly`

The header without the proxy doesn't include Set-Cookie whereas the header via the proxy does - is it possible that this is over-writing the signed-in cookie? (This may be saying the same thing, but there is only a request cookie without the proxy, and a request **and** response cookie when the proxy is used).

I'm not using LDAP, just the out-of-the-box gptuser/gptuser. I can include the full header contents if this will help. Thanks

**Comment by phpmaps** [comment]
Thanks.  This is good info.  I assume these are response headers?  It would be good to see everything.  For example, set 1 showing request and response headers showing what works not using proxy and set 2 showing request and response headers of what fails using the proxy.  Make sure the query stays the same to make things easiest.

I am not very familiar with geoportal security except recall there are a few options.  The intended design was that the resource - proxy was to support ArcGIS Online, Server and Portal.  To that end the project supports token and oauth well but there are limitations regarding other security protocals.  For example, the php proxy does not support Windows Authentication, Basic or Digest. Not sure that's an issue here but just sharing what I know...


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by slead** [comment]
OK here goes:

A direct request to http://localhost:8080/geoportal/rest/find/document?f=pjson

Remote Address:[::1]:8080
Request URL:http://localhost:8080/geoportal/rest/find/document?f=pjson
Request Method:GET
Status Code:200 OK

**Request Headers**
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:JSESSIONID=F17CB139CEB630B7462F3A9378B6DC12; JSESSIONID=46EB87BD31842F4EA99F29AF91DD8316; PHPSESSID=efuhc629e68nhk06iitss9pph3
Host:localhost:8080
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
**Query String Parameters**
f:pjson
Response Headersview source
Content-Type:text/plain;charset=UTF-8
Date:Wed, 11 Feb 2015 05:57:32 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked
X-Powered-By:JSF/2.0
Name
Path
document?f=pjson
/geoportal/rest/find

A request via the proxy to http://localhost/resource-proxy-patch/PHP/proxy.php?http://localhost:8080/geoportal/rest/find/document?f=pjson

Remote Address:[::1]:80
Request URL:http://localhost/resource-proxy-patch/PHP/proxy.php?http://localhost:8080/geoportal/rest/find/document?f=pjson
Request Method:GET
Status Code:200 OK

*Request Headers**
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:PHPSESSID=efuhc629e68nhk06iitss9pph3
Host:localhost
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
Query String Parametersview sourceview URL encoded
http://localhost:8080/geoportal/rest/find/document?f:pjson
**Response Headers**
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Length:3620
Content-Type:text/plain;charset=UTF-8
Date:Wed, 11 Feb 2015 05:58:39 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:Apache-Coyote/1.1
Server:Microsoft-IIS/7.5
Set-Cookie:JSESSIONID=163CE67F94F1BEAC796F31B8448B0FA1; Path=/geoportal/; HttpOnly
X-Powered-By:JSF/2.0
X-Powered-By:PHP/5.6.0
X-Powered-By:ASP.NET
Name
Path
proxy.php?http://localhost:8080/geoportal/rest/find/document?f=pjson
/resource-proxy-patch/PHP

**Comment by slead** [comment]
@phpmaps here is some info I received from the Geoportal Server team:

_Geoportal Server uses Java sessions on the app server, a client identifies its session through an HTTP cookie named JSESSIONID. If the client does not supply a JSESSIONID cookie, it is assumed to be a new session and the server’s HTTP response will include a SET-COOKIE parameter for the new JSESSIONID. Maybe the proxy does not pass cookies._

This definitely sounds like what's happening. Does that help?

**Comment by slead** [comment]
However... when using the gptogc.esri.com Geoportal, the same pattern is seen with the proxy request setting the JSESSIONID cookie - but in this case the user is **not** logged out.

* log in to http://gptogc.esri.com/geoportal (you can use testing123/password)
* in a new tab, send a search via the proxy using http://stephenlead.com/esri-proxy/PHP/proxy.php?http://gptogc.esri.com/geoportal/rest/find/document?&max=10&rid=local&f=pjson
* Note that this sends a Response Header: Set-Cookie: JSESSIONID=A835E3A169D58DF171F29C2FBBD4342E; Path=/geoportal
* refresh the first tab and note that the user is still logged in

Could the difference be that the proxy is on the same machine/domain as the geoportal when it fails - if it's on a different machine/domain there isn't a problem?

**Comment by phpmaps** [comment]
@slead - my attention is on this request header sent through the proxy
```` Cookie:PHPSESSID=efuhc629e68nhk06iitss9pph3 ````

verses this header which is seen when the proxy is removed
```` Cookie:JSESSIONID=F17CB139CEB630B7462F3A9378B6DC12; JSESSIONID=46EB87BD31842F4EA99F29AF91DD8316; PHPSESSID=efuhc629e68nhk06iitss9pph3 ````

I am not sure what is the proper protocol.  Part of me thinks sending cookies is an automated thing that browsers take care of and another part of me thinks developers need to send cookie data with intent.

When signed into http://gptogc.esri.com  do both of these cookies ````JSESSIONID```` and  ````PHPSESSID```` get sent when going through the proxy?  I ask b/ you mentioned that the proxy works on http://gptogc.esri.com .  If both of these cookies get sent to http://gptogc.esri.com and if the signed in session persists - I think it may be worth the effort to determine why the ````JSESSIONID```` is not being sent and figure out how to make sure it is sent and see what happens.

**Comment by phpmaps** [comment]
@slead  looks like you typing as I was typing and noted that ````http://gptogc.esri.com```` proxy case sends this ````Cookie:JSESSIONID=F17CB139CEB630B7462F3A9378B6DC12;````.

I guess the only way to test your theory is to try using a resource-proxy from a different server. 

Here is an older version of the PHP proxy - but is should be close enough to test your theory... 

http://54.82.255.206/ogc/proxy.php

**Comment by slead** [comment]
The problem is that the 54.82... proxy can't see my localhost Geoportal, so I can't test using this(?)

http://54.82.255.206/ogc/proxy.php?http://localhost:8080/geoportal/rest/find/document?f=pjson returns `{"error":{"code":502,"details":["cURL error (7): Failed to connect to localhost port 8080: Connection refused."],"message":"Proxy failed due to curl error."}}`

Using the proxy at http://stephenlead.com/esri-proxy/PHP/proxy.php?http://gptogc.esri.com/geoportal/rest/find/document?&max=10&rid=local&f=pjson already demonstrates that it _seems_ to work when the proxy is on another domain.

Is it feasible to reproduce the "proxy on another domain" setup within a single Windows installation? I've got the proxy running on PHP via IIS and the Geoportal Server is on Apache, if that helps.

**Comment by phpmaps** [comment]
Yes.  I believe you can create a subdomain on your IIS box.  For example Geoportal on port 80 and the proxy on port 85 (a different subdomain).   That I believe would do the trick since http://54.82.255.206/ogc/proxy.php cannot reach your machine.

**Comment by slead** [comment]
I'll give that a try - but I would ideally like to be able to handle this in the proxy itself, to keep things easier for clients (who may not have the ability to put the proxy on a separate domain).

A clever friend said "When they are both on the same domain, the cookie is being overwritten. The proxy needs to forward on the entire header that the browser would make".

Does that help, and is that possible?

**Comment by slead** [comment]
Bingo! Putting the proxy onto a separate subdomain on localhost avoids the problem. I'll use this as the workaround for now, but it would be great if you can fix this within the proxy itself.

Many thanks for the help in debugging this one.

**Comment by phpmaps** [comment]
@slead Great thanks.  Would you take a moment to share the headers, aka the full request and response headers now that you are running the proxy on a different subdomain.  (like you did above) That would be good info to capture.

**Comment by bsvensson** [comment]
Closing since it sounds like a solution was found by putting one proxy on each domain.
