### ISSUE TITLE
JSP: set Content-Type to json for errors

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#205]
Tomcat by default serves HTML files with Content-Type=text/html (no charset portion).

When we return JSON we should set the Content-Type to JSON. We already do this for "ping", but not for error responses.

Test `http://localhost:8080/Java/proxy.jsp?oops` or `http://localhost:8080/Java/proxy.jsp`

**Comment by esoekianto** [comment]
fix at #206 , the same behavior was also observed in other java web server (I tested on WebSphere too)
