### ISSUE TITLE
Password with a '?' not handled

### ISSUE THREAD

**Issue by tr3vorm** [Esri/resource-proxy#210]
After upgrading to 10.3 I discovered that one of our passwords was not being accepted as a valid credential because it contained a "question mark". I updated to the current build of the proxy.ashx (.Net) to get around another AGS 10.3 bug but it looks like my problem is caused by the proxy treating the '?' as a query delimiter. 

I have changed offending passwords, but it may be worth fixing this.

**Comment by esoekianto** [comment]
@tr3vorm thank you for submitting this, I can reproduce the same issue and patch a fixed for this #211 

If you have time , can you test this fix for me? Thanks

**Comment by tr3vorm** [comment]
Works now thanks. Apologies for not trying to fix this myself. Was easier to just change the password :-)

**Comment by esoekianto** [comment]
@tr3vorm not a problem, the proxy needs to be able to handle this anyway

**Comment by esoekianto** [comment]
JSP version of this fixed #212
