### ISSUE TITLE
Support for basic auth under https and custom port

### ISSUE THREAD

**Issue by majales** [Esri/resource-proxy#213]
Hi,
I tried to use resource proxy for remote wms server on secure https website protected by basic auth and had no luck. I'm allways getting error 500 in log. Is there any chance that resource proxy would support this auth and custom https port?

**Comment by jtroe** [comment]
I have this implemented in a custom build.  It works against a web adaptor with web-tier authentication instead of to a gis-tier configuration as the resource-proxy seems to support now.

Is this what you're looking for?  If so, I could raise a pull request with the changes.

**Comment by majales** [comment]
Hi,
Thanx for answer. I don't know how exactly configure web-tier auth with Web Adaptor, but it should be generic basic auth without any special forms or tokens. I've got SSL URL with WMS service protected by basic authentication. I'd like to configure credentials in resource proxy configuration and force arcgis server web client to access this map resource through resource proxy.

**Comment by bsvensson** [comment]
@majales - is the service you're trying to use on your machines?  If not, you shouldn't have to configure web adaptor.

Which proxy are you using?
I have a version of the PHP proxy that supports [HTTP Basic Access Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). It's not thoroughly tested but works on my machine...

**Comment by majales** [comment]
Hi. No, the service is external independent WMS service accessible via secured web ( https) with username and password. I'm using .NET proxy at the moment, but I can switch to PHP version without problem. Could you please publish your PHP proxy with HTTP Basic Access Authentication support?
