### ISSUE TITLE
proxy.jsp - 498

### ISSUE THREAD

**Issue by MrPaulg** [Esri/resource-proxy#214]
Hi, 
apologies for the non technical syntax of this issue I'm having, and if I have posted in the wrong location, please feel free to move or remove my post.
I have used the 'latest release' and the 'master' version of proxy.jsp, I have had issues with both but have persevered with the master version. It works once you only use the www.mydomain.com or “*” referrers, it refuses to use application url’s. Then after a period of working it fails and the logs never produce an error, but you can see the json request it stops at in the logs. The app using the proxy then presents the login UI (it’s a flex app) for credentials for the service endpoints. I’m not a developer so I recruited a developer (bribed) to take a look to see what’s happening. With a bit of rooting around we have noticed that the proxy was looking at the Http response and checking for a 498 error which it doesn’t get (See attached image)  – the http request returns 200 as the request was fulfilled correctly, however the json response contains the ‘498’ which is the real error which in the byte stream is encoded so apparently not easy to extract(??) but this byte stream response is a certain length which is unique in our case 79 so we use this to setthe flag to true it then goes and gets a token and we are good to continue.  Below is the temporary fix to see if we are going in the correct direction, it’s a hack for a temporary solution only, once we have time we will take a better look …

if (con.getResponseCode() >= 400 && con.getErrorStream() != null){
 if (ignoreAuthenticationErrors && (con.getResponseCode() == 498 || con.getResponseCode() == 499)) return true;
            byteStream = con.getErrorStream();
        }else{
            byteStream = con.getInputStream();
        }

        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        final int length = 5000;

        byte[] bytes = new byte[length];
        int bytesRead = 0;

        while ((bytesRead = byteStream.read(bytes, 0, length)) > 0) {
            buffer.write(bytes, 0, bytesRead);
        }
        buffer.flush();

        byte[] byteResponse = buffer.toByteArray();

	String dump = "DEBUG DUMP: " + byteResponse.length;
	
	_log(Level.INFO, dump);

	if ( byteResponse.length == 79) {
		_log(Level.INFO, "JSON Error DETECTED!!!!");
		return true;
	}

So are we going about this the correct way or have I missed something, any help is appreciated as the proxy is vital  for future work, and most of all it has to be constantly up and available.

![200498](https://cloud.githubusercontent.com/assets/11313276/6527121/222f5724-c410-11e4-9331-37e4c48fc314.png)

**Comment by cheetah90** [comment]
@MrPaulg sorry for getting back really late. This issue sounds like this one #146. Could you take a look and help us figure out if it's the same? If it is, we recently fixed it in #245. Please use the master branch code :)

**Comment by bsvensson** [comment]
Closing as I believe this has been fixed by the recent updates.
