### ISSUE TITLE
.NET Proxy - ESRI pop up attachment link redirects to REST Login

### ISSUE THREAD

**Issue by taran03** [Esri/resource-proxy#216]
I have a JavaScript web map with pop up widget info window functionality.  The attachment links display as intended within the pop up window, but when the user clicks on the attachment link the URL is calling for a redirect that requires the user to authenticate with our ArcGIS REST endpoint in order to see the attached image. Of course, the attachment links work fine if the service is public. I'm using .NET proxy to auto authenticate user access to secure services, so I'm a little stumped as to why clicking on the attachment link leads to a login redirect page instead of direct authentication from the functioning proxy. Any thoughts how I can auto bypass the redirect authentication required to see the attached images? Thanks.

![image](https://cloud.githubusercontent.com/assets/8386074/6559724/da18570c-c652-11e4-84a6-b2bea733b2db.png)

![image](https://cloud.githubusercontent.com/assets/8386074/6559730/e2100144-c652-11e4-8264-2824683d9c30.png)

**Comment by jgravois** [comment]
you are able to indicate to the JSAPI to utilize a proxy when accessing individual services via AJAX requests, but this is different than expecting it to intercept generic `<a href>` links in the DOM.

i know that's not the most helpful information in the world, but the proxy can't field a request that doesn't get directed at it.
