### ISSUE TITLE
ArcGIS Online SSL enabled fail to consume http: 

### ISSUE THREAD

**Issue by Murkor** [Esri/resource-proxy#218]
We have implemented SSL in ArcGISOnline against a domain (SSL enabled: this is a our client's policy they must use SSO).  We have deployed an app on ArcGIS Online, the webMap has security service hosted in the AGS (certificates work properly) and others free services hosted outside of the organization (government's services).  This solution arise an issue because all calls to services are sending  "https" and fail when calling the free service hosted outside of the organization whose are exposed with not security (just htttp).  Is there any solution using the proxy approach in order to modify the https to http for those services hosted outside of the organization ?

fhernandez@esri.cl

**Comment by jgravois** [comment]
it sounds as if you'd like calls to your proxy over HTTPS to fetch HTTP resources and present them back to the end-user as if they were hosted with SSL/TLS (to bypass mixed-content warnings in the browser).  AFAIK, this is not a usage we intend to support.

check out [this blog]()http://blogs.esri.com/esri/arcgis/2015/03/11/sharing-web-gis-services-always-enable-tls/) for more information.
