### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by michaelschnack** [Esri/resource-proxy#220]
Had this working on IIS 7 & Windows server 2008.  But now on IIS 8.5 & Windows Server 2012, the error returned is:
{error: {code: InternalServerError,message:"Unable to connect to the remote server http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson"}}

I have installed .NET 4.5, and tried changing the web.config to targetFramework="4.5"

**Comment by esoekianto** [comment]
@michaelschnack can u try open this url "http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson" in the web browser in the server?

I suspect the server can not access this url "http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson"

**Comment by michaelschnack** [comment]
I am able to connect directly to the URL.

**Comment by esoekianto** [comment]
@michaelschnack can you try to proxy to some internal url? preferably ags server that is in the network. 

the next step for this would be to check the user of the application pool that the proxy is using in IIS. I remember we had weird issue with .NET 4.5 in Windows Server 2012, can you try .NET 4.0?

**Comment by michaelschnack** [comment]
Proxy to internal server does work, thank you.

**Comment by jgravois** [comment]
@michaelschnack logging a call through our standard technical support channel would probably be the most expeditious route to trapping the cause of the problem you are having.  are you able to do that?

**Comment by michaelschnack** [comment]
@jgravois I'll run it by Esri support, thanks.

**Comment by esoekianto** [comment]
@michaelschnack if proxy to internal server works, that means the server or the user of the application pool that the proxy is using in IIS cant make the request to "http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson"

yes, Esri Technical support should be able to help you troubleshoot this.

**Comment by carrbrpoa** [comment]
Hey @michaelschnack, were you able to solve this issue?
Thanks

**Comment by jgravois** [comment]
@carrbrpoa if the server itself cannot access resources on the outside internet, the proxy will not be able to retrieve those resources either.

in some cases we've found servers that are entirely firewalled, in others, the IIS user assigned to fetch resources in the .NET application pool utilized by the proxy is prohibited specifically.

**Comment by carrbrpoa** [comment]
Hey John,

If I login in the machine with the same app pool configured user, I can
browse the internet normally (thanks to Internet Options' proxy config).
I'll just confirm tomorrow if I can browse the same addresses negated by
the proxy, which I didn't tried.

Thanks

**Comment by carrbrpoa** [comment]
Well, actually it worked today. I don't know what happened yesterday, maybe some user permissions/proxy glitch. Thanks anyway.

**Comment by brysageek** [comment]
Have found that the issue was the AppPool identity -- will look into further and try and get further details
