### ISSUE TITLE
.Net proxy - asp.Net 5

### ISSUE THREAD

**Issue by stokseth** [Esri/resource-proxy#223]
Hi,

asp.net 5 has changed a lot from previous versions of asp.net. As far as I know System.Web no longer exists. So using a ashx file as proxy, will no longer work.

Instead I guess you have to write a middelware class and include it in Startup.cs with app.UseMyMiddleware().

Any plans for creating a new proxy for asp.net 5 ?

**Comment by bsvensson** [comment]
Hi @stokseth,
No, at this point, we don't have any plans for creating a new proxy for asp.net 5.  Once it's released, we might revisit this.

Note, as far as I understand, legacy apps will continue to run on the new version of the ASP.NET [without any modifications](http://www.asp.net/vnext/overview/aspnet-vnext/aspnet-5-overview).
