### ISSUE TITLE
"client" parameter is now required for generate token request in 10.3

### ISSUE THREAD

**Issue by esoekianto** [Esri/resource-proxy#224]
We just encountered that there is an update to ArcGIS Server 10.3 for generate token request, now requires “client” parameter to be included in the request, otherwise we will get this error, 

“{"error":{"code":201,"message":"Exception in generating token","details":"Exception in generating tokenFailed to generate a token for the user.Client ID is required for long expiration tokens."}}”

@afili  and I just made a quick patch to the .NET version for a user, by adding the “client” parameter in the generate token request, and this addition seems to be working with previous version of ArcGIS Server. 

https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.ashx#L508 

Before : string uri = tokenServiceUri + "?f=json&request=getToken&referer=" + PROXY_REFERER + "&expiration=60&username=" + su.Username + "&password=" + su.Password;

After : string uri = tokenServiceUri + "?f=json&client=HTTP Referer&referer=" + PROXY_REFERER + "&expiration=60&username=" + su.Username + "&password=" + su.Password;

So we need to make this changes to all version of the proxy.

I tested with ArcGIS server 10.2, and this change does not break anything, maybe we should try with older version to make sure.

Reference to ArcGIS Server documentation. http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Generate_Token/02r3000000m5000000/

**Comment by jgravois** [comment]
good find @esoekianto .  
in general, shouldn't cause any trouble in older versions of ArcGIS Server as unknown params are typically ignored.

**Comment by bsvensson** [comment]
Duplicate/solution for #177 which has been fixed and closed.
