### ISSUE TITLE
PHP script returning empty query response

### ISSUE THREAD

**Issue by kingrollo** [Esri/resource-proxy#225]
Hi,

I've got a problem with a complex Map Service which is returning its response too slowly. I appreciate the best fix here is to do some fine tuning on the service, but it did highlight a problem with the proxy code (in the PHP version, anyway).

Manually signing into ArcGIS Server and calling the query URL http://server/arcgis/rest/services/SERVICE/MapServer//identify?f=json&tolerance=5&returnGeometry=true&imageDisplay=958%2C670%2C96&geometry=...&geometryType=esriGeometryPoint&sr=102100&mapExtent=...&layers=...
takes around 7 seconds but works fine - the response is valid JSON.

Calling it via the proxy:
proxy/proxy.php?http://server/arcgis/rest/services/SERVICE/MapServer//identify?f=json&tolerance=5&returnGeometry=true&imageDisplay=958%2C670%2C96&geometry=...&geometryType=esriGeometryPoint&sr=102100&mapExtent=...&layers=...
takes around 5 seconds and returns a completely blank response. The PHP is returning a 200 header but zero bytes of content, which is causing problems for my front-end client (I think I'm right in saying that a blank response isn't valid JSON?)

I tried playing with the PHP set_time_limit call, but it didn't appear to be making any difference. Even if set, it seems to me that ideally the proxy would recognise the timeout and return a valid error code rather than an empty response.

Hopefully this gives you enough details to investigate the issue? As a short-term fix I've reduced Maximum Number of Records Returned by Server on the service to 100 (1000 seems pretty crazy anyway in retrospect), but this is hiding the problem rather than solving it!

Thanks!
r.

**Comment by tgeorge** [comment]
What version of PHP are you using?

I had something similar going on with 5.5.12 where the images wasn't being loaded but giving me a 200 header. I tested it on 5.6.10 which worked fine and I settled with 5.5.26.

**Comment by kingrollo** [comment]
@tgeorge Sorry! only just saw this. I'm using PHP 5.6.8.

**Comment by akaSStalkALEX** [comment]
Does anybody know solution to this problem or maybe work around?

**Comment by akaSStalkALEX** [comment]
In case someone  experienced the same problem with blank screen after json_decode, there is global config turning off error reporting in proxy script. After turning it on, I was able to see all errors.
