### ISSUE TITLE
How can the proxy.ashx file be modified to work with a Proxy on a LAN?

### ISSUE THREAD

**Issue by Tapas-Das** [Esri/resource-proxy#226]
All our servers operate behind a firewall which blocks direct connections to the outside world. All communication must go through a Proxy.

How can the proxy.ashx file be modified to make it aware that there is a proxy on the Local Area Network?

We had to tweak the server/proxy.js file with this proxy information before we could run the Web AppBuilder developer edition 1.1

if (req.method === 'GET') {
        requestParams = {
          url: url,
          rejectUnauthorized: false,
          requestCert: true,
          agent: false,
          proxy: 'http://path_to_proxy:port',

   } else if (req.method === 'POST') {
        requestParams = {
          method: 'POST',
          url: url,
          form: req.body,
          rejectUnauthorized: false,
          requestCert: true,
          agent: false,
          proxy: 'http://path_to_proxy:port',

Is there a similar way to tweak the proxy.ashx file to make it aware that all connections to the outside world must be routed through a proxy?

When we try to test the proxy with this URL, it fails with an HTTP 500 error:

http://machine_name.domain_name/proxy/proxy.ashx?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson

The reason being, it is trying to make a direct connection to http://services.arcgisonline.com
The firewall is blocking this.

If there is a way to make proxy.ashx communicate with the outside world via the Proxy on our LAN, our problem will be solved.

We are talking about the DotNet version of the proxy.

Best regards,

Tapas Das

**Comment by cheetah90** [comment]
@Tapas-Das sorry for the late reply. I am trying to understand what URL it would look like if it's proxied by your proxy. Is it something like `http://{your_own_proxy}?http://www.google.com`?
Thanks

**Comment by Denverino** [comment]
Hi. I have the same issue with the proxy on a Lan. How can i fix it? Thanks for any help.

**Comment by Tapas-Das** [comment]
Hi Denverino,

The fix is very simple when you have a Proxy on your Local Area Network.
I have explained it on pages 221 through 226 of this Help Guide:

http://www.tapasdas.com/WABv2.pdf

You have to open IIS Manager and tweak it so that it is aware that you have a Proxy on your LAN.

Open the Configuration Editor under Management

Expand the drop down list for Section

Select defaultProxy under system.net

Expand the Proxy tree

Enter your Proxy Address

Click Apply

**Comment by Denverino** [comment]
Tapas-Das, big thanks for so fast answer!I think it's resolve my problem. Tomorrow i will test it.
