### ISSUE TITLE
How can I use the proxy without storing the password in cleartext?

### ISSUE THREAD

**Issue by phillipgreenii** [Esri/resource-proxy#228]
Right now we are using the DotNet proxy, but it requires me to store the password in clear text.  Is there away do handle the authentication more securely?

**Comment by bsvensson** [comment]
When possible, it's better to use clientId/clientSecret.

https://developers.arcgis.com/authentication/working-with-proxies/

**Comment by phpmaps** [comment]
Phill I also want to add that you can set permissions on the server folder itself to limit access as to who can see the config file.

**Comment by phillipgreenii** [comment]
@bsvensson  Once I created an application, the client id/client secret seems to work.  Thanks
