### ISSUE TITLE
Secure ArcGIS Server WFS?

### ISSUE THREAD

**Issue by lccspatial** [Esri/resource-proxy#230]
Hi,

Is this possible? Manual browser run using proxy.ashx and arcgis server token & login page resolves ok.

Currently raising below:

[ApplicationException: Unable to determine the correct URL to request a token to access private resources]
   proxy.getNewTokenIfCredentialsAreSpecified(ServerUrl su, String reqUrl) in c:\inetpub\wwwroot\SLProxy\proxy.ashx:418
   proxy.ProcessRequest(HttpContext context) in c:\inetpub\wwwroot\SLProxy\proxy.ashx:186
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +913
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165

**Comment by bsvensson** [comment]
#266 (and/or other recent updates) should have fixed this.
