### ISSUE TITLE
Failure to load proxied map service until browser is refreshed

### ISSUE THREAD

**Issue by taran03** [Esri/resource-proxy#236]
I'm wondering if anybody has encountered issues with the DotNet proxy and Server 10.3 where the proxy appears to timeout? This map service loading issue typically occurs when a web map has not been opened for a period of time, maybe about 1 hour or more. I have not been able to nail down that time interval. I have limited clues for troubleshooting other than the following two tidbits:

1. Web maps I have deployed without any reference to this proxy don't exhibit these map service loading issues
2. I see the following console messages in Chrome 
  
Failed to load resource: net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH
https://pm.X.com/DotNet/proxy.ashx?https://maps2013.X.com/maps/rest/s…ue&format=png32&callback=dojo.io.script.jsonp_dojoIoScript4._jsonpCallback Failed to load resource: net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH
https://pm.X.com/DotNet/proxy.ashx?https://maps2013.X.com/maps/rest/s…ue&format=png32&callback=dojo.io.script.jsonp_dojoIoScript2._jsonpCallback Failed to load resource: 
init.js:967 dojo.io.script error q {message: "Timeout exceeded", response: Object, log: undefined}
init.js:967 dojo.io.script error q {message: "Timeout exceeded", response: Object, log: undefined}

My JavaScript web map ultimately loads with the ESRI basemaps and other map services from outside my organization, but the proxied map services do not load until I do a browser page refresh. Refreshing the web browser one time always resolves the issue and the map loads with all the map services as expected.  This loading issue is also observed across web browsers, not just in Chrome.

**Comment by JeremiahUM** [comment]
I think I experienced this issue as well, it occurs after a cached token expires.  The copyHeaders function adds a second content-length to the header when a new token is obtained. One possible fix is to change the copyHeaders function to the following:

private void copyHeaders(System.Net.WebResponse fromResponse, HttpResponse toResponse)
{
	foreach (var headerKey in fromResponse.Headers.AllKeys)
	{
		switch (headerKey.ToLower())
		{
			case "content-type":
			case "transfer-encoding":
			case "accept-ranges":   // Prevent requests for partial content
				continue;
			case "content-length":
			case "length": // content-length,length must not have multiple values
				toResponse.Headers[headerKey] = fromResponse.Headers[headerKey];
				break;                    
			default:
				toResponse.AddHeader(headerKey, fromResponse.Headers[headerKey]);
				break;
		}
	}
	toResponse.ContentType = fromResponse.ContentType;
}

**Comment by taran03** [comment]
@JeremiahUM, thank you. This tweak to the code appears to have resolved the issue.

**Comment by cheetah90** [comment]
Hi @taran03 and @JeremiahUM thanks for bringing this issue up and offer the solutions. Can you provide more details in what scenario you get the the "second content-length to the header when a new token is obtained". I am trying to reproduce this issue and add the fix to the master branch :) Thanks.

A related thing, regarding the "proxy failed after 1 hour". We do notice that there is a bug in the DotNet proxy regarding token expiration, I will shortly submit a fix and let you know.

Thanks

**Comment by JeremiahUM** [comment]
Hi @cheetah90, from my experience to replicate the issue you just need to make a request through the proxy that causes the proxy to get and store a token.  Then after that token expires (1 hour by default), the first request made that tries to use that token will have the error.  I was also able to replicate the issue by reducing the "Lifespan of Short-Lived Tokens" on our arcgis server down to a few minutes and changing the expiration in the proxy's token request uri to match, that way you don't have to wait an hour for every test.

**Comment by cheetah90** [comment]
@JeremiahUM thanks for the reply! Yes, we are aware of this 1-hour-token-expiration bug. But as far as I know, this will give back a JSON file containing "code 498: invalid request". But how is this related to your fix regarding the second "content-type"?
```
case "content-length":
case "length": // content-length,length must not have multiple values
toResponse.Headers[headerKey] = fromResponse.Headers[headerKey];
break;
```

**Comment by JeremiahUM** [comment]
@cheetah90, In the DotNet proxy, the function fetchAndPassBackToClient will return true when the response has the "code: 498" in it.  The proxy then attempts to get a new token and calls fetchAndPassBackToClient again, which calls copyHeaders again.  The second call to copyHeaders adds a second content-length value to the headers with the current code.  I hope that makes sense.

```
//first attempt to send the request:
bool tokenRequired = fetchAndPassBackToClient(serverResponse, response, false);

//checking if previously used token has expired and needs to be renewed
if (tokenRequired) {
	log(TraceLevel.Info, "Renewing token and trying again.");
	//server returned error - potential cause: token has expired.
	//we'll do second attempt to call the server with renewed token:
	token = getNewTokenIfCredentialsAreSpecified(serverUrl, uri);
	serverResponse = forwardToServer(context, addTokenToUri(uri, token, tokenParamName), postBody);

	//storing the token in Application scope, to do not waste time on requesting new one untill it expires or the app is restarted.
	context.Application.Lock();
	context.Application["token_for_" + serverUrl.Url] = token;
	context.Application.UnLock();

	fetchAndPassBackToClient(serverResponse, response, true);
}
```

**Comment by cheetah90** [comment]
@JeremiahUM Yes. I completely understand now :) Looking at the code, it seems that the [`copyHeaders()`](https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.ashx#L385) is called too early than it should be. I will fix the issue and let you know! Thanks again for your help!

**Comment by cheetah90** [comment]
PR submitted. #253

**Comment by cheetah90** [comment]
Fixed and can be closed! Thanks @taran03 and @JeremiahUM
