### ISSUE TITLE
DotNet: doc the "domain" property

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#269]
Support was added in https://github.com/Esri/resource-proxy/pull/118 to allow for Windows authentication.

**Comment by bsvensson** [comment]
Both the https://github.com/Esri/resource-proxy/blob/master/DotNet/README.md and  https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.xsd needs updating as part of this issue.

**Comment by jgravois** [comment]
protip&trade;
it'll close issues like these automatically if you include a [keyword](https://help.github.com/articles/closing-issues-via-commit-messages/) in the initial comment of your Pull Request
