### ISSUE TITLE
CHANGELOG needs updated

### ISSUE THREAD

**Issue by jgravois** [Esri/resource-proxy#270]
we should be updating the CHANGELOG with a new 'Unreleased' section (like [this](https://github.com/koopjs/koop/blob/master/CHANGELOG.md)) to keep track of code changes since 1.0 and including new line items in future PRs.  

this will make tagging the next release and announcing what's included significantly more straightforward.

---
background info on why we should [keep a changelog](http://keepachangelog.com/)

**Comment by bsvensson** [comment]
Good idea about the "Unreleased" section. Thanks @jgravois.

**Comment by jgravois** [comment]
I'd also suggest that we move to using [Semantic Versioning](http://semver.org/) (ie: tagging the next release as 1.1.0) so that we can isolate and release fixes for an individual proxy (or all 3) in patches more easily.

**Comment by bsvensson** [comment]
I updated the two open milestone labels from 1.1 and 1.2 to 1.1.0 and 1.2.0
