### ISSUE TITLE
dot in query string causes "Unsupported Referer" via checkWildcardSubdomain()

### ISSUE THREAD

**Issue by aaronkilbey** [Esri/resource-proxy#284]
Been chasing down 403s from 1.1.0 version using allowedReferers="//*.domain.com".  URLs with coords that have dot failed referer checking.  checkWildcardSubdomain() splits on dot to make part comparisons to allowedReferer, and requestedReferer can have a query sting with a dot.  suggest chopping off query string before comparison

**Comment by cheetah90** [comment]
Hi @aaronkilbey, thanks for the suggestions. We are aware of this bug and are trying to fix it in the next release. Will update here about the specific pull request in case you want to manually apply the patch. Thanks

**Comment by cheetah90** [comment]
@aaronkilbey can you tell us which proxy are you using? DotNet or JSP?

**Comment by aaronkilbey** [comment]
DotNet on 2012/IIS 8.5.  Also, in evaluating responses for this, I noticed the error return has IIS HTML output after the JSON "Server Error in '/' Application...''.  Fixed by response.End(); at the end of sendErrorResponse().  (I know barely enough asp to debug this otherwise I'd pull request)

**Comment by cheetah90** [comment]
This is fixed by #285 and can be closed! Thanks @aaronkilbey
