### ISSUE TITLE
Token Required with Login Prompt

### ISSUE THREAD

**Issue by djg07** [Esri/resource-proxy#289]
I've been attempting to set this up using the instructions in the Readme.md, but keep getting a "Token Required" error and subsequent login prompt when attempting to access the secured map service. 

.config file looks like this:
```xml
<ProxyConfig mustMatch="false" allowedReferers="*">
<serverUrls>
      <serverUrl url="xxx/arcgis/rest/services/WebCom/Animal_Density_Bovine/MapServer" username="map1dev_user" password="xxx" matchAll="true"></serverUrl>
</serverUrls>
</ProxyConfig>
```

I tried getting a token from the rest interface and passing it in as "token='xxx'" but that didn't work either. Also, I am noticing I can't hit a breakpoint in proxy.aspx

**Comment by esoekianto** [comment]
@djg07 
the proxy configuration file looks good to me. but the fact that passing the token didn't work is probably the key information here (assuming that we set the referer value correctly when generating the token)

Can you try different user maybe? It is probably easier if you can call esri tech support, we can help you debug this.

**Comment by djg07** [comment]
@esoekianto 

Just tried it with a different user with read privileges, same result. 

I've been using "IP" as the Client when generating the token. Is this correct?

**Comment by esoekianto** [comment]
@djg07 thats okay. 

The requests in your application are going thru the proxy right? You can try to also change the mustMatch property in proxy.config to true.

**Comment by djg07** [comment]
Yup they are going through the proxy successfully.

**Comment by djg07** [comment]
@esoekianto I updated to the most recent version of proxy.ashx . It is now working as expected.

**Comment by 2496772010** [comment]
I have the same problem.when i use the mapserver in html to open in web, it reminds me to login .
