### ISSUE TITLE
Pass current user's Integrated Windows Authentication credentials through the proxy

### ISSUE THREAD

**Issue by stewrouse** [Esri/resource-proxy#292]
Currently, the proxy allows users to hard code their IWA credential in the proxy.config file to be passed to a server that is set up to accept IWA credentials as suitable logins.  Some users would find it useful if the proxy could get the credentials of the currently logged in user to pass to the proxy in lieu of hard coding the credentials in the proxy.config file.

There is a enhancement request that highlights this request: NIM043102.

**Comment by jgravois** [comment]
if the user has appropriate credentials to access the secure resource, why proxy the request?

do your browsers/server not support CORS?

**Comment by stewrouse** [comment]
In the case where this Issue originated, the user’s browser did not support CORS.  It was a government agency and they were using IE9 and did not have access to any other web browsers.

The request had to be sent through the proxy because it was an Add Features request which only accepts Post requests.

If I am understanding things correctly, current browsers support CORS and do not need a proxy to make a post request, which would essentially mean that there is no use for a proxy unless the service is secure.  Am I correct in that assessment?

**Comment by jgravois** [comment]
exactly.  proxies assist in POSTing across domains when CORS is not supported.

see [this](https://developers.arcgis.com/javascript/jshelp/ags_proxy.html) article for a little more info.

**Comment by stewrouse** [comment]
The use case I am advocating for is less about the CORS aspect of using the proxy, and more about passing credentials along using the proxy.  Since ArcGIS for Server has the capability to accept IWA credentials, it could be useful for the proxy to be able to automatically get those credentials from header of the request that is sent to the proxy, and have the proxy pass the credentials to the server.

Am I misunderstanding the capabilities of the proxy and it’s uses?

**Comment by bsvensson** [comment]
@stewrouse - which proxy are you using? 

For DotNet, this was supposed to be fixed by https://github.com/Esri/resource-proxy/pull/118 (DotNet: Allow Windows Authentication). (Or is that not the issue you are describing?)

**Comment by jgravois** [comment]
if the end user is capable of passing their own credentials to access the secure resource the proxy is unnecessary, except in the case you outlined above (when assistance is needed to POST across domains because either the client browser or web server doesn't support CORS.

if that's what you're asking for, we can look into it, but it'd also be appropriate for you to investigate establishing CORS support in your environment and skipping use of the proxy entirely.

**Comment by stewrouse** [comment]
I am using the DotNet proxy, and yes it was fixed. You are able to hardcode Windows Authentication credentials in the proxy and pass them from the proxy to the server. I am referencing having the proxy automatically get the credentials from the user that is logged in, and passing them to the Server.  I have been emailing John Gravois about this issue.

**Comment by irisevenstar** [comment]
I need this as well. In my case, I don't believe it's a CORS issue, but an applyEdits request that exceeds 2048 characters to a secured service, and is therefore being pushed through the proxy. I want the current user's credentials to determine access to the service.

**Comment by meghan452** [comment]
@stewrouse  I'd appreciate how you're able to achieve 'having the proxy automatically get the credentials from the user that is logged in, and passing them to the Server'. 

Thanks
