### ISSUE TITLE
mustMatch = false not working in DotNet

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/resource-proxy#294]
I'm not sure if this is a bug or just something wrong with my proxy.config, but when setting the mustMatch option to false, the proxy still will not allow any URL to be proxied, instead replying with:

*The request URL does not match with the ServerUrl in proxy.config! Please check the proxy.config!*

from line 122 in proxy.ashx

**Comment by jgravois** [comment]
are you working with the 1.0 release of the proxy or did you download source from the active `master` branch?
can you copy/paste your proxy.config and an example of one of your requests?

at the bare minimum, you'd need something like this
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
             mustMatch="false">
    <serverUrls>
    </serverUrls>
</ProxyConfig>
```
http://[yourmachine]/[folder]/proxy.ashx?http://services.arcgisonline.com/arcgis/rest/services

**Comment by sverkerEsriSE** [comment]
I am using the latest master branch (from a few days ago). 1.1.0 beta
I tried the bare minimum proxy.config as you suggested, same error.

Replicated this on all machines I tested on.

A request can look like this:

`http://[externalsite]/proxy/proxy.ashx?http://www.google.com`

Also tried the default proxy.config, but changed *mustMatch* to *false*

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
             mustMatch="false">
    <serverUrls>
        <serverUrl url="http://services.arcgisonline.com"
                   matchAll="true"/>
    </serverUrls>
</ProxyConfig>
```

**Comment by djg07** [comment]
@sverkerEsriSE 

Just want to confirm, you are setting the same URL in your application code as the one in the <servelUrl> tag in proxy.config?

**Comment by sverkerEsriSE** [comment]
I am accessing the proxy.ashx directly for testing purpose, so I am not going trough an application.

As I understand it from the README, you should be able to have the proxy work with any URL, and it did work that way in the release version 1.0.

Looking at the proxy.ashx code, the flow of the method GetConfigServerUrl will always try to match up with the URL:s in proxy.config, and if there is no match, it will return null. This was the same in the release version 1.0.

However, in 1.0, we have the following code in ProcessRequest:
```c#
bool passThrough = false;
try {
serverUrl = getConfig().GetConfigServerUrl(uri);
passThrough = serverUrl == null;
}
```

This code seems to be removed in the latest version on github, and thus, the "passThrough" functionality is missing.

Maybe the function is not complete yet, or the documentation is lacking.

**Comment by gavinr** [comment]
I've seen this issue too.

**Comment by esoekianto** [comment]
@jgravois @bsvensson I can repro this issue. 

It looks like this issue started happening after this commit https://github.com/Esri/resource-proxy/commit/4bafdd234e415c0c3fe84fd89d19f26db60b8daf

**Comment by esoekianto** [comment]
fix at #297

**Comment by jgravois** [comment]
@gavinr @sverkerEsriSE can you guys confirm everything looks good on your side too when you have a minute please?

**Comment by sverkerEsriSE** [comment]
@jgravois Yeah, it's working now. Thanks @guo7711 !

**Comment by gavinr** [comment]
:+1:

**Comment by esoekianto** [comment]
@gavinr @sverkerEsriSE thank you for testing and confirming
