### ISSUE TITLE
Proxy.php and Sample API not working together

### ISSUE THREAD

**Issue by thewordsmith** [Esri/resource-proxy#295]
Thus far I have been able to configure the proxy.php system so it works on its own. Like testing the configuration at  http://freshsoftware.net/usps/eddm/sample_api/proxy/proxy-verification.php. 

I can also test the argis json response by running http://freshsoftware.net/usps/eddm/sample_api/proxy/proxy.php?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson.

But I have not been able to get the SAMPLE API to work with the the PHP Proxy. I even tried editing geoprocessing.js by editing the line 41 so it says esriConfig.defaults.io.proxyUrl = "/proxy/proxy.php"; But the sample_api still does not work. Try it your self at http://freshsoftware.net/usps/eddm/sample_api/?secret_key=MTI1ZjVyN3JBNTY2dDJlcjE1d2tyNTQ0dWprNDhraklXUzZuJXdrZGprSkg=.

How do I get the SAMPLE API to work with PROXY.PHP?

**Comment by phpmaps** [comment]
@thewordsmith  - Since it looks like your test page is working, I think the problem appears to be inside your JS application.  Your application is not resolving the location of your proxy.php.  Your server is throwing a 404.  You app thinks your proxy is here.

```
http://freshsoftware.net/proxy/proxy.php?....
```

However, really I think your proxy lives here...

```
http://freshsoftware.net/usps/eddm/sample_api/proxy/proxy.php
```

**Comment by thewordsmith** [comment]
I created a symlink from document_root/proxy/proxy.php to usps/eddm/sample_api/proxy/proxy.php and that solves the connection problem.

Now I am getting the following error in my proxy_log.log file.

09-12-15 21:51:30 | GET detected
09-12-15 21:51:30 | Proxy could not resolve requested url - http://stg-production.shippingapis.com/ShippingAPI.dll/execute.  Possible solution would be to update 'mustMatch', 'matchAll' or 'url' property in the configuration file.

I tried briefly to edit the config file to no success. It is past my bed time and I will try again tomorrow morning. But before I reinvent the wheel if you know the proper configuration please share that information.

Sulaiman

**Comment by phpmaps** [comment]
Hi Sulaiman - when ````mustMatch```` is true the proxy will only broker requests to URLs listed in the ````serverUrls```` element.  You likely need to update your config with something like this. 

````
      <serverUrl
          url="http://stg-production.shippingapis.com"
          matchAll="false"/>

````

**Comment by thewordsmith** [comment]
I was able to resolve the stg-production.shippingapis.com problem. Now when I use the Polygon or Freehand I see an authentication error when I press F12 and follow proxy/proxy.php. I set the username/pass in proxy.config but I still get the authentication error. 

<?xml version="1.0" encoding="UTF-8"?>
<Error><Number>80040B18</Number><Description>An error has occurred with the service.  Please contact the system administrator, or try again.</Description><Source>USPSCom::DoAuth</Source></Error>

Also when I use the webtools page I do not get an auth error. See: http://www.freshsoftware.net/usps/eddm/sample_api/webtools.php?secret_key=MTI1ZjVyN3JBNTY2dDJlcjE1d2tyNTQ0dWprNDhraklXUzZuJXdrZGprSkg=

Once again the url is http://www.freshsoftware.net/usps/eddm/sample_api/?secret_key=MTI1ZjVyN3JBNTY2dDJlcjE1d2tyNTQ0dWprNDhraklXUzZuJXdrZGprSkg=

But

**Comment by phpmaps** [comment]
I am not sure Sulaiman.  A few things seem a bit unusual to me.  That error you see is not an error message built into the PHP proxy.  You can scan the source code to confirm that.  Also it's not clear why you've got the key value ```secret_key=xxxxx``` within your request.  That is not a convention I am familiar with.

Perhaps  use chrome debugger tools and paste the entire GET or POST here, so the problem can be reproduced.

**Comment by thewordsmith** [comment]
The Secret Key is for later use in my development. Use FireFox for the link bellow. After making a polygon press F12 to view the debug console log 
![js_console](https://cloud.githubusercontent.com/assets/10285202/9842665/ebf96946-5a7e-11e5-8248-3fe6da5899f3.jpg)
and click on proxy/proxy.php.

http://www.freshsoftware.net/usps/eddm/sample_api/?secret_key=MTI1ZjVyN3JBNTY2dDJlcjE1d2tyNTQ0dWprNDhraklXUzZuJXdrZGprSkg=

**Comment by phpmaps** [comment]
@thewordsmith after close look the problem does not seem to be the PHP proxy.   If you remove the proxy and send a request to this address

 ```
http://stg-production.shippingapis.com/ShippingAPI.dll/execute?SelectPolygon=&f=json&env%3AoutSR=102100&in_Polygon=%7B%22fields%22%3A%5B%5D%2C%22geometryType%22%3A%22esriGeometryPolygon%22%2C%22features%22%3A%5B%7B%22geometry%22%3A%7B%22rings%22%3A%5B%5B%5B-9985470.667454347%2C4172722.553832795%5D%2C%5B-9982776.262207298%2C4172302.1501772273%5D%2C%5B-9984190.347230572%2C4170066.3670998886%5D%2C%5B-9985566.213739704%2C4170945.392925167%5D%2C%5B-9985470.667454347%2C4172722.553832795%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D%7D%5D%2C%22sr%22%3A%7B%22wkid%22%3A102100%7D%7D&Rte_Box=R&callback=dojo.io.script.jsonp_dojoIoScript2._jsonpCallback 
```

 the same error is thrown, which tells me the proxy is doing it's job by brokering the communication. The error is from the underlying resource.

**Comment by thewordsmith** [comment]
I went into proxy.php and added every instance of username & password but I get the same result.

**Comment by phpmaps** [comment]
@thewordsmith - I think the issue is ``` http://stg-production.shippingapis.com/ShippingAPI.dll/execute ``` is not an ArcGIS Service.  When the proxy project got kicked off it was created with ArcGIS Services in mind (especially when dealing with authentication).  If the config has a username and password - the is logic in the code to dynamically look up the ArcGIS for Server token endpoint and then it does the authentication.  I think for this proxy to work, your app (ShippingAPI.dll) would need to support some kind of token authentication.  I suspect it would not be hard for you to modify the proxy to fit your needs - but I think making your app support a token mechanism might be a bit more challenging.  Does this make sense?

**Comment by thewordsmith** [comment]
I added the following url to proxy.config:

      <serverUrl
          url="http://services.arcgisonline.com/ArcGIS/rest/services/"
          matchAll="false"/>

Now when I use FireFox go to the Sample API I get time out errors in the consol log (F12).

http://www.freshsoftware.net/usps/eddm/sample_api/?secret_key=MTI1ZjVyN3JBNTY2dDJlcjE1d2tyNTQ0dWprNDhraklXUzZuJXdrZGprSkg=

**Comment by phpmaps** [comment]
@thewordsmith I am not understanding.  Are you or are you not trying to setup a proxy to obtain information from ```http://www.freshsoftware.net/usps/eddm/sample_api/```?

**Comment by thewordsmith** [comment]
Yes, that is what I am attempting to do. I just found that there was a config syntax error in proxy.config. I corrected that am now I am getting the same authentication error. I have tried to add the username/password to proxy.config and directly in proxy.php but I still get the same error. Where am I supposed to but the username/pass. I have been a USPS Webtools developer for over 10 years so I am used to there XML way of doing things. Where does the username go so it gets sent to the USPS Server?

**Comment by phpmaps** [comment]
Thanks, got it.  Sulaiman when the PHP proxy was created, it was created so users could proxy ArcGIS Services and not other types of services.  If you read the readme we talk about why folks should use the proxy.  

For example, I cannot put ```https://accounts.google.com/ServiceLogin``` into the config.xml file along with my username and password and then log into google / gmail.  That does not work.  The security feature (if you could call it that) aka the part with the username and password, is only designed to work with ArcGIS services.  

That said what you can do is fork the proxy and customize it to work with your USPS Webtools service.  Hope this makes sense.

**Comment by thewordsmith** [comment]
The SAMPLE USPS/ERIS file is supposed to work with the USPS/Ersi Every Door Direct Mail SAMPLE API. You are supposed to be able to replace the WSPROXY.JSP file with PROXY.PHP by editing the assets/geoprocessing.js file.

It is not working because the is no way to set the username/password the same way that I can with the sample webtools.html that I have uploaded to the link bellow. Look at the XML syntax in each form.

<SelectNearRequest USERID="Blah"> 

http://www.freshsoftware.net/usps/eddm/sample_api/webtools.php?secret_key=MTI1ZjVyN3JBNTY2dDJlcjE1d2tyNTQ0dWprNDhraklXUzZuJXdrZGprSkg=
