### ISSUE TITLE
Port over proxy documentation from JavaScript API page

### ISSUE THREAD

**Issue by NoashX** [Esri/resource-proxy#298]
There is some good information and instructions in the "Using the proxy" documentation from the JavaScript API page https://developers.arcgis.com/javascript/jshelp/ags_proxy.html

Seems like it would be useful to incorporate this into the main README file here? A one-stop shop for proxy information would be more useful than distributed information on different pages.

Thoughts?

**Comment by jgravois** [comment]
i get where you're coming from, but it seems to me like it would be enough to link to it where it is.  that way we don't have to worry about keeping *two* pieces of documentation up to date.

**Comment by esoekianto** [comment]
@NoashX I think that information is more on how to incorporate the proxy page in js api, and it may be different in other APIs or product like WAB here (https://developers.arcgis.com/web-appbuilder/guide/use-proxy.htm)

I think those can stay in their respective API/product doc page, not here.

**Comment by jgravois** [comment]
@esoekianto.  check out the section in the link @NoashX provided called *'Test the proxy'*.  the steps it describes have nothing to do with the JSAPI and would be totally relevant here.

**Comment by NoashX** [comment]
Understood. I'll see your comments @jgravois @esoekianto, and raise you a list of links to our products that have their own proxy documentation. Would that be useful?

e.g.
JavaScript API
Web AppBuilder
AGOL
...

**Comment by esoekianto** [comment]
@jgravois I see. I think the "Test the proxy" part is like a 'story-telling' version of the instruction page here on how to set up or test the proxy in your web server. 

I feel like if it is important and related to how to set up or test the proxy they can be here, but it if it is related to on how to incorporate proxy to the specific product, its better to stay where its doc is, so that if any changes, we can let the team to update. 

That JS api doc page that @NoashX provided, provides both how to incorporate in js api application and how to set up/test the proxy.

**Comment by jgravois** [comment]
yeah, its really valuable troubleshooting doc that i don't think it needs to be rewritten here.  

@NoashX please take a stab at updating the readme in this repo to include links to both dependent project documentation and the existing troubleshooting documentation and we can review your PR.

**Comment by NoashX** [comment]
@jgravois will do, thank you and @esoekianto for the feedback

**Comment by NoashX** [comment]
https://github.com/Esri/resource-proxy/pull/299 :grey_question:

**Comment by jgravois** [comment]
ProTip :copyright:
your mention of `#298` in the initial PR commit message automatically added the reference above your last comment here.
if you had used a [keyword](https://help.github.com/articles/closing-issues-via-commit-messages/) like 'close', 'fixes', 'resolves' in that message, this issue would be closed automatically by the merge.

**Comment by NoashX** [comment]
good looking out, i'll give that a shot :ok_hand:
