### ISSUE TITLE
Support subdomain wildcards

### ISSUE THREAD

**Issue by gobsmack** [Esri/resource-proxy#30]
Is there any interest in supporting wildcards for referrer and server? For example:

    allowedReferers="http://*.myorganization.com"
Or, a better solution might be a regex match, for example:

    url="(https?:\/\/)?(\w+)(.myorganization.com)"

I'm dealing with over 50 subdomains accessing one application, so this way I could white-list them all. Maybe mine is an unusual case, and an unnecessary complication to the base proxy.

**Comment by cheetah90** [comment]
Fixed on all three proxies.
