### ISSUE TITLE
Login prompt appearing randomly

### ISSUE THREAD

**Issue by djg07** [Esri/resource-proxy#300]
Using .net, the login prompt has been appearing randomly. The issue is impossible to replicate consistently. It just happens when a user attempts to add a layer. 

My proxy config looks like the following: 

```
<ProxyConfig mustMatch="false" allowedReferers="*">
<serverUrls>
<serverUrl url="xxx/arcgis/" username="xxx" password="xxx" matchAll="true" ></serverUrl>
</serverUrls>
</ProxyConfig>
```

Not sure what more information would be helpful. 

Edit: Looking at the docs more, it may actually be an issue with rateLimit and rateLimitPeriod. Since I have many users using the same login and I hadn't overwritten the default ratelimit/period. 

I'll follow up if this does not resolve it.

**Comment by upcamogie** [comment]
I have a similar issue. the log in screen comes up somewhat randomly. It does seem to be limtied to the default rate period of 60 minutes. But in my log files, it seems to also grab the required tokens but then not apply them unless I refresh the browser. So I will load an app, get  login screen, cancel/ignore, refresh page and then app will load with my secure layers (secure on my server). Will work & then repeat this issue. I am working with a support analyst (this is the 2nd go around with this issue) but its been weeks & we are stumped. My setup has a unshared web map & secure map services, FYI.

**Comment by djg07** [comment]
@upcamogie 

I had to many problems with login based authentication I just gave up. It seems to be extremely buggy and inconsistent. I ended up going with token based authentication which has been working flawlessly. Let me know if you want further details.

**Comment by upcamogie** [comment]
@djg07 
Thanks- I do want further details. Is your token based for the web map or the services? are your services hosted locally? I have tried probably almost every combo so far, client id/secret, token, a million versions of URLs in my proxy.config. All just for wanting to share a map in an app without having to share all of maps/services- seems a straightforward workflow that should not cause so many inconsistencies! thanks again- post here or PM if thats an option (I am not very github savvy)

**Comment by djg07** [comment]
@upcamogie 

The token is for the map services. Services are hosted on an external server.  My proxy.config file looks like the following: 

```<ProxyConfig mustMatch="false" allowedReferers="*">
    <serverUrls>
              <serverUrl url="http://serverHere:6080/arcgis/" matchAll="true" accessToken="token here">   
        </serverUrl>
</ProxyConfig>
```

In order to get a token, you have to login to your arcgis server and make a user account with read only privileges. Once its greated, head over to your server's REST page and click on the "Get Token" link in the top right. Put in the username/password you just created. The referer is the machine in which the services will be accessed from. After getting this token, put it into your proxy.config as described above.

**Comment by upcamogie** [comment]
Thanks for the info-- I will definitely explore this approach since this is def something a bit different w/the special user account and whatnot. Quick curiosity- is this something you found on your own or did you enlist support help? From past experience in many issues, each person I talk to has a different solution and often contradictory which is why I continue my own tests as well as work w/support. thx again

**Comment by djg07** [comment]
@upcamogie 

I generally find the tech support to be hit or miss. Some agents are very knowledgeable and helpful, others are useless and just insist on closing the ticket. The original agent suggested using the username/password approach. Despite working, my application was still getting "login" popups every so often. 

I ended up figuring out this token based approach on my own. So far it has been working flawlessly.

**Comment by sanramanathan** [comment]
@djg07 @upcamogie 

Hi,

I too have a similar popup prompt problem.Here I am using .net proxy with  dynamic username and password .When i open my application i am getting identity pop up for first time but when i refresh twice    the browser popup disappears and map is visible and also when application is running if i refresh the browser pop up appears again.

when checked in debug mode. login prompt comes when proxy is sending   requestUri  for "arcgis/rest/info?f=json" 

any suggestions for this issues.

**Comment by upcamogie** [comment]
@sanramanathan what kind of application do you have? Your proxy rules may be ok but the proxy reference in your app may not be. I have had to structure my app's proxy rules depending on whether it was a story map or a web appbuilder app. I have not had to do this from scratch lately but can refer back to my app code if you think either of those app types may be similar enough. Also, the latest version of the story map journal template available on github has the proxy code built in which makes it a bit easier.

**Comment by sanramanathan** [comment]
I am using Asp.Net application with arcgis javascript api with proxy also included as part  my project code.
Services are from arcgis server 10.2.1 running in another pc (samplegis).
I have given proxy rules using the following code
 
require([
    "esri/urlUtils"
    ], function (urlUtils) {

        urlUtils.addProxyRule({
            urlPrefix: $("#URLGIS").val(),//"http://samplegis:6080" 
            proxyUrl: $("#URLProxy").val() //"/proxy.ashx";  {this is from website itself}
        });

    });  

my proxy config is

<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
             mustMatch="true" logFile="ProxyLog.txt">
  <serverUrls>

    <serverUrl url="http://samplegis:6080/arcgis" 
     matchAll="true" dynamicToken="true" />

  </serverUrls>
</ProxyConfig

**Comment by fellj** [comment]
I am also having a problem with the random login display. I have a secured service accessed through an ArcGIS server site hosted at my organization. Did anyone have any luck altering the rateLimit property? Also, if I used token based authentication do I need to recreate a token on a regular basis for the user?

**Comment by fellj** [comment]
Just wanting to bump this issue post again. We applied the fix @djg07 suggested but are still getting feedback from external users that the login prompt continues to display randomly. Has anyone else experienced this? What is going on? Has anyone found an additional fix?

**Comment by ccrozek** [comment]
@fellj are you still getting login prompts from using a token? did you figure out if you need to recreate it on a regular basis? I'm currently using the .net proxy on my web app builder applications with a username and password to access our secured services and the login prompt is making the apps look really bad

**Comment by fellj** [comment]
Hi @ccrozek.

My workaround is less than elegant but it works about 99% of the time. See my esri geonet forum post<https://community.esri.com/thread/179051>. Open to anything else others have done.

John W. Fell, GISP
GIS Administrator
214-631-0520, ext. 3329
