### ISSUE TITLE
Formalize release?

### ISSUE THREAD

**Issue by nateshaub** [Esri/resource-proxy#303]
Hi there, I simply wanted to suggest that you formalize a release from your 1.1 Beta as the 1.0 resource proxy does not work correctly with ArcGIS Server 10.3.1.  Thanks!  -Nate Shaub

**Comment by esoekianto** [comment]
@nateshaub we are working on formalize the 1.1.0 that should work with AGS 10.3.x , in the mean time feel free to use the daily build

**Comment by nateshaub** [comment]
Thanks sir!  I've already put the daily build in place successfully but would love to peg myself to a specific release.

**Comment by bsvensson** [comment]
This is a duplicate of #108 .
