### ISSUE TITLE
tokenServiceUri option missing in the DotNet version of the proxy

### ISSUE THREAD

**Issue by pstaikov** [Esri/resource-proxy#304]
I am trying to use the proxy with token based authentication. I have realized that before the proxy calls the generateToken URL, it calls the /arcgis/rest/info page to discover the generateToken URL. My problem is that the arcgis/rest/info page also requires authentication and since it precedes the token generation, that call returns 401 (Unauthorized) response. I do not understand the portal configuration options much, but I assume that it is setup with no public access and this is why it requires authentication for all URL. This seems reasonable to me. I was able to find a work-around for this issue when using the java version by specifying the tokenServiceUri. When I provide the generateToken URL with this parameter, the call to the /arcgis/rest/info page is skipped. The problem however is that this option is not available in the DotNet version of the proxy and this is the one that I want to use. This would help me avoid the complication of setting additional java application servers in a cluster environment, which is not completely trivial. I think it would be very nice if you added the tokenServiceUri  config parameter  to the DotNet version.

Thank you for your help!

**Comment by pstaikov** [comment]
I actually did some more investigation and found out that the tokenServiceUri was actually a red herring. It is still a difference between the DotNet and java versions and you can fix it if you feel it is a good idea, but my problem was due to something else. Both the /arcgis/rest/info and the /arcgis/tokens URL were protected by windows authentication. It turns out that the java proxy handles IWA by default and the DotNet proxy does not.

**Comment by bsvensson** [comment]
@pstaikov - tokenServiceUri  is implemented for all three proxies BUT missing from [the DotNet README.md](https://github.com/Esri/resource-proxy/blob/master/DotNet/README.md).  We will get that updated.

Could you explain in more details what you mean with IWA is not handled by default in the DotNet proxy?  It should be...  Are you using the 1.0 version or the latest daily build.

**Comment by pstaikov** [comment]
Bjorn,

Thanks for your response. I did try both version 1.0 and the latest on the master (it says it is version 1.1.0-beta). Regarding the tokenServiceUri,  I can see that there is a variable by that name in the DotNet version, but to the best of my ability, I cannot see it being read from the config file and used the same way as in the java version. 

Regarding the IWA, let me start by saying that there may be something strange with the way my portal is setup. Because why would it require windows authentication when you are trying to access the URL to use token authentication. But here are my observations. First, I saw that the java proxy was able to connect to the portal and the DotNet was not. When I started to debug, I figured that when they are trying to connect to the /arcgis/rest/info, the java proxy was sending an Authorization header in the request and the DotNet proxy was not.
Authorization:	NTLM TlRMTVNTUAADAAAAGAAYAJQAAACyAb..............
Then, after googling and searching for a while I added the following line in the DotNet proxy in the second doHTTPRequest method:
req.UseDefaultCredentials = true;
That fixed the issue. 

I hope this helps.

**Comment by pstaikov** [comment]
@bsvensson - Here is what I figured out. I was providing a username and password in the proxy config, but not domain. I do not believe that the domain attribute is documented in the readme file. So I think what happens is that when you specify the domain, that is a trigger for the proxy to use IWA. If a domain is not specified, then the proxy attempts getting a token. In my case this did not work since the token URL was protected with windows authentication. When I added the domain value, the proxy connected using IWA. I would suggest that you guys document this behavior, so that other people would not have to learn it the hard way like me :)

**Comment by bsvensson** [comment]
@pstaikov 

It's a bit hidden, but on https://github.com/Esri/resource-proxy/tree/master/DotNet (about to be moved to the main readme as part of #293) there is a bullet point for:
* **domain**: The Windows domain to use with username/password when using Windows Authentication.

Any suggestion how we can improve that info?

Also, so in the end, did you end up not needing `req.UseDefaultCredentials = true;`?

**Comment by afili** [comment]
@pstaikov you are right, this is how it works. domain should be in place in order for the proxy to use IWA. We have this line of code in the readme:

domain: The Windows domain to use with username/password when using Windows Authentication.

Do you think that it is not very explicit?

**Comment by afili** [comment]
@bsvensson you were faster than me!

**Comment by bsvensson** [comment]
21 seconds!

**Comment by pstaikov** [comment]
I suppose the line you have is enough. At least it will give the developer an idea that there is something else to try. I was looking at the 1.0 version and the latest on the master and did not know it existed. 

@bsvensson -- no, I did not have to use the req.UseDefaultCredentials = true; after all.

Thank you guys for your support!
