### ISSUE TITLE
document - must include oauth2endpoint in the serverurl when using OAUTH2 for WAB

### ISSUE THREAD

**Issue by esoekianto** [Esri/resource-proxy#307]
From my experience and other folks in support helping customers setting up proxy for WAB, when accessing the secure webmap, we need to include "oauth2endpoint" with value of "http://orgnamexxxx.maps.arcgis.com/sharing/oauth2", otherwise we will get error of no permission to access this resource

example of serverurl that NOT working,  

``<serverUrl url="http://ess.maps.arcgis.com" clientId="xxxx" clientSecret="xxxx" 
                   matchAll="true"/>``

resulting to this error from AGOL, 

``{"error":{"code":403,"messageCode":"GWM_0003","message":"You do not have permissions to access this resource or perform this operation.","details":[]}}``

example of serverurl that works 

``<serverUrl url="http://ess.maps.arcgis.com" clientId="xxxx" clientSecret="xxxx" oauth2Endpoint="https://ess.maps.arcgis.com/sharing/oauth2"
                   matchAll="true"/>``

I am not sure if we should document this in WAB doc or maybe we can help mention it in this page as example on when to use oauth2endpoint properties

**Comment by phpmaps** [comment]
It might be interesting to explore if they can use the built-in proxies in WAB (aka the ones built into ArcGIS Online Applications under the Authentication Tab).  Actually for Application type logins using clientID and clientSecret I would recommend always using the built-in Service Proxies.  Thoughts? 

![image](https://cloud.githubusercontent.com/assets/2159502/10594389/87d5bf4a-7681-11e5-9e46-a316a81761ad.png)

**Comment by esoekianto** [comment]
@phpmaps this is actually a really good idea if we can make it work using this built-in proxies in AGOL to access the secure webmap. It is only available for services, like routing, elevation, etc

**Comment by bsvensson** [comment]
@esoekianto - [the doc](https://github.com/Esri/resource-proxy/blob/master/README.md) was updated recently to say:

* **oauth2Endpoint**: When using OAuth 2.0 authentication specify the portal specific OAuth 2.0 authentication endpoint. The default value is https://www.arcgis.com/sharing/oauth2/.

Any suggestions for how to clarify that?

**Comment by esoekianto** [comment]
@bsvensson hmm, I think that is good already. It just that I feel that there is confusion since we don't need to specify the oauth2endpoint when accessing secure webmap in other js api template in AGOL. Maybe if we can add example after that sentence, when using this in Web AppBuilder application.

what do you think?

**Comment by phpmaps** [comment]
I like this idea.  @esoekianto it sounds like this is a very specific thing involving WAB and Web Maps.  Is that correct? If so I like @bsvensson 's idea.

**Comment by jgravois** [comment]
if there's a bug in WAB, why don't we just help them out when we can and adapt generic ArcGIS Online Organizational urls to infer an `oauth2Endpoint` that works automatically?

**Comment by bsvensson** [comment]
Sounds like this is already doc'd and there's nothing left to do on the resource-proxy side.
Closing.
