### ISSUE TITLE
HTTP Vs HTTPS Issue

### ISSUE THREAD

**Issue by akirti** [Esri/resource-proxy#311]
When my application is running under http and I m trying to get response from https ArcGIS service its giving me 500 Error. (DotNet Proxy)

**Comment by akirti** [comment]
How I can add SSL Validator there when this kind of Situation occur

**Comment by akirti** [comment]
I followed
http://stackoverflow.com/questions/18454292/system-net-certificatepolicy-to-servercertificatevalidationcallback-accept-all-c/18454416#18454416
http://www.briantist.com/errors/could-not-establish-trust-relationship-for-the-ssltls-secure-channel/

And under this Method
     private System.Net.WebResponse doHTTPRequest(...)
     ....
        if (credentials != null)
            req.Credentials = credentials;
        SSLValidator.OverrideValidation();
     ..

I added force accept of certificate it worked for me. Any better way of doing this?

**Comment by esoekianto** [comment]
This happens because the server, where the proxy is hosted, does not have the certificate to access the https ArcGIS Server. You can try this by browsing the to the https url in the web browser on the server, and you should see certificate error in the web browser.  

Are you in the position to add the certificate to the server?

**Comment by akirti** [comment]
No I cannot access Server.  but I used this code for above problem. Somtimes I get NullPointer Exception at   funcs.Push(System.Net.ServicePointManager.ServerCertificateValidationCallback);

          public static class SSLValidator
{
    private static System.Collections.Generic.Stack<System.Net.Security.RemoteCertificateValidationCallback> funcs = new System.Collections.Generic.Stack<System.Net.Security.RemoteCertificateValidationCallback>();

    public static bool OnValidateCertificate(object sender, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain,
                                                System.Net.Security.SslPolicyErrors sslPolicyErrors)
    {
        return true;
    }

    public static void OverrideValidation()
    {

        funcs.Push(System.Net.ServicePointManager.ServerCertificateValidationCallback);
        System.Net.ServicePointManager.ServerCertificateValidationCallback =
            OnValidateCertificate;
        System.Net.ServicePointManager.Expect100Continue = true;
        //if (ServicePointManager.ServerCertificateValidationCallback != null)
        //{
        //    funcs.Push(ServicePointManager.ServerCertificateValidationCallback);
        //    ServicePointManager.ServerCertificateValidationCallback =
        //        OnValidateCertificate;
        //    ServicePointManager.Expect100Continue = true;
        //}

    }

    public static void RestoreValidation()
    {
        if (funcs.Count > 0)
        {
            System.Net.ServicePointManager.ServerCertificateValidationCallback = funcs.Pop();
        }
    }
}

**Comment by bsvensson** [comment]
Closing this issue as it seems to have been answered by @esoekianto [on Oct 26, 2015](https://github.com/Esri/resource-proxy/issues/311#issuecomment-151198148).
