### ISSUE TITLE
ArcGIS Server 10.3.1 GET Token Requests

### ISSUE THREAD

**Issue by lccspatial** [Esri/resource-proxy#312]
I have configured ArcGIS Server to allow these for ArcGIS for Autocad integration.

Does the .NET proxy support GET Token Requests?

My config below:

<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
             mustMatch="true">
    <serverUrls>
		<serverUrl url="https://samtest.launceston.tas.gov.au"
                   matchAll="true"
				   username="ISC\SVC_Spatial_External"
				   password="password"
				   />
    </serverUrls>
</ProxyConfig>

**Comment by esoekianto** [comment]
@lccspatial the latest version of the .NET proxy is now making POST request to exchange the token with ArcGIS Server

**Comment by lccspatial** [comment]
Thanks,

The above configuration is is returning this in the log file.

w3wp.exe Information: 0 : 2015-11-04 10:06:06 https://samtest.launceston.tas.gov.au/arcgis/rest/services/Infrastructure/Assets/MapServer
w3wp.exe Information: 0 : 2015-11-04 10:06:06 Matching credentials found in configuration file. OAuth 2.0 mode: False
w3wp.exe Information: 0 : 2015-11-04 10:06:06  Querying security endpoint...
w3wp.exe Information: 0 : 2015-11-04 10:06:06  Service is secured by https://samtest.launceston.tas.gov.au/arcgis/tokens/: getting new token...
w3wp.exe Error: 0 : 2015-11-04 10:06:06  Token cannot be obtained: {"error":{"code":405,"message":"Method not supported","details":"Generate Token request should not contain username and password in the query string."}}

**Comment by esoekianto** [comment]
@lccspatial you probably need to update the proxy.ashx file to the latest one in daily build

**Comment by lccspatial** [comment]
Problem solved thank you. Should this be merged with the release version?

**Comment by esoekianto** [comment]
yes, we are working on finalizing the new release 1.1.0 which should include this fix, and support for AGS 10.3

**Comment by jgravois** [comment]
none of the 1.1.0 milestone tags are showstoppers.  i vote we push them to 1.2.0 and just tag the release.  its **way** overdue.

@bsvensson
