### ISSUE TITLE
proxy.jsp cannot generate tokens to access security service

### ISSUE THREAD

**Issue by guizgis** [Esri/resource-proxy#313]
The proxy files I used is the latest release(v1.0). ArcGIS Server is 10.3.1
The proxy files for dotnet works fine while for java cannot generat tokens when I specify the username and password in proxy.config. The error reported by javascript is "dojo.io.script error Error: Token Required(…)".

**Comment by jgravois** [comment]
we released version [1.1.0](https://github.com/Esri/resource-proxy/releases/tag/v1.1.0) tonight.  please update and let us know how you go.

**Comment by guizgis** [comment]
Many errors are reported when I updated.

![error1](https://cloud.githubusercontent.com/assets/12145470/11025389/5788fc58-86d5-11e5-846e-39418849b90f.png)

![error2](https://cloud.githubusercontent.com/assets/12145470/11025396/6f4e217e-86d5-11e5-9f62-535c7286af47.png)

**Comment by jgravois** [comment]
@esoekianto can you confirm whether or not you can reproduce these errors with our official 1.1 java proxy release?

**Comment by esoekianto** [comment]
@jgravois @guizgis I can reproduce the same compiled error with the 1.1.0 version of proxy.jsp.

This is the last stable version I know, https://github.com/Esri/resource-proxy/blob/bdf7dd94178a23f016c77db42883edb9520b1fe8/Java/proxy.jsp , @guizgis, can we try using this as the base test as I am hunting which commits broke the build? 

Thanks

**Comment by bsvensson** [comment]
@esoekianto @guizgis - what versions of java are you using?

**Comment by esoekianto** [comment]
@bsvensson I am using 1.7.0_45

**Comment by guizgis** [comment]
@bsvensson  I am using 1.8.0_65
@esoekianto  I have tested the proxy.jsp you provided. However, no matter what url I add in proxy.config, I get error code 403 every time.
{"error": {"code": 403,"details": ["Proxy has not been set up for this URL. Make sure there is a serverUrl in the configuration file that matches: http://sampleserver6.arcgisonline.com/ArcGIS/rest/services/?f=pjson"], "message": "Proxy has not been set up for this URL."}}

**Comment by esoekianto** [comment]
@guizgis thats weird, can you share your proxy configuration? if you have access to esri tech support, feel free to contact us

**Comment by guizgis** [comment]
@esoekianto  my configuration is very simple, I don't think that could be the point. I have contacted esri support, hope a test could help find the answer. Thank you for your help.

**Comment by guizgis** [comment]
@esoekianto I have changed to use the version in #315, which sovles the compilation error. However, it is ok to access sample servers hosted by arcgisonline while error occurs when accessing my local server with error message:"ERR_INVALID_CHUNKED_ENCODING". This errors also occur when using the 1.1beta version you provided last time to access both local servers and online servers that version greater then 10.0.
