### ISSUE TITLE
1.1.? planning

### ISSUE THREAD

**Issue by jgravois** [Esri/resource-proxy#316]
[SemVer](http://semver.org/) dictates that if a release only includes bug fixes we should only bump the patch (1.1.x).  feature additions warrant bumping the minor (1.2.0) and breaking changes require bumping the major (2.0.0).

for the time being i recommend:
- (A) we continue to merge distinct bug fixes or feature additions directly to `master` and consider maintaining an alternate long running branch in the event that we attempt a more substantial refactor or overhaul.
- (B) bump the files to list the version as `1.1.1dev` or 'beta' and start getting into the habit of tagging a release basically _every_ time we add a legitimate bug fix.

in order to assist with (B), my process recommendation is that we attempt to move whatever unit tests currently exist into the public repo so that both community contributors and more casual folks at Esri are able to QA individual PRs as they come in.  even if they aren't pretty (yet), they would be extremely valuable.

@Esri/oauth2-proxy all other ideas welcome.

**Comment by bsvensson** [comment]
* On (B): Let's continue to use `1.1.1` and `1.1.1-beta` style labels within the master branch. (As we are)

* (C) It would be nice to have an automatic way to "bump-version-into-beta", i.e. do the equivalent of https://github.com/Esri/resource-proxy/pull/318.  Maybe a little script? And the equivalent for going from beta to release.

* (D) For the testing of the three proxies (which most people wouldn't need to use and would add lots of files to the repo), is it cleaner to create a separate repo or should we add a folder in the current repo, e.g. "test-tools".

**Comment by jgravois** [comment]
okay, i've done more research and i'd like to amend one of my earlier suggestions.

> * (B) bump the files to list the version as `1.1.1beta`...

looking at a variety of core [npm](https://github.com/gulpjs/gulp/commit/84df40b0faabc2b61d576154fd1145e2146377ca) projects, it seems that they all find it sufficient to merge directly to `master` and leave the version number alone until they're ready to tag the next release (which they tend to do **often**).  because of this, i think we should [KISS](https://en.wikipedia.org/wiki/KISS_principle) and follow the same pattern.

> * (C)...

if we incorporate my suggestion above, it'll be a little less painful to keep version numbers up to date, but it could still be helpful if someone is interested in writing a script to bump version numbers across all the files automagically.

> * (D)...

while i don't yet see a way to incorporate true continuous integration testing (like we have in [esri-leaflet](https://travis-ci.org/Esri/esri-leaflet) and [koop](https://travis-ci.org/koopjs/koop)), i feel that its **crucial** that we include our own testing tools in a `test` or `spec` folder directly inside this repo.  this makes it significantly more plausible for both developers submitting PRs and folks here at Esri (other than @bsvensson) to review/merge/tag a new patch quickly.

i'm happy to help/guinea pig if you agree.

---
with regard to *automating* the actual version tagging/release.  we use @ngoldman's [gh-release](https://github.com/ngoldman/gh-release) in several projects and it works with aplomb.  integrating it here would be particularly easy since we've already done the hard part of getting our changelog up to snuff (and because gulp dependencies will already give us an excuse to maintain a `package.json` file).

i **am** happy to volunteer to get gh-release in place.

**Comment by phpmaps** [comment]
John – automated testing tools are key.  Having something kind of like the PHP proxy verification page would be good.  Via JS it would be great if we could check each type of request via the incomming proxy and then compare actual results with expected results – I think we just released  a JSAPI version that included a deffered collection which would be useful here.  Maybe if we want to get fancy add some speed tests too.  What are your thoughts?

**Comment by ngoldman** [comment]
Just saw I was mentioned and thought I'd chime in :grin:

You can get automated tests for free on each commit and pull request with Travis CI -- quite easy to get that part going. Typically it expects a repo to be for one language though. I see this project includes DotNet, Java, and PHP. You might want to consider breaking those out into separate repos. It looks like the folders for each language are already ready for that, and it would make versioning for each of them a bit cleaner. You could keep things as they are in this repo and in each folder replace the `README.md` text with something like:

```md
# Resource Proxy for DotNet

This project has moved to [Esri/resource-proxy-dotnet](http://github.com/Esri/resource-proxy-dotnet).
```

This would leave a trail of breadcrumbs for users, allow bug fixes for different languages to be released more quickly and easily, and allow for easier integration of standard open source automated testing.

**Comment by jgravois** [comment]
@ngoldman, it would obviously be ideal to have the testing entirely automated, but i'm not sure how we can confirm that the proxies are functioning correctly without issuing authentic web requests, in some cases after supplying private credentials (to test its ability to generate tokens).  because of this, up until now i hadn't even considered trying to use something like Travis.

if/when we get what @bsvensson has already written (i believe he used gulp + request and swapped in a testing proxy.config with sensitive info at runtime) in this repository it would be **super** helpful if you were willing to take a look and give us some guidance.

**Comment by ngoldman** [comment]
It shouldn't be too difficult to both run a test server with the proxy and fire web requests on travis. For tokens, you can set environmental variables that are encrypted like so: https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings. This is how I handled testing for geohub, koop-github, and koop-gist ([example](https://github.com/koopjs/geohub/blob/master/test/repo-test.js#L6)).

**Comment by bsvensson** [comment]
@ngoldman - When you say test server, what sort of server would it be?  We would need something that can serve out JSP etc...

**Comment by ngoldman** [comment]
I imagine each language would need a test server to replicate the expected conditions -- basically an example implementation of the proxy for that language.

**Comment by bsvensson** [comment]
> looking at a variety of core npm projects, it seems that they all find it sufficient to merge directly to master and leave the version number alone until they're ready to tag the next release (which they tend to do often). because of this, i think we should KISS and follow the same pattern.

I agree.  I've changed my mind since [my Dec 9, 2015](https://github.com/Esri/resource-proxy/issues/316#issuecomment-163468095) comment.  Let's move away from "intermittent beta" tagging. And start up updating the minor version for each bug/patch fix as per [semver](http://semver.org/).

I'll check in a change to bump the version to `1.1.2` and moving away from `x.y.z-beta` naming convention :)

@jgravois - would you still recommend [gh-release](https://github.com/ngoldman/gh-release)?  If so, feel free to go ahead with your earlier volunteer offer _"to get gh-release in place"_.

**Comment by jgravois** [comment]
we have a process in place for releasing with significantly fanfare and a new issue #440 to track incorporating our current test suite into version control.

breaking out the individual proxies into seperate repos and automating CI would still be sweet, but case _closed_ based on what we've got as far as i'm concerned :hammer:
