### ISSUE TITLE
secured printing service to print a securing map service failed with https

### ISSUE THREAD

**Issue by tomwebgis** [Esri/resource-proxy#321]
Hi,

Our web application has secured map services and a secured printing service. It works fine before to apply https. After using https, map services are displaying fine, but the print function is not working with secured map services.  There is any thing missing?

Thanks,

Tom

**Comment by jgravois** [comment]
what happens when you test your own print service directly at the [REST endpoint](https://sampleserver6.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/execute)?

anything that works there should work via the proxy as well as long as the allowed urls use the appropriate protocol.

**Comment by dbened-denver-water** [comment]
I am having the same issue. I posted a comment on the WebMapToJson issue. It looks to me like the token is not embedded as part of the webMapJson request for all the layer urls that are secure. Please advise as to suggested fix. Thanks

**Comment by jgravois** [comment]
have you already read through the help article below @dbened-denver-water?

[Print maps that contain secured services](http://enterprise.arcgis.com/en/server/latest/create-web-apps/windows/printing-maps-that-contain-secured-services.htm)

**Comment by dbened-denver-water** [comment]
No I must have missed this. Thank you @jgravois , I will look over the document and include what I need  for publishing the print service with secure map services.

Thanks for getting back to me so soon.

**Comment by bsvensson** [comment]
Closing old issue.

See also comment in https://github.com/Esri/resource-proxy/issues/480#issuecomment-386396029 about options for printing secure services.
