### ISSUE TITLE
Referer Header

### ISSUE THREAD

**Issue by MrPaulg** [Esri/resource-proxy#322]
Hi 
I'm using the latest Proxy.jsp and having the following error

{"error": {"code": 403,"details": ["Current proxy configuration settings do not allow requests which do not include a referer header."], "message": "403 - Forbidden: Access is denied."}} 

This error is being thrown on the popup event in a flex viewer, issues also exist for identify on secure services.

Any help is appreciated

**Comment by esoekianto** [comment]
@MrPaulg this is because the request has null referrer value in the header (normally when testing from the web browser), and you are specifying allowedReferer properties in proxy.config. 

https://github.com/Esri/resource-proxy/blob/master/Java/proxy.jsp#L1041 

Can you check if the request from flex viewer has null referrer value in the header?

**Comment by MrPaulg** [comment]
Hi Erwin, thanks for responding ..... my error was misleading, I've switched to IE11 to test and debug in developer tools ...  The issue I'm having for my POPUP and IDENTIFY is that the response body is truncated. I'm attaching examples of a working response and an error response 

[sucess.txt](https://github.com/Esri/resource-proxy/files/38078/sucess.txt)
[truncated.txt](https://github.com/Esri/resource-proxy/files/38077/truncated.txt)


My site is here @ http://spatial.dcenr.gov.ie/GeologicalSurvey/GroundwaterX/

and the offending layers are Topsoil and Subsoils  if you wan to see the issue live. There should be a popup on both of these layers but the fail because the response is truncated, the identify will work on small polys and return nothing on large polys again the response body gets truncated.

Any ideas , please.
