### ISSUE TITLE
Using resource proxy with web adaptor under windows auth

### ISSUE THREAD

**Issue by dmorosi** [Esri/resource-proxy#325]
Hi all,

I'm trying to use resource-proxy within an architecture based on Portal adn Web Adaptor. The WA and the Portal authenticate users both through Windows Authentication (domain users).
I would like to let users acces a service published on a federated ArcGIS Server on the Portal without having to impersonate a domain user. This in my proxy.config:

<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
 mustMatch="true" logFile="c:\log\proxylog.txt">
 <serverUrls>
 <serverUrl url="https://[portal]/[federated_ags]arcgis/rest/services/XXX/YYY/FeatureServer/11002/"
 matchAll="false"
 username="user"
 password="pass"
 domain="domain"
 tokenServiceUri="https://[portal]/arcgis/sharing/generateToken" />
 </serverUrls>
</ProxyConfig>

When I try to access the url indicated, I get the following in the logfile:

2015-12-02 15:38:13 The remote server returned an error: (401) Unauthorized. https://[portal]/[federated_ags]/rest/services/XXX/YYY/FeatureServer/11002

I think the proxy is not authenticating me on the web adaptor... Am I right? Is it possible to do so?

Thanks

**Comment by esoekianto** [comment]
@dmorosi sorry for the delay, yes it looks like we are getting 401 back from WA in IIS. This workflow should work, do you know if you are using special configuration of WA setting?

and also, why would need to have tokenServiceUri when using WA?

**Comment by GISSupport** [comment]
You need (I think) the token service as a Federated Server needs IWA off and has server authentication mode set to ARCGIS_PORTAL_TOKEN.

From http://server.arcgis.com/en/portal/latest/administer/windows/federate-an-arcgis-server-site-with-your-portal.htm

If the server you want to federate uses web-tier authentication, you'll need to disable web-tier authentication (basic or digest) and enable anonymous access on the ArcGIS Web Adaptor configured with your site before federating it with the portal. Although it may sound counterintuitive, this is necessary so your site is free to federate with the portal and read the portal's users and roles.
