### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel 

### ISSUE THREAD

**Issue by anjithalk** [Esri/resource-proxy#330]
I am trying to use this proxy on SSL3 protocol blocked environment. How to tell this proxy to use TLS protocol as default ? 

I get this error message error: {code: InternalServerError,message:"The request was aborted: Could not create SSL/TLS secure channel." 

Can someone guide me please.

**Comment by markdeaton** [comment]
I encountered this as well. I had to modify proxy.ashx to include this call:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

As outlined in this StackOverflow discussion:
http://stackoverflow.com/questions/10822509/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

**Comment by DrewQuartic** [comment]
Had the same problem but in reverse. I have a server with an older security cert. I had to change SecurityProtocolType.Tls12; back to SecurityProtocolType.Ssl3. Luckily it's not in production.

**Comment by bsvensson** [comment]
PR #349 was merged in a few weeks ago to fix this.  Closing.

**Comment by quirimmo** [comment]
Upgrading Git to the latest version fixed the issue to me
