### ISSUE TITLE
Multiple serverUrls for token/server based services in the same proxy.config?

### ISSUE THREAD

**Issue by upcamogie** [Esri/resource-proxy#331]
edited - I am using the DotNet proxy--
I have 2 sets of server-side credentials I want to use for different apps. Ideally one proxy.config would have everything I need. However, my apps seem to only work when the serverUrl for that service is listed first in the proxy.config so it seems to ignore the 2nd rule for my http://myserver.org/rest/services.  Currently I have 2 proxies with the same rules-- the order is just reversed. the apps using those proxies only work if the web maps used have the content that is tied to the first ServerUrl rule listed in the proxy.config file. Both ServerUrls are at the root level since I want to be able to use those creds in different folders. Both are set to matchAll="true" since that is the only way my proxy works anyway (despite my read of the documentation that seems to indicate otherwise to my novice brain).

I did not see anything in the help/documentation noting this limitation. I have multiple proxy ServerUrl rules for other things, such as the Oauth for use with www.arcgis.com as well as with myorg.maps.arcgis.com (apparently it makes a difference per app template). I have enough issues with proxies alredy so knowing what is/not possible would really help. thanks

**Comment by esoekianto** [comment]
@upcamogie so you have two sets of credentials for the same serverUrl in the proxy.config? The proxy would use the first serverUrl listed in the case of duplicates in the serverUrls list

**Comment by upcamogie** [comment]
Thanks @esoekianto-- yes, that is correct and your explanation makes sense for what I am seeing. Would I be able to have these 2 users if I added a folder name after /services? I think I tried that and it still did not work. Should I deploy multiple proxies based on user? I can do that but wasn't sure of my options.

**Comment by bsvensson** [comment]
In theory, adding the folder name should work.  If not, I'd consider that a bug.
Currently, I think this behavior differ between the three proxies. It might work for some of them, but not all three...

**Comment by esoekianto** [comment]
@upcamogie if the serverUrls for both users are identical, then yes, you would need to have multiple proxies. (although this is a good enhancement where you can have different user depending on the referrer value)

yes, adding folder name should work. it will go like this, 
```
<serverUrls>
        <serverUrl url="https://server/arcgis/folderforuser1/" username="user1" password="password1" matchAll="true"/>
        <serverUrl url="https://server/arcgis/folderforuser2/" username="user2" password="password2" matchAll="true"/>              
    </serverUrls>
```

another trick, if you can have the folder prefix that specific per user, you have have multiple folders for each user

**Comment by upcamogie** [comment]
Thank you both @esoekianto  and @bsvensson for your ideas. The folder thing does not work for me-- still no dice with how I need to have it currently.  I will have to use different proxies since my one user has access to services in many folders (hence the root level ServerUrl) and the other user I have more flexibility limiting to a folder. Overall though I would like my proxy to be generic enough to satisfy most situations so I would like to keep my main credentials tied to the root . I may be able to organize some of server users/roles better too now that I am actually using them for something.

I agree that enabling more than one user to access the same ServerUrl is a good enhancement-- hopefully that kind of thing will go somewhere along with more standardization on how to apply proxy rules across products. thanks again

**Comment by esoekianto** [comment]
@upcamogie the last time I tried it, the folder workflow worked, I will try it again in little bit.

can you try changing the order just little bit, try to have the server url with folder first in order with the first user, then the server url for root folder with main user after?

essentially the proxy is going thru the serverurl in the order, and compare the request uri string with serverurl listed in proxy.config

**Comment by upcamogie** [comment]
That seems to have done the trick, @esoekianto, thanks. I am now able to use the one proxy with all 3 apps which use a proxy-- one for my user via 'services/folder' and the other at the root /services. I had not reordered with the folder designation and that seems to be the key, as you describe above. thank you for your assistance.

**Comment by esoekianto** [comment]
@upcamogie im glad it worked out for you
