### ISSUE TITLE
POST to geometry service for 'PROJECT' is returning HTML instead of JSON

### ISSUE THREAD

**Issue by jtawee** [Esri/resource-proxy#332]
I am using the ArcGIS JS API, using the Geometry Service object to project points.  All is well until I have geometries with data that is large.  This causes the request to use a POST instead of GET, which causes the request to go through this proxy here.  This proxy is supposed to be able to handle this request, sending the request to the geometry service (in this case http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer ), and sending the JSON data back.  Unfortunately, it seems to ignore the 'f=json' param that I am sending as a post param (the ArcGIS JS API takes care of the params, wrapping it in a 'ProjectParams' object), and it is returning the HTML that makes of the Geometry Service Project page.  I've tried version 1.0 and 1.1 of this proxy, same issue.  I am going to use a different proxy, just thought you guys would want to know.

**Comment by bsvensson** [comment]
Hi @jtawee - thanks for reporting this.  Could you explain a little more for us to be able to replicate the issue?  Also, which proxy did you use DotNet, java or php?

If you are using the ArcGIS JavaScript API, e.g. with https://developers.arcgis.com/javascript/jsapi/geometryservice-amd.html#project, you shouldn't have to specify f=json. The API takes care of this.  I'm not sure what you mean when you say "sending as a post param". Could you share more information?

**Comment by jtawee** [comment]
Hello:

I'm using the java proxy.

Yes, I am using

https://developers.arcgis.com/javascript/jsapi/geometryservice-amd.html#project
from the ArcGIS JS API.

One of the params that gets passed to this function is the
'ProjectParameter" object.  That's where I set the 'geometries' and 'outSR'.

I do not specify the 'f=json', the api does take care of it (that's what I
mean by saying 'sending as post param' - it is sent automatically with the
POST param...I can see it in the firebug console.

The problem is that the response seems to return HTML.



TO give more details, I did do some debugging on my own.

The 'readRequestPostBody' method in the Proxy.jsp does return an
EOFException.  I updated the code to catch the exception, still returning
the bytes.  This allowed the code to continue on and eventually return a
response, however the response is HTML.  So maybe there is an issue here?



Here is an example of the post params I'm sending (the api takes care of
this):

[image: Inline image 1]


here is my URL:

http://localhost:8080/.../proxy.jsp?http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer/project




FYI - not sure if this helps in any way, but When my 'geometries' data is
shorter, I perform a GET request, without going through the proxy, and
everything is fine



Thanks

**Comment by jtawee** [comment]
Just to add to this issue.  I don't think POST to this proxy works for any service.  I just realize that my routing widget fails when it switches over to use POST.  (if I route a path with 3 location, it sends a GET request to this proxy, but when I add a 4th location, the widget sends a POST to this proxy instead, causing an error. )  Looking at the response, I see the same issue as above, i am getting HTML response back of the service page
