### ISSUE TITLE
Proxy Issue when using IE 11 browser via GET method

### ISSUE THREAD

**Issue by daranasela** [Esri/resource-proxy#336]
Hi

I'm currently using ArcGIS Javascript API and Proxy.jsp. Everything works fine with Chrome and Firefox  browser. But it fails when the ArcGIS API forward GET method url as below:

http://localhost:7777/proxy/jsp/proxy.jsp?http://xx.xxx.xx.xx/ArcGIS/rest/services/LayerMgmtSpecific/FeatureServer/8?f=json

The IE browser consider the above url as an invalid url.

Does anyone experience this before ? What would be the work around ?

Thank you

**Comment by bsvensson** [comment]
Does other things work with localhost:7777, e.g. http://localhost:7777/proxy/jsp/proxy.jsp?ping and/or some non-proxy URL on that domain port combo?

Try using `http://<name of the computer>` instead of `http://localhost`.

**Comment by daranasela** [comment]
The ping (http://localhost:7777/proxy/jsp/proxy.jsp?ping) works as normal.
The issue is only with IE as IE consider the last parameter ?f=json as invalid url.
I works when I paste the url in IE browser and I remove the last param ?f=json as below:
http://localhost:7777/proxy/jsp/proxy.jsp?http://xx.xxx.xx.xx/ArcGIS/rest/services/LayerMgmtSpecific/FeatureServer/8
