### ISSUE TITLE
"tokenServiceUri" attribute is not working in Dot.Net proxy

### ISSUE THREAD

**Issue by girishyadav20** [Esri/resource-proxy#337]
The Proxy configuration settings has one parameter to set token service url.

"tokenServiceUri: If username and password are specified, the proxy will use the supplied token service uri to request a token. If this value is left blank, the proxy will request a token URL from the ArcGIS server."

But proxy does not respect it. When I checked proxy.ashx, found that this XMLAttribute is not read from proxy.config. 

Is this feature not yet implemented?

Thanks,
Girish

**Comment by bsvensson** [comment]
It's implemented in all three proxies.  [For ashx](https://github.com/Esri/resource-proxy/blob/master/DotNet/proxy.ashx#L533-L544):
```

                    String tokenServiceUri = getJsonValue(infoResponse, "tokenServicesUrl");
                    if (string.IsNullOrEmpty(tokenServiceUri)) {
                        string owningSystemUrl = getJsonValue(infoResponse, "owningSystemUrl");
                        if (!string.IsNullOrEmpty(owningSystemUrl)) {
                            tokenServiceUri = owningSystemUrl + "/sharing/generateToken";
                        }
                    }
                    if (tokenServiceUri != "") {
                        log(TraceLevel.Info," Service is secured by " + tokenServiceUri + ": getting new token...");
                        string uri = tokenServiceUri + "?f=json&request=getToken&referer=" + PROXY_REFERER + "&expiration=60&username=" + su.Username + "&password=" + su.Password;
                        string tokenResponse = webResponseToString(doHTTPRequest(uri, "POST"));
                        token = extractToken(tokenResponse, "token");
                    }
```

Are you maybe not using the latest version?

**Comment by esoekianto** [comment]
@girishyadav20 I am looking thru this issue, the problem with the server you are working on is, 

the rest/info is giving the token url with https but when you try to go to the token url with url is not accessible. 

I would suggest changing the token url setting of the ags server to point to http or enable https

**Comment by girishyadav20** [comment]
@bsvensson I am using a latest version of proxy and currently proxy is getting tokenServiceUri from server info. But as mentioned in the proxy settings document we can specify "tokenServiceUri" through proxy.config as well. Is that true? 

@esoekianto Yes, I also observed the same and notified client to make required changes. Thanks for your help.
