### ISSUE TITLE
Renewing token  result at "Invalid Token".

### ISSUE THREAD

**Issue by sebaspelletier** [Esri/resource-proxy#338]
This Issue: https://github.com/Esri/resource-proxy/issues/185#issuecomment-181690511
is not closed. I still have this type of issue and am using the latest dotnet proxy. I use ClientId and ClientSecret on ArcGIS Online. When the proxy make "renewing token" the result is always "Invalid Token". At the next proxy call the respond il always OK.

My workaround is not the best but he work. In ProcessRequest add this 

![patch1](https://cloud.githubusercontent.com/assets/17067567/12917807/9f12cf5a-cf09-11e5-9776-930da7fd1f4a.PNG)

![patch2](https://cloud.githubusercontent.com/assets/17067567/12917992/9e951910-cf0a-11e5-9951-11aeefd34de4.PNG)

**Comment by jamiew0519** [comment]
Hi!  I'm struggling with this same issue.  Do you mind posting the full content of your proxy.ashx?  Thanks!

-Jamie

**Comment by sebaspelletier** [comment]
Here is my file hoping this helps you ... we work in french but you should understand.
[proxy.ashx.txt](https://github.com/Esri/resource-proxy/files/138010/proxy.ashx.txt)

**Comment by aaronkilbey** [comment]
I was getting the same periodic behavior of 498 being returned to the client by the proxy prompting the IdentityManager popup after the token validity period had expired.  This code seems to have helped remedy the issue.  I think the proxy could store the expire date as well and use it to not have to receive a 498 first before going back to get a new token.  In the process of engaging ESRI support about this...

**Comment by esoekianto** [comment]
@aaronkilbey I don't see any case open by you, let me know if you want me to create a case for you in Esri support so that we can take a look at this issue

**Comment by aaronkilbey** [comment]
Sorry, my coworker needed to get the ball rolling with the ELA support so he just put it in there.  Case # is 01770095.

**Comment by esoekianto** [comment]
@aaronkilbey thanks

**Comment by ssudhan** [comment]
Is there an update on this? Still seems to happen with latest dot net proxy and ArcGIS Server 10.4.

**Comment by aaronkilbey** [comment]
Answer from ESRI support was to set IIS App Pool refresh time to 55min, i.e. less than the 60 minutes the proxy requests for a token validity period.  It's an acceptable workaround, but ideally the proxy would keep track of whether or not a stored token is valid.

**Comment by ssudhan** [comment]
Thanks, that's useful.

**Comment by raghav99** [comment]
We are encountering this issue as well. 
We are consuming some 3rd party services (secured services hosted by Arcgis server) in our web mapping application. After the web app loads, if we leave it alone and dont refresh for 60 minutes, the token expires and the 3rd party service would throw the pop up window asking for credentials on the next ajax request. At this moment, reloading the web page will force the proxy to create a fresh token (and the pop up window will go away) and everything works fine but this is not an acceptable workaround for obvious reasons. Until a fix is shipped, we are going with the "55 min app pool refresh time" approach but it would be great to avoid that as we our product is installed at several of our client sites.

@bsvensson - Would it be possible to provide a ballpark estimated time of completion for a fix? Thanks.

**Comment by nsulzberger** [comment]
Thanks for your help @sebaspelletier ! I was using your validate method and extended it with Content type.Contains("javascript"):
 
// Text response
                if (serverResponse.ContentType.Contains("text") ||
                    serverResponse.ContentType.Contains("json") ||
                    serverResponse.ContentType.Contains("xml")||
					serverResponse.ContentType.Contains("javascript"))
                {
and now it works pretty well :)
