### ISSUE TITLE
Problem in installing proxy

### ISSUE THREAD

**Issue by adityakumar529** [Esri/resource-proxy#342]
(“https://github.com/Esri/resource-proxy”   link to download the proxy).
Once we setup up the proxy and pass the first url 
http://localhostDotNet/proxy.ashx?ping for test we get the following message which shows the configuration is ok.

In the second step we need to pass the url through the proxy so we pass the following url 

This error message shows the proxy has not been setup properly because of where the url is not able to pass through the proxy file.

**Comment by bsvensson** [comment]
@adityakumar529 - it seems like some of your text description is missing - like the example URL and the actual error message.

**Comment by adityakumar529** [comment]
@bsvensson 
When I check if the proxy has been installed.
![image](https://cloud.githubusercontent.com/assets/17431182/13277497/584b1dce-daef-11e5-882a-2d0eb7224016.png)

When I try to pass a url through the proxy as mentioned in the readme file of the proxy.
![image](https://cloud.githubusercontent.com/assets/17431182/13277525/9322b1f0-daef-11e5-891d-cb0fbbc260fd.png)


This shows I am not able to pass the url through the proxy.

**Comment by esoekianto** [comment]
@adityakumar529 

That error normally means that the web server where proxy is hosted can not access the URL that is being proxied. 

In my experience, this web server has no outside/external/internet access.

**Comment by adityakumar529** [comment]
@esoekianto But when I am accessing the same url without proxy I am able to see the data.
![image](https://cloud.githubusercontent.com/assets/17431182/13293562/1d5bc734-db46-11e5-90e0-d368ca94703d.png)

**Comment by esoekianto** [comment]
@adityakumar529 hmm, another test is by creating simple aspx code (c# or VB.NET) that make http request to the same URL from server side, and host it in the same server. 

this is what the proxy page is failed doing in that server literally.

**Comment by adityakumar529** [comment]
@esoekianto I am sorry I have not done the test with aspx code. But considering it to be the issue what solution do you suggest.

**Comment by michaelschnack** [comment]
Having the same issue.  Latest version of the proxy on IIS 7.
http://myserver/proxy/proxy.ashx?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson  returns a 500, but I can connect to the URL directly from myserver or from the client.
http://myserver/proxy/proxy.ashx?ping returns:
{ "Proxy Version": "1.1.0", "Configuration File": "OK", "Log File": "Not Exist/Readable"}

**Comment by esoekianto** [comment]
@adityakumar529 if thats case then you would need to make changes to the server setting to allow connection to outside world

**Comment by adityakumar529** [comment]
@esoekianto :+1: 
Do you mean the server where I am putting my proxy? If yes then my server does have access to outside world.

**Comment by adityakumar529** [comment]
@esoekianto : We made one aspx page and tried to redirect it to http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson and its working fine.
Thanks

**Comment by benbtx** [comment]
<ProxyConfig allowedReferers="*"
             logFile="proxy_log.log"    
             mustMatch="true">

**Comment by slead** [comment]
I have the same issue as michaelschnack:

http://localhost/proxy/proxy.ashx?ping returns `{ "Proxy Version": "1.1.1-beta", "Configuration File": "OK", "Log File": "Not Exist/Readable"}`

Web.config lists the log file path as C:\Temp\Shared\proxy_logs\auth_proxy.log, and I have created the empty directory at C:\Temp\Shared\proxy_logs, but no log file is created here.

 http://localhost/proxy/proxy.ashx?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson returns `{"error": {"code": 500,"message":"Unable to connect to the remote server http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson"}}`

@esoekianto you wrote _"you would need to make changes to the server setting to allow connection to outside world_" - can you please clarify how to do this? Is it in the IIS manager? Thanks for any advice.

![iis](https://cloud.githubusercontent.com/assets/133596/20731197/6d1145ec-b6dd-11e6-8675-313463bd2ec7.PNG)

**Comment by esoekianto** [comment]
@slead 

it would not be in IIS manager, this is normally the firewall rule of that web server or the organization network.  since most likely, the cause of that error is because the web server where the proxy is hosted, is unable to connect to remote URL, in this case http://services.arcgisonline.com

you can test this by trying to open the remote url in the web browser of the web server (where the proxy is hosted), and you should not be able to open the url (http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson )

let me know if this makes sense

**Comment by brysageek** [comment]
I am having similar issue
`{
error: {
code: 500,
message: "Unable to connect to the remote server http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson"
}
}`

I did see that in the proxy,ashx that security protocol type Ttl12 was coming back as not being a type, I went ahead and switched this to Ssl3 -- still nothing
I've checked apppoolidentity.  Scratching my head on this one

**Comment by Eserim** [comment]
Similar issues here - I am "testing" the site in Visual Studio, so it uses localhost:12345 (a port number at random)

Trying to get a test request ends in "Invalid URI: The URI scheme is not valid." line 562 - I really can't get my head around the structure of the config file, it seems counter Intuitive with the must match part.
