### ISSUE TITLE
Running Web AppBuilder (WAB) thru Proxy

### ISSUE THREAD

**Issue by bobjr12345** [Esri/resource-proxy#343]
I am trying to access a WAB app exclusively thru the proxy.  It seems that this should be doable but I keep running into road blocks like the map not loading.  I can get the logo to spin but does not load the 2nd step and access the secured map.

If i access the WAB project by going to its html page then it opens the secured map without any issues.  So obviously the WAB config.json is configured and pointing to the proxy as well.

To access the the WAB project i am trying https://www.mysite.com/Weather/proxy.aspx?https://www.mysite2.com/Weather/index.html  

Anybody else have any luck trying to secure and publish the whole app thru the proxy?  

Thanks!
bobby

**Comment by esoekianto** [comment]
@bobjr12345 

I have never seen a scenario where you run the whole web application (web app builder application in this case) thru the proxy, http://example/com/proxy.ashx?http://theapplication.com/index.html

And this resource proxy was not build to be used like this, it is meant for specific request to secured ArcGIS Server service or premium service in ArcGIS Online (routing service, elevation, etc)

let me know if we understand your situation correctly

**Comment by bobjr12345** [comment]
@esoekianto 
Thanks for the quick response.  The application will be hosting secured resources.  I need to share the resources with a larger group of people without them signing in, and I need to use a 3rd party authentication to control access which is why I was hoping to push everything thru the proxy so I can restrict access by ip-address.  Im guessing its not quite possible at this time the way I am looking at doing it.

**Comment by esoekianto** [comment]
@bobjr12345 
it is very interesting, but unfortunately the resource-proxy can only support the authentication to ArcGIS Server and ArcGIS Online at this point
