### ISSUE TITLE
PHP: proxy-verification page blank if CURL extension not installed

### ISSUE THREAD

**Issue by gavinr** [Esri/resource-proxy#346]
If you don't have the cURL PHP extension installed, the `proxy-verification.php` page is blank. I know cURL is listed as a requirement [here](https://github.com/Esri/resource-proxy/tree/master/PHP#requirements), but it would be nice for the `proxy-verification.php` page to tell you if you're missing a dependency.

PHP Version tested in: 5.5.9

**Comment by bsvensson** [comment]
The verification page is supposed to check for cUrl.  See https://github.com/Esri/resource-proxy/blob/master/PHP/proxy-verification.php#L189-L191.  @gavinr - Is this not working in your case?

**Comment by gavinr** [comment]
It did not. It just gave me a blank page. I've only run though this once - haven't had a change to replicate it, but here are the steps:

OS: Ubuntu 14.04.3 LTS

1. Apache is already installed
2. `sudo apt get update`
3. `sudo apt-get install php5 libapache2-mod-php5 php5-mcrypt`
4. `sudo service apache2 restart`

** at this point when i hit `proxy-verification.php`  the page was just blank. Once I did `sudo apt-get install php5-curl` the proxy verification page started working.
