### ISSUE TITLE
bugs on .net proxy

### ISSUE THREAD

**Issue by huawan** [Esri/resource-proxy#347]
I am using proxy page to consuming secured arcgis map service: (arcgis tier, built-in ags user and role), two bugs I found so far:

1) token expiration time is hard-coded in the code :
log(TraceLevel.Info," Service is secured by " + tokenServiceUri + ": getting new token...");
string uri = tokenServiceUri + "?f=json&request=getToken&referer=" + PROXY_REFERER + "&expiration=60&username=" + su.Username + "&password=" + su.Password;
string tokenResponse = webResponseToString(doHTTPRequest(uri, "POST"));
token = extractToken(tokenResponse, "token");

if set shortLivedTokenValidity=3 mins in arcgis server, error was occurred.

2) if token is expired, new token is appended as second token tag in url, old token is still in url, therefore still use old token to request the service and got "required token" issue. solved with replace new token with the old.

**Comment by sanramanathan** [comment]
@huawan  Yes, i too had that issue old token is still in url and new token append to it.Resolved by removing the old expired token before creating the new token

**Comment by darkbluemsu** [comment]
Can you guys kindly let me know which  line of code that you need to remove the old token? I might have similar problem. Thanks.
