### ISSUE TITLE
Identity pop up with ags proxy issue

### ISSUE THREAD

**Issue by sanramanathan** [Esri/resource-proxy#350]
Hi,i am using ags proxy along with my .Net application and for Arcgis server SQL DB as custom identity store. When i run the application i am getting identity pop up even though i pass username and password dynamically in proxy code.After getting this identity popup if i refresh the browser twice i am able to see map service again.

can you guide me on what configuration i am missing here..

**Comment by esoekianto** [comment]
@sanramanathan can you show us how do you pass the username and password dynamically in proxy code? Are you using customized version of the proxy page to achieve this?

if you have tech support, feel free to call us, we may be able to help you faster.

**Comment by sanramanathan** [comment]
@esoekianto i have download latest proxy(resource-proxy-1.1.0). i didn't customized much just in the following method i passed username and password from ASp.net Session

  private string getNewTokenIfCredentialsAreSpecified(ServerUrl su, string reqUrl)
        {
....
 //standalone ArcGIS Server/ArcGIS Online token-based authentication

 if (tokenServiceUri != "")
                        {
                            log(TraceLevel.Info, " Service is secured by " + tokenServiceUri + ": getting new token...");

                            //string uri = tokenServiceUri + "?f=json&request=getToken&referer=" + PROXY_REFERER + "&expiration=60&username=" + su.Username + "&password=" + su.Password; // orginal

                         // Code to get the token dynamically 
                            string uri = tokenServiceUri + "?f=json&request=getToken&referer=" + PROXY_REFERER + "&expiration=5&username=" + username + "&password=" + pwd; //modified -santhosh
                            string tokenResponse = webResponseToString(doHTTPRequest(uri, "POST"));
                            token = extractToken(tokenResponse, "token");
                        }
.....
}

**Comment by sanramanathan** [comment]
Hi,
I have found that reason for identity pop up is when i refresh the page after token expiration time the api is sending request for "arcgis/rest/info?f=json" via ags proxy so identity popup is coming.when i refresh back again. request for map services goes and map is displayed.I dont know why rest info request is coming in between.

any suggestions to stop this in proxy.

**Comment by esoekianto** [comment]
@sanramanathan how about routing that request "arcgis/rest/info?f=json" thru the proxy as well?

**Comment by sanramanathan** [comment]
@esoekianto  yes i am routing that through proxy. what happening here is proxy code is taking "arcgis/rest/info?f=json"  url as request uri and generates token(which is not required) .Then  attaches the token to this url and forwardToServer .So server response is arcgis server info json. After this stage i am confused,Dont know how my arcgis javascript application opens up the identity pop up (with map service link mentioned in dialogue UI).

hope i convey my issue clearly??

**Comment by esoekianto** [comment]
@sanramanathan yes you did, and you are correct that what we need to find out is what is, which request triggers the identity manager (login popup).

I would normally examine all the requests (especially the ones that going to ArcGIS Online or ArcGIS Server) at fiddlers or network tab in developers tools, and see which one that has response "token required".

if you want I can call you and take a look at your application to help you troubleshoot this, or fiddler log would also be helpful

**Comment by sanramanathan** [comment]
@esoekianto  I checked with Fiddler and netowk tab about the point you have mentioned.

I found that when a user(first time) from different pc(other than developer pc) login to my application, in fiddler i noticed that json  request goes to the mapservice  whose response is error :499 ,Token required following that "arcgis/rest/info?f=json" is called,then popup appears.
![error new user](https://cloud.githubusercontent.com/assets/3839368/14278471/7e67d64c-fb5a-11e5-99ab-c3508b228b11.jpg)

same machine with my login(logged many times),in fiddler for the same map service json response is layer:id so on...
![no error](https://cloud.githubusercontent.com/assets/3839368/14278524/b8aa6644-fb5a-11e5-8340-efff19469a83.jpg)
