### ISSUE TITLE
Can not handle the options request (.net proxy).

### ISSUE THREAD

**Issue by wcfbj0** [Esri/resource-proxy#351]
When I run the proxy in IE (IE 11), there is no problem whether the length of the request is longer (request method is POST) than 2048 or less (request method is GET). 

When I run the proxy in Chorme (Version 49.0.2623.110 ), proxy works fine if the request url length is less than 2048 (request method is GET).  If the request URL length is longer than 2048, the request method is OPTIONS, and request body is null. This is a preflight request, and the proxy can not handle it.  Any thoughts for this issue? Thank you.

**Comment by bsvensson** [comment]
@wcfbj0 - what is the request URL that cause an OPTIONS request?

**Comment by wcfbj0** [comment]
Here are the way you could duplicate the issue in Chrome. 
1. In Web App Build, add a printing widget to your web application. 
2. change the "config.json" in your web application and use the proxy. 
3. run the web application in Chrome, and run the printing widget.  In order to have a "WEB Map as Json" input, you could enable all the layers in your map, or change the Map Title to "AnyWord..... (make sure the title have 2100+ character. )". 
A "OPTIONS" request will be created if you are running your web application in Chrome.  But in IE, a "POST" request is created with the correct body.   

Let me know if you have more questions.  Thank you.
