### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by carrbrpoa** [Esri/resource-proxy#352]
Hello,

With 1.1.0 release, I'm trying:
http://localhost/proxy/proxy.ashx?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson, but it always gives me

```javascript
{error: {code: 500,message:"Impossível conectar-se ao servidor remoto http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson"}}
```

The `message` means "Impossible to connect to the remote server". I'm using Windows 8.1 and ASP.NET 4.5 AppPool, with .NET CLR v4.0.
The log contains the same message.

I can access the URL directly in the browser or with proxy 1.1 beta version (with that same AppPool) and `?ping` works.

Any ideas?

Thanks

**Comment by MikeTschudi** [comment]
Please try with proxy site's URL, e.g., `http://myserver.com/proxy/proxy.ashx?...`

`localhost` can be a problem
