### ISSUE TITLE
My Web App Builder is not working properly.

### ISSUE THREAD

**Issue by tmkanthapppally** [Esri/resource-proxy#355]
When I am selecting web map,the layers are not loading.The only thing loading is the base map and that extent.layers not displaying or showing.

![image](https://cloud.githubusercontent.com/assets/18652741/14775025/7d00f5f2-0ad9-11e6-8496-eee25a02d11d.png)

**Comment by esoekianto** [comment]
Can you show us the network traffic? Maybe the layer is not shared to the user you are logged in to

**Comment by tmkanthapppally** [comment]
Yes it is shared
