### ISSUE TITLE
Java proxy on a JBOSS server

### ISSUE THREAD

**Issue by lingpri** [Esri/resource-proxy#356]
My arcgis services are hosted in a IIS server, and my application and the Java Proxy in a Jboss server on a virtual machine.

proxy.xml excerpt :

`<serverUrl url="http://hostname"  matchAll="true" domain="<strong>" username="*" password="</strong>*"/><br/>`

When I access the services through the proxy page

http://cbrhel6jboss004:8080/Java/proxy.jsp?http://hostname/ags/rest/services

I get an 401 error, please advice , how to fix this issue.

**Comment by esoekianto** [comment]
@lingpri can you provide more information regarding the error? such as full error message or screen shot. 

also did you try to run the ping command like this, http://cbrhel6jboss004:8080/Java/proxy.jsp?ping

**Comment by lingpri** [comment]
![jboss_error](https://cloud.githubusercontent.com/assets/6947168/15218387/598c80b0-1825-11e6-85ad-5a86e973cfc5.png)

I get Http 401 error. The cloud vm on a red hat linux hosts the JBOSS and the resource proxy), I'm logged in as a root admin user on the cloud vm, to run the JBOSS. The arcgis services are secured to a default  all "company Domain users". I'm thinking , somewhere the credentials are not being authenticated by the arcgis services. 

Please advice.


yes I did use the ping command and its returning OK.

**Comment by esoekianto** [comment]
@lingpri I am not sure I follow when you say, "company domain users", are you saying that the arcgis server is secured using Windows Authentication instead of out of the box GIS token authentication?

If that's the case, only .NET version of the resource proxy can work with that

**Comment by ves-krd** [comment]
@lingpri How did you deploy the Java proxy to Jboss?
