### ISSUE TITLE
PHP proxy got 500 error on both 1.1.0 and 1.1.1-beta

### ISSUE THREAD

**Issue by zhiyuli** [Esri/resource-proxy#357]
Hi there,
I am trying to setting up a PHP proxy server in order to let our ArcGIS JS app access some paid Esri services through one esri organizational account (App login). I used the official example "World traffic" (https://www.mymanatee.org/arcgis_js_api/sdk/jssamples/ags_traffic.html) to test the proxy server.

But this example app could not display the traffic layer. 
F12 shows a 500 error on:
http://10.2.115.24/PHP/proxy.php?http://traffic.arcgis.com/arcgis/rest/services/World/Traffic/MapServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

/proxy.php?ping returns:
{"Proxy Version":"1.1.1-beta","Configuration File":"OK","Log File":"OK"}

/proxy-verification.php returns: 
Check PHP version 5.4.2 or newer?   Pass [v5.6.21]
Check if directory is writable? Pass
Check for PDO Sqlite extension? Fail
Check for Curl? Pass [v.7.19.7]

Is this error related to the above failure: "Check for PDO Sqlite extension   Fail"?

Server info:
CentOS 6.7
Apache 2.2.15
PHP 5.6.21

Any suggestion?
Thanks

**Comment by esoekianto** [comment]
@zhiyuli somehow I could not open the link you provided to see the error message, can you give more information about the error message? full message or screen shot would help

but in general error 500 refers to error in the web server itself, it is possible that it has something to do with failing one of the requirement in the php-verification page.

**Comment by zhiyuli** [comment]
@esoekianto 
sorry the url I posted is a local vm.

you may access the following urls instead to check it out.
https://appsdev.hydroshare.org/PHP/ags_traffic/index.html
https://appsdev.hydroshare.org/PHP/proxy.php?ping
https://appsdev.hydroshare.org/PHP/proxy-verification.php
thanks

**Comment by esoekianto** [comment]
@zhiyuli it is likely possible that this 500 erros is caused by missing PDO Sqlite extension, since this error is only appears when making request to url that is listed in proxy.config, and it is trying to write to log file

where we could json error message 403 when trying to access other urls that are not listed in proxy.config

are you in position to fix the PDO Sqllite extension?

**Comment by zhiyuli** [comment]
@esoekianto 
Thanks for looking into this issue.
I saw the minmum requirments for PHP proxy are:
PHP 5.4.2 or higher (recommended)
cURL PHP extension
OpenSSL PHP extension
PDO_SQLITE PDO PHP extension

But we are using CentOS 6.7 and it only has PHP 5.3 in its official repository. So I followed this link http://www.shayanderson.com/linux/centos-5-or-centos-6-upgrade-php-to-php-54-or-php-55.htm to install an "unofficial" higher version PHP (5.5). It has cURL PHP extension and OpenSSL PHP extension by default, but looks like it is hard to find a compatible PDO_SQLITE PDO PHP extension.

Is there any way to walk around the PDO_SQLITE PDO PHP extension?
thanks

**Comment by zhiyuli** [comment]
@esoekianto 
Also looks like our apache did not log any thing related to this error. And the proxy_log.log only shows some "GET detected" and "Pinged".

**Comment by esoekianto** [comment]
@zhiyuli looks like the logging functionality is working if you see some text in the log file

**Comment by zhiyuli** [comment]
@esoekianto  yes there is some text in the proxy_log.log file. Looks like something else is wrong....

**Comment by esoekianto** [comment]
@zhiyuli apologize, but at this point, I don't have any other clue other than missing PDO_SQLITE extension in the web server. 

as far as walkaround for the PDO_SQLITE extension, I would think if you are good in PHP, you could go thru the code and remove the dependencies or replace it with similar methods or libraries

**Comment by zhiyuli** [comment]
@esoekianto thanks. one update from my side: I set up the PHP proxy server on a local Ubuntu 14.04 server. It does not have PDO_SQLITE extension installed. But it is working! The world traffic app can display traffic layer properly. It is so weird that the same thing is NOT working on CentOS 6.7 ...

![image](https://cloud.githubusercontent.com/assets/10070599/15221873/7693efe0-182a-11e6-83c0-dea1051d1f83.png)

**Comment by esoekianto** [comment]
ooh so it is something to do with the version of PHP?

**Comment by zhiyuli** [comment]
@esoekianto  I dont know... The php on CentOS 6.7 we are using is 5.5.35, on Ubuntu it is 5.5.9. They are almost the same PHP except the difference in minor version number...

**Comment by esoekianto** [comment]
@zhiyuli this is good, we would have to investigate this further and test that specific version and/or the specific OS. but im glad that it is working out for you now

**Comment by phpmaps** [comment]
@zhiyuli @esoekianto - the PDO extension is a requirement and is a hard dependency to support rate limiting specified in the config.  The proxy uses Sqlite to count number of requests to certain resources.  If you do not have rate limiting needs you can take out all lines of code that involve rate limiting and Sqlite.
