### ISSUE TITLE
Proxies should not return hop-by-hop header fields

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#362]
As per https://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-7.1.3 and https://www.mnot.net/blog/2011/07/11/what_proxies_must_do there are several "hop-by-hop header fields" that should not be parsed along by proxies, neither in requests nor responses.
- Connection
- Keep-Alive
- Proxy-Authenticate
- Proxy-Authorization
- TE
- Trailer
- Transfer-Encoding
- Upgrade

Some of the resource-proxies already do part of this. It would be good to test all of them...

**Comment by bsvensson** [comment]
(Testing out github's new "multiple assignes for an issue or PR)

**Comment by esoekianto** [comment]
This is interesting read, definitely something we need to add in the proxy to strip out these hop-by-hop headers

**Comment by bsvensson** [comment]
This should now be fixed for DotNet - see #433.
