### ISSUE TITLE
Error parsing dynamicLayers

### ISSUE THREAD

**Issue by fredericmazzini** [Esri/resource-proxy#363]
Hello,

In my application, when i use the php proxy to display a portal web map with dynamic layers i get the following error : "Error : Error parsing dynamicLayers.".

Without the proxy the web map displays correctly but the popups not "The 'Access-Control-Allow-Origin' header contains the invalid value 'null'. Origin 'http://comminges.cirad.fr' is therefore not allowed access."

Fred
[conventions.txt](https://github.com/Esri/resource-proxy/files/286969/conventions.txt)

**Comment by esoekianto** [comment]
can you try adding 
``` esriConfig.defaults.io.corsEnabledServers.push("'http://comminges.cirad.fr"); ````

in javascript api code?

**Comment by fredericmazzini** [comment]
I added esriConfig.defaults.io.corsEnabledServers.push("arcgisserver.cirad.fr") and removed 
urlUtils.addProxyRule( {
		proxyUrl : "/~mazzini/proxyArcgis/proxy.php",
		urlPrefix: "arcgisserver.cirad.fr"
		
	});
but i get always errors (see attached file)
[javascript.txt](https://github.com/Esri/resource-proxy/files/287009/javascript.txt)

**Comment by fredericmazzini** [comment]
Sorry I have closed accidentally this issue

**Comment by esoekianto** [comment]
This is weird. What version of ArcGIS Server are you using? Is this an older arcgis server?

Can you try adding the proxy url here, 

``` esriConfig.defaults.io.proxyUrl = "<url_to_proxy>" ````

**Comment by fredericmazzini** [comment]
Ok, after a refresh of my cache everything works correctly with cors. Vut why i can't use the proxy without getting error : "Error : Error parsing dynamicLayers." ? Is-it a limitation ?

**Comment by bsvensson** [comment]
> Vut why i can't use the proxy without getting error : "Error : Error parsing dynamicLayers." ? Is-it a limitation ?

@fredericmazzini - it should work.  Do you have a public webmap that we can test against?

**Comment by fredericmazzini** [comment]
@bsvensson - No i'm sorry. 
My dynamics layers are built using "Query Layer". The data comes from an Oracle database.

**Comment by torrin47** [comment]
We're having a similar issue - seems like the definitionExpression in particular isn't making it gracefully through the proxy. Our services and proxies are internal and locked down, but hopefully it tells the right story. Here's the form data that's being posted to the proxy:

```
dpi:96
transparent:true
format:png8
dynamicLayers:[{"id":0,"name":"Water Quality Monitoring Stations","source":{"type":"mapLayer","mapLayerId":0},"definitionExpression":"EcoregionIdentifier='X'","drawingInfo":{"renderer":{"type":"uniqueValue","field1":"P_SamplesMedian_Concern","defaultSymbol":{"color":[153,153,153,255],"size":9,"angle":0,"xoffset":0,"yoffset":0,"type":"esriSMS","style":"esriSMSDiamond","outline":{"color":[0,0,0,255],"width":0.375,"type":"esriSLS","style":"esriSLSSolid"}},"uniqueValueInfos":[{"value":"1","symbol":{"color":[44,123,182,255],"size":9,"angle":0,"xoffset":0,"yoffset":0,"type":"esriSMS","style":"esriSMSDiamond","outline":{"color":[0,0,0,255],"width":0.375,"type":"esriSLS","style":"esriSLSSolid"}}},{"value":"2","symbol":{"color":[171,217,233,255],"size":9,"angle":0,"xoffset":0,"yoffset":0,"type":"esriSMS","style":"esriSMSDiamond","outline":{"color":[0,0,0,255],"width":0.375,"type":"esriSLS","style":"esriSLSSolid"}}},{"value":"3","symbol":{"color":[253,174,97,255],"size":9,"angle":0,"xoffset":0,"yoffset":0,"type":"esriSMS","style":"esriSMSDiamond","outline":{"color":[0,0,0,255],"width":0.375,"type":"esriSLS","style":"esriSLSSolid"}}},{"value":"4","symbol":{"color":[215,25,28,255],"size":9,"angle":0,"xoffset":0,"yoffset":0,"type":"esriSMS","style":"esriSMSDiamond","outline":{"color":[0,0,0,255],"width":0.375,"type":"esriSLS","style":"esriSLSSolid"}}}]}},"minScale":0,"maxScale":0}]
bbox:-12429336.867769243,2877258.4016377386,-8420367.608269384,4589447.835225232
bboxSR:102100
imageSR:102100
size:1639,700
f:json
layerDefs:0:EcoregionIdentifier='X'
```
And here's what we see in the ArcGIS Server full Debug logs:

`com.esri.arcgis.discovery.json.JSONException: Expected a ',' or '}' at character 123 of [{id:0,name:Water Quality Monitoring Stations,source:{type:mapLayer,mapLayerId:0},definitionExpression:EcoregionIdentifier=VIII,drawingInfo:{renderer:{type:uniqueValue,field1:P_SamplesMedian_Concern,defaultSymbol:{color:[153,153,153,255],size:9,angle:0,xoffset:0,yoffset:0,type:esriSMS,style:esriSMSDiamond,outline:{color:[0,0,0,255],width:0.375,type:esriSLS,style:esriSLSSolid}},uniqueValueInfos:[{value:1,symbol:{color:[44,123,182,255],size:9,angle:0,xoffset:0,yoffset:0,type:esriSMS,style:esriSMSDiamond,outline:{color:[0,0,0,255],width:0.375,type:esriSLS,style:esriSLSSolid}}},{value:2,symbol:{color:[171,217,233,255],size:9,angle:0,xoffset:0,yoffset:0,type:esriSMS,style:esriSMSDiamond,outline:{color:[0,0,0,255],width:0.375,type:esriSLS,style:esriSLSSolid}}},{value:3,symbol:{color:[253,174,97,255],size:9,angle:0,xoffset:0,yoffset:0,type:esriSMS,style:esriSMSDiamond,outline:{color:[0,0,0,255],width:0.375,type:esriSLS,style:esriSLSSolid}}},{value:4,symbol:{color:[215,25,28,255],size:9,angle:0,xoffset:0,yoffset:0,type:esriSMS,style:esriSMSDiamond,outline:{color:[0,0,0,255],width:0.375,type:esriSLS,style:esriSLSSolid}}}]}},minScale:0,maxScale:0}] at com.esri.arcgis.discovery.json.JSONTokener.syntaxError(JSONTokener.java:454)`

Seems like something in the proxy is stripping out all the quotes.

**Comment by esoekianto** [comment]
@torrin47 quite possible with the definition expression, it may have something to do with the url/json parsing or decoding the encoded definition expression. 

we will need to see the url made to the proxy or some sort of repro case to be able to pin point which character that cause this

**Comment by torrin47** [comment]
Unfortunately our proxy is really locked down, and we don't have a public-facing equivalent we can share that's open for testing. But if all you need is a public-facing service with an example definitionLayer that you can use with your proxy, happy to share that.  Give this one a try:

https://gispub.epa.gov/arcgis/rest/services/OEI/EPA_Locations/MapServer/export?dynamicLayers=%5B%7B%22id%22%3A2%2C%22name%22%3A%22EPA%20Regions%20Small%20Scale%20(%3C%201%3A5%2C000%2C001)%22%2C%22source%22%3A%7B%22type%22%3A%22mapLayer%22%2C%22mapLayerId%22%3A2%7D%2C%22definitionExpression%22%3A%22EPAREGION%20%3D%20%27Region%2010%27%22%2C%22drawingInfo%22%3A%7B%22renderer%22%3A%7B%22type%22%3A%22simple%22%2C%22symbol%22%3A%7B%22color%22%3A%5B227%2C139%2C79%2C255%5D%2C%22outline%22%3A%7B%22color%22%3A%5B255%2C255%2C255%2C255%5D%2C%22width%22%3A0.75%2C%22type%22%3A%22esriSLS%22%2C%22style%22%3A%22esriSLSSolid%22%7D%2C%22type%22%3A%22esriSFS%22%2C%22style%22%3A%22esriSFSSolid%22%7D%7D%7D%2C%22minScale%22%3A0%2C%22maxScale%22%3A5000001%7D%5D&dpi=96&transparent=true&format=png32&bbox=-14582915.476279886%2C4639974.500334173%2C-11356661.386420025%2C6528274.847090665&bboxSR=102100&imageSR=102100&size=1319%2C772&layers=show%3A2&layerDefs=2%3AEPAREGION%20%3D%20%27Region%2010%27&f=json
