### ISSUE TITLE
Error when uploading attachments using php 5.6+ (but works with 5.5)

### ISSUE THREAD

**Issue by godsmustbcrazy** [Esri/resource-proxy#364]
When I try to upload an attachment using the php proxy I get this error on the server 

Unable to process request. java.lang.String cannot be cast to com.esri.arcgis.discovery.json.JSONObject

I have tried troubleshooting this a lot but I cant seem to get anywhere. Any help would be much appreciated. 

The request details are like below ( urls obscured ) 
https://proxurl.com/proxy.php?https://serverurl.com:6443/arcgis/rest/services/editingservices/servicename/FeatureServer/0/106765/addAttachment

debugging proxy screenshots below

Request 

![image](https://cloud.githubusercontent.com/assets/78633/15638689/97be254a-25f0-11e6-9c46-3d21bc470554.png)
![image](https://cloud.githubusercontent.com/assets/78633/15638723/0b463ef8-25f1-11e6-9d5b-759f1c3c2de3.png)

Response 
![image](https://cloud.githubusercontent.com/assets/78633/15638704/d6e99aba-25f0-11e6-8420-1e00886ca3d6.png)

Results of proxy verification:
Check PHP version 5.4.2 or newer?   Pass [v5.6.21]
Check if directory is writable? Pass
Check for PDO Sqlite extension? Pass
Check for Curl? Pass [v.7.40.0]

**Comment by godsmustbcrazy** [comment]
I added some extra logging to the proxy and here is what I found was in the queryArray that curl is POSTING

05-30-16 03:51:30 | key:f       value:json
05-30-16 03:51:30 | key:attachment       value:@/tmp/1.jpg
05-30-16 03:51:30 | key:token       value:TOKENVALUE

**Comment by godsmustbcrazy** [comment]
Found the issue: It was a simple version compatibility problem ( https://stackoverflow.com/questions/25934128/curl-file-uploads-not-working-anymore-after-upgrade-from-php-5-5-to-5-6) 

php version 5.6 does not support the @ special character for files 

You can do one fo the two methods you can either set 

The two lines 1175 and 1177
                        $this->proxyData[$key] = "@" . $this->unlinkPath;
                        $query_array[$key] = "@" . $this->unlinkPath;

To
                        $this->proxyData[$key] = new CURLFile($this->unlinkPath, $file['type']);

                        $query_array[$key] = new CURLFile($this->unlinkPath, $file['type']);

And add CURLOPT_SAFE_UPLOAD before line 1193

            curl_setopt($ch, CURLOPT_SAFE_UPLOAD, true);


The other option is to set CURLOPT_SAFE_UPLOAD to false above line 1193 but that was not recommended

**Comment by bsvensson** [comment]
@godsmustbcrazy - Thanks for opening this issue and also finding the solution.  I'm going to re-open this issue to keep track of this problem until we fixed it in the php proxy.

**Comment by phpmaps** [comment]
@godsmustbcrazy thanks.  Looking into this with @bsvensson.  This is long over do but I think we've reached a point in time where we have to consider version specific fixes and get with the team responsible for addAttachment logic..  Interesting.  I was not aware of the point you made with php version 5.6 does not supporting the @ special character for files.  Thanks.

**Comment by bsvensson** [comment]
#365 has been merged.

Closing.

Note also that the resource-proxy is moving to only support PHP 7.1 and later - see #449.
