### ISSUE TITLE
Secured Feature service with attachments enabled does not work if the service is passed through proxy and attachment size is greater than 4 MB

### ISSUE THREAD

**Issue by amritkumar90** [Esri/resource-proxy#368]
Unable to attach attachments to secure services through proxy. The issue occurs when the attachment size exceeds 4Mb and when we try to pass the service through proxy. The application fails to attach any attachment with size greater than or equal to 4MB and throws internal server error. Attached is the sample application(In .Txt format, Please save it as HTML for testing )

[Attachment_test.txt](https://github.com/Esri/resource-proxy/files/298392/Attachment_test.txt)

**Comment by bsvensson** [comment]
This is more likely a web server issue.  You're using the DotNet proxy, and IIS 6 have a default maximum file upload size of 4 MB.  See e.g. http://ajaxuploader.com/large-file-upload-iis-asp-net.htm for more info.

Are you using IIS 6?

**Comment by bsvensson** [comment]
Closing as presumed answered.  @amritkumar90 - feel free to re-open with more details.

**Comment by aspetkov** [comment]
I have a form that excepts a file upload in ASP.NET. I need to increase the max upload size to above the 4 MB default.

**Write in Web.config in DotNet proxy folder**
To increase uploading file's size limit we have two ways

1. IIS6 or lower

    By default, in ASP.Net the maximum size of a file to be uploaded to the server is around 4MB. This value can be increased by modifying the maxRequestLength attribute in web.config.

    Remember : maxRequestLenght is in KB

Example: if you want to restrict uploads to 15MB, set maxRequestLength to “15360” (15 x 1024).

<system.web>
    
   <httpRuntime maxRequestLength="15360" ></httpRuntime> 
</system.web>

2. IIS7 or higher

    A slight different way used here to upload files.IIS7 has introduced request filtering module.Which executed before ASP.Net.Means the way pipeline works is that the IIS value(maxAllowedContentLength) checked first then ASP.NET value(maxRequestLength) is checked.The maxAllowedContentLength attribute defaults to 28.61 MB.This value can be increased by modifying both attribute in same web.config.

    Remember : maxAllowedContentLength is in bytes

Example : if you want to restrict uploads to 15MB, set maxRequestLength to “15360” and maxAllowedContentLength to "15728640" (15 x 1024 x 1024).

<system.web>
    
   <httpRuntime maxRequestLength="15360" ></httpRuntime> 
</system.web>

<system.webServer>              
   <security> 
      <requestFiltering> 
          
         <requestLimits maxAllowedContentLength="15728640" ></requestLimits>
      </requestFiltering> 
   </security>
</system.webServer>
http://stackoverflow.com/questions/288612/how-to-increase-the-max-upload-file-size-in-asp-net
