### ISSUE TITLE
PHP and DotNet proxies does not support empty POST

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#370]
Currently if you send an empty POST, the php and dotnet proxies complain about error 411.  Java works fine.

See https://github.com/Esri/resource-proxy/pull/345 for a possible DotNet solution.

Simple PHP test case:
`curl -X POST  "http://localhost/resource-proxy/PHP/proxy.php?ping`

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

Simple DotNet test case:
`curl -X POST  "http://localhost/resource-proxy/DotNet/proxy.ashx?ping`

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

Compared to 
`curl -X POST  http://loan218692.esri.com:8080/proxy.jsp?ping`

```
{ "Proxy Version": "1.1 Beta", "Configuration File": "OK", "Log File": "Not Exist/Readable"}
```

There are quite a lot of info about this quirk on the web.
- https://sevalapsha.wordpress.com/2011/08/03/curl-http11-empty-post-bug/
- http://stackoverflow.com/questions/2885274/post-with-curl-without-sending-data
- http://robertgreiner.com/2013/01/the-remote-server-returned-an-error-411-length-required/
- https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13:_"Applications SHOULD use this field [Content-Length] to indicate the transfer-length of the message-body, unless this is prohibited by the rules in section 4.4."_
- https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4" _"If a request contains a message-body and a Content-Length is not given, the server SHOULD respond with 400 (bad request) if it cannot determine the length of the message, or with 411 (length required) if it wishes to insist on receiving a valid Content-Length."_.. and more exceptions

**Comment by phpmaps** [comment]
@bsvensson When I run the simple PHP test case:
```curl -X POST "http://localhost/resource-proxy/PHP/proxy.php?ping```  I get reasonable results.  I see this outputted.  

```{"Proxy Version":"1.1.1-beta","Configuration File":"OK","Log File":"OK"}```

Also since the first parameter following the ```?``` is designed to be a URL, the test case is unclear to me.    Can you explain a bit more?   Should the test be ```curl -X POST "http://localhost/resource-proxy/PHP/proxy.php?<some-web-page-included-in-the-proxy-config>``` ??

**Comment by bsvensson** [comment]
@phpmaps - that's different from what I see on my (Windows) machine.  Are you using the latest? (I know this wasn't an issue with some earlier versions)

```
C:\somewhere>curl -X POST "http://localhost/resource-proxy/PHP/proxy.php?ping"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```
while the GET works fine
```
C:\somewhere>curl -X GET "http://localhost/resource-proxy/PHP/proxy.php?ping"
{"Proxy Version":"1.1.1-beta","Configuration File":"OK","Log File":"OK"}
C:\Users\bjor3345\Documents\gh\arcgis-js-sdk>
```
using `curl 7.47.1 (x86_64-pc-win32) libcurl/7.47.1 OpenSSL/1.0.2f zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.8.0`

**Comment by phpmaps** [comment]
@bsvensson yes on using the latest version of the proxy.  However my tests were done on a macbook with PHP 5.5.7.  Maybe this is a Windows issue only?  I am still unsure of the issue.  Since ping is not a url should we expect this to work?  Also what if someone were to do this -  

``` curl -X POST "http://localhost/resource-proxy/PHP/proxy.php?githubissue```

What is the expected result suppose to be?
