### ISSUE TITLE
ArcGIS Server file attachments for Microsoft Office 2007 are corrupted

### ISSUE THREAD

**Issue by pfoppe** [Esri/resource-proxy#371]
**Scenario:** Deployed ArcGIS for Server services with file attachments.  User uploaded a Microsoft Office 2007 (and higher) document (ex: .docx, .xlsx, .pptx).  When downloading the document through the DotNet proxy the file is corrupted. Downloading the document directly against the REST end-point is successful.

We modified the proxy.ashx.. specifically the **fetchAndPassBackToClient** method.  The if statement with the 
`serverResponse.ContentType.Contains("xml")`

appears to be the culprit.  The content-type of a MS Word .docx (2007+) is _application/vnd.open**xml**formats-officedocument.wordprocessingml.document_

so the response is being handled as a 'text' rather than 'binary'.

**Comment by bsvensson** [comment]
@pfitts Which version of the proxy are you using?  There was a check-in a few days ago - see https://github.com/Esri/resource-proxy/issues/367 - does this fix or break your scenario?

**Comment by pfoppe** [comment]
We downloaded the master "1.1.1-beta" version last night with what appears to be the last commit being #367.  although I only see a fix for **application/vnd.ogc.wms_xml** not **application/vnd.openxmlformats**

Although the fix on #367 appears to be for setting the content-type back to _text/xml_ which I dont think is desired.  I think the content-type needs to be set to the appropriate [MIME-Type for the office formats](http://filext.com/faq/office_mime_types.php)

We adjusted the 
`serverResponse.ContentType.Contains("xml")`
to
`serverResponse.ContentType.Contains("/xml")`

so that it would not process the response as "Text" and instead processed it as "BINARY".  although this might have some adverse effects since we did not take into account all MIME-Types with */xml* and how they should be handled.

**Comment by bsvensson** [comment]
To account for the adverse effects, maybe a better solution would be to do `Contains("xml")` but not containing `vnd.openxmlformat`. That should account for these 7 MS MIME-Types, and not effect anything else.

That would be a good pull request :)

Or if there was a better way of knowing when an xml is binary...
