### ISSUE TITLE
PHP Proxy, can't execute proxy.php

### ISSUE THREAD

**Issue by odoe** [Esri/resource-proxy#372]
Korara 23
PHP 5.6.22
Apache 2.4.18

So the proxy verification page works, I can use a test page with `phpinfo()`, everything seems to work.

I'm set permissions on the proxy folder, copied SELINUX permissions (because Red Hat) and by all accounts, PHP seems to be working.

*But* when I try `http://localhost/proxy/proxy.php` or `http://localhost/proxy/proxy.php?ping` I just get `500 Internal Server Error`, no response, no nothing.

I'm at a loss at this point. I even went back to an old 2014 version of the PHP proxy I had on this machine before formatting because I knew it worked in Ubuntu Linux and still no luck.

I'm wondering if this is a Fedora/Red Hat specific issue or not.

Thanks.

**Comment by bsvensson** [comment]
Hi @odoe - did you ever solve this issue?  It doesn't seem to be specific to the proxy code but more that specific setup.

**Comment by odoe** [comment]
I'm going to chalk this one up to some odd permission issues via SELINUX in Korora. I went back to Ubuntu and all is well. If someone runs across a similar issue, we can open this back up again.
