### ISSUE TITLE
Edit Tracking Capability

### ISSUE THREAD

**Issue by kawayz** [Esri/resource-proxy#375]
This is a wonderful resource but I find simultaneous edit tracking to be challenging.  Would it be possible to modify this proxy application to track the edits of specific user accounts simultaneously?  Currently I can only setup the dot net proxy application to use one user account so all the edits are recorded as the user specified in the proxy application.   Is there way to track multiple editors at the same time.  Maybe starting with just one to five users each getting their own proxy login to specific rest services for instance.
 
I certainly cannot do this myself so I am asking for help from the talented community of programmers that maintain this proxy application.

Thank you.

**Comment by jgravois** [comment]
if you'd like end users to authenticate themselves, why use a proxy at all?

**Comment by kawayz** [comment]
not sure what you mean Jgravois?

**Comment by esoekianto** [comment]
@kawayz 
I think what @jgravois was trying to say that the proxy will only use the one credential that is specified in the configuration page. 

Normally if you want to track the edits done by the users, the end user would need to login to specify who they are. So the question is why would need to use the proxy if you let the end user to specify who they are.

**Comment by kawayz** [comment]
Both jgravois and esoekianto have summarized my request with a question.   I would like to use more than one set of user credentials to login with the proxy application.  Can anyone in the community perform such a modification?

**Comment by bsvensson** [comment]
Hi @kawayz 
The most common way to handle editor tracking for multiple users when using ArcGIS Server is documented at http://server.arcgis.com/en/server/latest/publish-services/windows/editor-tracking-for-feature-services.htm.  Are you maybe not using ArcGIS Server, and thus that's why you would like to handle the user credentials outside of ArcGIS Server?

**Comment by kawayz** [comment]
Hi @bsvensson 

Yes I would like to pass more than one editor's credentials thru the proxy application when using arcGIS Server from a dot net website.  At this time only one user credential can pass thru with the proxy application even though multiple users are performing edits.  Maybe this is to difficult to implement but  I envision at least five user credentials passing thru the proxy to the same rest service end point for example while the rest of the users pass thru as it stands.   

 Thank you for responding to this request.

**Comment by jgravois** [comment]
i still think that if you already have users signed into a .NET application you're better off skipping the proxy entirely and instead just ensure that they start making authenticated requests directly to your secure services.

that said, if anyone in the community understands the need better than i do and is willing to write the code on @kawayz's behalf, they are certainly free to.

**Comment by kawayz** [comment]
@jgravois 
Thanks so much for helping me articulate the issue.  I really appreciate everyones help.  The way I see it many of the popular standalone web viewers originate from out of the box ESRI templates.  These sites rely on the proxy application for authentication as well as support for 2048 char requests, cross domain access, and resource/ refer limitations.  The proxy application provides a lot of functionality that a custom DOT .NET solution may not provide in a timely fashion.  

To fully understand the issue try edit tracking with an out of the box ESRI viewer that accesses an arcGIS server using this very sophisticated proxy application.  Try the out of the box Web AppBuilder for Developer solution (WABD) for example since it provides extended mapping functionality including web based editing of points, lines, polygons, and table data. Then access this application behind a firewall using the proxy application for authentication to the rest map services in the map viewer as recommend by ESRI in the help documents.  You will find that the proxy application cannot handle edit tracking, since it only recognizes a single authenticated user at a time. 

So the request is to modify this proxy application to handle multiple user credentials.  This way edits from multiple users could be tracked as they pass thru the this proxy application.

Thanks for the help.

**Comment by kawayz** [comment]
ok ok uncle.
