### ISSUE TITLE
DotNet proxy error - Unable to obtain token -

### ISSUE THREAD

**Issue by dhinag** [Esri/resource-proxy#377]
I am utilizing the .net proxy code along with my client id and client credentials to use esri public api services for rendering the map. I get the below error in my log file

Token cannot be obtained: {"error":{"code":400,"message":"Unable to generate token","details":["Unable to generate token for this server"]}}
Has someone encountered this error before? I'd appreciate any pointers. Let me know if you require any details for troubleshooting.

**Comment by esoekianto** [comment]
which services are you trying to use? from ArcGIS Online or Portal?
