### ISSUE TITLE
Cannot access non-authenticated resource via proxy

### ISSUE THREAD

**Issue by intotecho** [Esri/resource-proxy#380]
I have installed the proxy and am trying to access the resource via the proxy.
 _PHP/_proxy.config_ includes 
```
<ProxyConfig allowedReferers="*"
             logFile="/var/log/proxy/arcgisproxy_log.log"
             mustMatch="true">
    <serverUrls>
        <serverUrl url="http://ec2-54-204-216-109.compute-1.amazonaws.com:6080/arcgis/rest/services/wdpa/wdpa/MapServer/0" matchAll="true"  />
    </serverUrls>
</ProxyConfig>
```
There are no username, password or oauth2 parameters inside the <serverUrl> tag.

When I call the URL, 
http://bunjilforestwatch.net/PHP/proxy.php?http://ec2-54-204-216-109.compute-1.amazonaws.com:6080/arcgis/rest/services/wdpa/wdpa/MapServer/0=&callback=ags_jsonp.ags_jsonp_0_288177&f=json

Error 500 is returned and the _arcgisproxy_log.log_ shows
>08-03-16 01:10:33 | GET detected
> 08-03-16 01:10:33 | could not find driver
> 08-03-16 01:10:33 | Can not determine if OAuth or ArcGIS Server means of authentication.  Check config for errors.

The resource should be accessible without authentication.

Looks like a user error, but I can't find info on accessing unprotected layers.

**Comment by bsvensson** [comment]
> PHP/_proxy.config

The proxy config doesn't usually have an underscore in the filename. Is that something you've changed in the proxy to read from?  (Just making sure that the config file you're using is the one that you think is being used).

> could not find driver

I'm not sure I've seen this message before. Seems suspicious....   What versions of PHP/curl/proxy are you using?  You can find this information from the `proxy-verification.php` page and the `prox.php?ping`.

Does other things work your proxy?

**Comment by intotecho** [comment]
- curl 7.35.0 (x86_64-pc-linux-gnu)
- PHP Version 5.5.9-1ubuntu4.4
- Proxy  $version = "1.1.0";
- SQLite version 2.8.17
- OpenSSL version 1.0.1f 6 Jan 2014


The server is running wordpress. 
I had the files installed into /var/www/PHP and have also tried placing the proxy files into /var/www/html/

If I place [info.php](https://www.digitalocean.com/community/tutorials/how-to-change-your-php-settings-on-ubuntu-14-04) in there, it runs fine.

When I call /html/proxy.php?ping - The log file says 
> 08-04-16 04:10:55 | GET detected 
> 08-04-16 04:10:55 | Pinged

but the server returns 500. 

Also /html/proxy-verification.php returns 500 and no other info.

I have used the distribution proxy.config without changes and made the local log file read/write.
But when I send the http://bunjilforestwatch.net/html/proxy.php?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson

I also get 500 and the log file shows:

> 08-04-16 04:10:55 | GET detected
> 08-04-16 04:10:55 | could not find driver
> 08-04-16 04:10:55 | Can not determine if OAuth or ArcGIS Server means of authen

So it seems like something proxy-verification.php is doing is erroring out, or something is preventing it from returning a response.

**Comment by intotecho** [comment]
Thanks for your suggestions. 
I did some hacking of proxy.php and found out that curl_version() was simply hanging the script rather than reporting a missing capability.
It seems for or a DigitalOcean Ubuntu Wordpress build - curl isn't enabled for php default.
I ran 
`apt-get` install php5-curl 

but this did not work - curl can be installed, but not enabled in PHP5.

Then I found this post http://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init
To get the path of the curl executable 
'find / -name 'curl.so'
add this executable to php5.ini file 
etc/php5/apache2/conf.d/20-curl.ini

Now it works except I am getting a new (and unrelated) error 

> XMLHttpRequest cannot load http://bunjilforestwatch.net/esri/proxy.php?http://ec2-54-204-216-109.compute-1.amazonaws.com:6080/arcgis/rest/services/wdpa/wdpa/MapServer/0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8001' is therefore not allowed access. The response had HTTP status code 403.

Should the proxy add header Access-Control-Allow-Origin to the response?

**Comment by esoekianto** [comment]
@intotecho this is great. 

do you have your web application and the proxy in different servers?

**Comment by intotecho** [comment]
Yes, the proxy is on apache and the app is on app engine. In production they are served on the same domain, but in test and dev the application is running on localhost.

**Comment by intotecho** [comment]
Note the correct URL for arcgislink.js ends in MapServer, not MapServer/0. 

I was hoping to use the proxy to avoid the fact that port 6080 is blocked where I work, but then my dev server is on a different URL and it is blocked anyway. I will ask the publisher to move it to port 80.

**Comment by eflaco** [comment]
@intotecho : What was your solution here? I try to build up a Web AppBuilder IDE using a php-proxy, and I have exactly the same symptoms here.

**Comment by MigueBlogs** [comment]
09-29-21 17:25:23 | GET detected
09-29-21 17:25:23 | Can not determine if OAuth or ArcGIS Server means of authentication.  Check config for errors.

i have the same error woth an API of the NASA firemaps, there was a solution for this problem or alternative? i've expend many days on this problem and i cant find a solution
