### ISSUE TITLE
PHP proxy - Performance issues

### ISSUE THREAD

**Issue by hhkaos** [Esri/resource-proxy#385]
I'm having some performance issues when using the resource-proxy loading a secured layer hosted in ArcGIS Online. It's slowing down my application increasing more than 3 times (~4sec vs 14secs) what it takes to load a layer just using the proxy. But the problem gets bigger when adding more than one layer (some apps are taking more than 1 minute to load on a desktop).

I have recorded a 2min video where you can see that: https://youtu.be/nOC1xMitVi0

I'm using oAuth2, this is rule:

```xml
<serverUrl url="http://services.arcgis.com/"
matchAll="true"
clientid="d17Yd7ULGJ2yT9e4"
oauth2Endpoint="https://www.arcgis.com/sharing/oauth2"
clientsecret="..."
/>
```

I have notice that 8 queries (with different extents) are made to load the service:
- With the public service each request takes between 300ms and 550ms
- Using the proxy it takes between 544ms and 7.46**seconds** each

I have checked:
- Opening the service using a simple token (without the proxy) and it toked ~250ms to load. 
- Loading the layer using `mode: FeatureLayer.MODE_ONDEMAND` but it still does 8 queries

So my question is, can I improve the load time somehow?

**Comment by hhkaos** [comment]
Any thoughts on this @phpmaps @bsvensson ?

**Comment by hhkaos** [comment]
@odoe @jgravois do you have any idea about this?, thx ^_^

**Comment by bsvensson** [comment]
@hhkaos 
It's weird that some proxy requests take up to 7 seconds. I would try to figure that part out.

Just to test: If you have small window (less pixels), there should be less requests. Does the proxy still run up to the 2+ second range for these cases?

**Comment by hhkaos** [comment]
In that case it that case it doesn't take that much as you can see here: https://youtu.be/MO5BIaC9jxw

Only one request exceeds 2 seconds. Is this a problem with PHP itself about the number of requests that can handle simultaneously?

**Comment by thewabbit** [comment]
I'm having the same problem - has there been any progress on improving the performance?

**Comment by akrymer1989** [comment]
Im also having the same problem. Did anyone manage to get anywhere with this?

**Comment by EricG66** [comment]
I have a support case with a client and she is facing this issue. When I tried using DotNet poxy, it is fast but on a Linux box with PHP 7, it is very slow.

Any solution?

**Comment by phpmaps** [comment]
@EricG66 -  Would it be possible to post an JSAPI app with public layers showing this issue?  Something like a single page HTML/JSAPI file would be ideal.

In terms of the config problems which could slow down performance, usually you only want to proxy layers that need proxying, ie use `<serverUrl>`  for those endpoints.   Also my suggestion (without knowing details) is heavy consideration should be considered to solve this problem via a server CORS config.  When this proxy was released, CORS was relatively new and not well know.  CORS may give you the flexibility and security you need to POST cross domain, without having to even use this PHP proxy.

**Comment by bsvensson** [comment]
@EricG66 - as @phpmaps  mentions above, today there are better alternatives than using the resource-proxy. See on https://github.com/Esri/resource-proxy#alternatives for CORS and ArcGIS Online solutions.

**Comment by EricG66** [comment]
This is the client app:
One of the images is secured (copyright) and one public https://www.centrenature.qc.ca/vmsh_1964-2013/

**Comment by EricG66** [comment]
The data is in AGOL and we are using the proxy for the credentials (clientid and secret). The webapp is hosted somewhere in the cloud

**Comment by phpmaps** [comment]
@EricG66 If the PHP proxy is targeting the tiled service making it available to everyone, I would not use the proxy at all for this layer.  Instead have you considered making this layer public and consumable directly via JS, not the PHP proxy?

**Comment by EricG66** [comment]
@phpmaps The issue client is having is that one of the tiled service is copyrighted image fro 1964 (they want limited access to it)
