### ISSUE TITLE
498/499 check doesn't handle current version of geoenrichment

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/resource-proxy#386]
If the keyword `error` is found in the response from a server, the .Net program checks for four specific patterns
1. `"code": 498`
2. `"code": 499`
3. `"code":498`
4. `"code":499`

The current version of geoenrichment is returning valid but different JSON:
`"code" : 498`
which is not caught by the program.

**Comment by jgravois** [comment]
my first instinct is that interrogating the actual JSON object would be substantially less brittle...

**Comment by bsvensson** [comment]
Fixed in PR #388 which has been merged.

**Comment by bsvensson** [comment]
FYI: 
PHP:  php proxy first tries regex, and if that fails, then it tries with json parsing - https://github.com/Esri/resource-proxy/blob/master/PHP/proxy.php#L924-L946
