### ISSUE TITLE
.Net's getJsonValue's extraction for unquoted values doesn't work

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/resource-proxy#387]
For values that don't begin with a double quotation mark after the keyword and colon, the program uses the following expression to get the position of the end of the value:
```
Math.Max(0, Math.Min(Math.Min(value.IndexOf(","), value.IndexOf("]")), value.IndexOf("}")))
```

This expression, however, produces `-1`, rather than the length of the shortest match if the tested string is missing any of the search characters `,`, `]`, or `}`.  As a result, it fails to get the `expires_in` value from the following response example:
```
"{\"access_token\":\"xrdHGoWexCIN33XOw5qoOL\",\"expires_in\":7200}"
```

**Comment by bsvensson** [comment]
PR #388 was merged.
