### ISSUE TITLE
How to make proxy.jsp work under jre 1.6

### ISSUE THREAD

**Issue by xh2453** [Esri/resource-proxy#391]
My current jre environment is 1.6. I have an old proxy.jsp working on jre 1.6. I tried to make it work under new JavaScript 4.x and it failed.  ESRI technical support suggested me to use jre 1.7 in order to use new proxy.jsp. 

Is there any workaround for jre 1.6 since my environment only supports 1.6?

**Comment by bsvensson** [comment]
@xh2453 - You could try using an earlier version of the resource proxy (but I'm not sure that'll help).

However, I would strongly recommend upgrading the environment to at least 1.7.

From the Java download pages:
__WARNING:__ These older versions of the JRE and JDK are provided to help developers debug issues in older systems. __They are not updated with the latest security patches and are not recommended for use in production.__

**Comment by esoekianto** [comment]
+1

**Comment by xh2453** [comment]
An earlier version of the resource proxy does not seem working, which is why I ask if there wi workaround.

**Comment by xh2453** [comment]
When I tried old versions of your proxy.jsp, I encountered following error:

XMLHttpRequest cannot load http://[servername]:9080/TrcDD_online/proxy_09.jsp?htt…ibutes%22%3A%7B%7D%7D%5D%2C%22doNotLocateOnRestrictedElements%22%3Atrue%7D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9080' is therefore not allowed access.

XMLHttpRequest cannot load http://[servername]:9080/TrcDD_online/proxy_10.jsp?htt…ibutes%22%3A%7B%7D%7D%5D%2C%22doNotLocateOnRestrictedElements%22%3Atrue%7D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9080' is therefore not allowed access.

Any thought of how I can get it fixed?

Thanks,
Xiaotian

**Comment by esoekianto** [comment]
@xh2453 this looks like the CORS warning from the browser. it has nothing to do with the resource-proxy on the server side. 

To overcome this issue, 
1. you would first need to add "http://localhost:9080" to the corsEnabledServers list in the javascript code, https://developers.arcgis.com/javascript/3/jshelp/inside_defaults.html#corsEnabledServers 

2. then make sure that your web server (the http://localhost:9080) is CORS enabled, see this doc enable-cors.org 

I am closing this issue as this is non resource-proxy related.
