### ISSUE TITLE
Transform 200 OK from ArcGIS Server into more RESTful responses

### ISSUE THREAD

**Issue by keithmoss** [Esri/resource-proxy#393]
Hi folks,

In integrating AWS's CloudFront with this proxy we had a need to receive errors from ArcGIS Server with more RESTful HTTP Status headers (AGS's default being to pass all errors back as `200 OK` responses).

CloudFront has some [nice smarts for handling 4xx/5xx error codes](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html) and serving up a previously cached good response instead of an error (as well as setting TTLs for errors independent of good responses, et cetera). ArcGIS Online + the local AGS instances we're dealing with intermittently throw errors at times when under load, so gracefully handling errors for the user was quite important to us.

We hacked in a fix for this to the proxy locally and I wanted to see if you had any desire for a PR of a cleaned up version. The changes thus far are at https://github.com/keithmoss/resource-proxy/commit/745094375b335d88d49184d571bf6fc7ef89e68a.

**Comment by bsvensson** [comment]
Thanks @keithmoss for your suggestion. I agree that having more RESTful responses would be nice.  However, for now, in this resource-proxy, for backward compatibility (and compatibility with current ArcGIS Server/Portal) we want to keep the errors as `200 OK` responses containing the error messages.
