### ISSUE TITLE
Java - Oracle WebLogic - Failure of server APACHE bridge

### ISSUE THREAD

**Issue by tiagorodriguesribeiro** [Esri/resource-proxy#396]
When deploying Java proxy.jsp in a Oracle WebLogic server sometimes I get an HTTP 503 error saying:

Failure of server APACHE bridge:
No backend server available for connection: timed out after 10 seconds or idempotent set to OFF or method not idempotent.

I tryed to understand the issue and I found that in method fetchAndPassBackToClient(HttpURLConnection con, HttpServletResponse clientResponse, boolean ignoreAuthenticationErrors) the OutputStream was not flushed in the end.

I added the bold block of code and the problem disappear.

byte[] byteResponse = buffer.toByteArray();
OutputStream ostream = clientResponse.getOutputStream();
ostream.write(byteResponse);
**ostream.flush();**
ostream.close();
byteStream.close();

Maybe it's a good idea to solve this in future releases.

Thanks for your work.

**Comment by bsvensson** [comment]
@tiagorodriguesribeiro 
Strange.  The close() should automatically flush the [OutputStream](https://docs.oracle.com/javase/8/docs/api/java/io/OutputStream.html#flush--) .  However, in reality ( [1](http://stackoverflow.com/questions/9858495/using-flush-before-close) [2](http://stackoverflow.com/questions/31456660/fileoutputstream-does-the-close-method-calls-also-flush) [3](http://stackoverflow.com/questions/2732260/in-java-when-i-call-outputstream-close-do-i-always-need-to-call-outputstream) [4](http://www.javapractices.com/topic/TopicAction.do?Id=8) ) it seems less certain.

Do you want to make a pull request for this fix (to get the street cred for it)?  (If not, I can add the the fix)?

**Comment by claywinkler** [comment]
Bjorn, are you saying that close() is failing to invoke flush()?

**Comment by bsvensson** [comment]
@claywinkler - according to the issue description @tiagorodriguesribeiro is running in to an issue, possibly only specific to Oracle WebLogic and server APACHE bridge.   Even though I'm not 100% sure that's really the issue, I don't think there's any drawback to adding the `flush()`...

**Comment by tiagorodriguesribeiro** [comment]
@bsvensson you can add the fix. @claywinkler my experience says that some implementations have flush before close, other's don't. I'm using Oracle WebLogic installed locally on my computer and I don't have any problem. Using Oracle WebLogic on client servers I have this problem... In past implementations the proxy.jsp had this flush + close. After some versions this disappeared.

**Comment by amit78g** [comment]
We're using Weblogic server version 12.1.3.0.171017 and we're getting issues on it. Which version should we revert back to?

**Comment by neilbissonnette** [comment]
Where is this file located and how do you change it?  I tryed to understand the issue and I found that in method fetchAndPassBackToClient(HttpURLConnection con, HttpServletResponse clientResponse, boolean ignoreAuthenticationErrors) the OutputStream was not flushed in the end.

I added the bold block of code and the problem disappear.

byte[] byteResponse = buffer.toByteArray();
OutputStream ostream = clientResponse.getOutputStream();
ostream.write(byteResponse);
**ostream.flush();**
ostream.close();
byteStream.close();
