### ISSUE TITLE
DotNet Proxy HTTP Request Error #2032

### ISSUE THREAD

**Issue by ClaudiaGallegos** [Esri/resource-proxy#397]
I've confirmed that my proxy page is configured and working correctly, as I can ping it and access secured services on other servers.

However, when I try to access secured services on my own server, I get the error:

Exception Details: System.Net.WebException: The remote name could not be resolved: 
[WebException: The remote name could not be resolved: ]
   System.Net.HttpWebRequest.GetResponse() +8420880
   proxy.doHTTPRequest(String uri, Byte[] bytes, String method, String referer, String contentType, NetworkCredential credentials) in c:\inetpub\wwwroot\DotNet\proxy.ashx:474
   proxy.doHTTPRequest(String uri, String method, NetworkCredential credentials) in c:\inetpub\wwwroot\DotNet\proxy.ashx:449
   proxy.getNewTokenIfCredentialsAreSpecified(ServerUrl su, String reqUrl) in c:\inetpub\wwwroot\DotNet\proxy.ashx:532
   proxy.ProcessRequest(HttpContext context) in c:\inetpub\wwwroot\DotNet\proxy.ashx:256
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +913
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34274 
ArcGIS Server 10.3.1, Windows Server 2012, IIS 8

I followed all instructions when I downloaded the most recent proxy page. 

I'm attempting to secure a legacy compiled Flex Viewer 3.2 that I just need to get migrated to our new server and secured to avoid a break in service. I downloaded the source code for the 3.2 compiled viewer (in case the .swf file was corrupt), and I get the same errors when linking it to my proxy page. 

I also confirmed that my rest page is available and the credentials in my proxy page are correct.

My applications can consume unsecured services from my server just fine; the problem is when I enable ArcGIS Server security.

I believe there are permissions with my server that need to be set so the proxy page can see my server's rest page.

**Comment by esoekianto** [comment]
@ClaudiaGallegos can you check weather the web server where the proxy is hosted can access the remote URL? 
you can try by opening the URL in web browser inside the server.

**Comment by ClaudiaGallegos** [comment]
No, I can't: "This page cannot be displayed" error.

**Comment by ClaudiaGallegos** [comment]
Looks like a DNS error.

**Comment by esoekianto** [comment]
@ClaudiaGallegos yep, so thats it! the web server can access the remote URL, thats why you are getting that error from the proxy.

**Comment by ClaudiaGallegos** [comment]
Aha! So not a proxy error. I did my part right. I'll start working with my IT folks on this.

Thanks!
