### ISSUE TITLE
Dotnet - Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by roemhildtg** [Esri/resource-proxy#399]
Any idea what's going on here?

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34209 

I have the proxy application set up and configured to use ASP.NET v4.0. I am hitting a url like this:

`https://apps.myapps.com/proxy/proxy.ashx?https://apps.myapps.com/arcgis/rest/services`

Server Error in '/ags_proxy' Application.
The request was aborted: Could not create SSL/TLS secure channel.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

Source Error:

```aspx
Line 490:            if (bytes != null && bytes.Length > 0)
Line 491:                req.ContentLength = bytes.Length;
Line 492:            using (Stream outputStream = req.GetRequestStream()) {
Line 493:                outputStream.Write(bytes, 0, bytes.Length);
Line 494:            }
```

Source File: c:\inetpub\wwwroot\ags_proxy\proxy.ashx    Line: 492

Stack Trace:

```
[WebException: The request was aborted: Could not create SSL/TLS secure channel.]
System.Net.HttpWebRequest.GetRequestStream(TransportContext& context) +1176
System.Net.HttpWebRequest.GetRequestStream() +23
proxy.doHTTPRequest(String uri, Byte[] bytes, String method, String referer, String contentType, NetworkCredential credentials) in c:\inetpub\wwwroot\ags_proxy\proxy.ashx:492
proxy.doHTTPRequest(String uri, String method, NetworkCredential credentials) in c:\inetpub\wwwroot\ags_proxy\proxy.ashx:470
proxy.getNewTokenIfCredentialsAreSpecified(ServerUrl su, String reqUrl) in c:\inetpub\wwwroot\ags_proxy\proxy.ashx:565
proxy.ProcessRequest(HttpContext context) in c:\inetpub\wwwroot\ags_proxy\proxy.ashx:257
System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +913
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +165
```

**Comment by roemhildtg** [comment]
I should also note, I'm running Windows Server 2008 R2 Service pack 1, 64bit.

**Comment by esoekianto** [comment]
@roemhildtg in my experience, it looks like the remote server SSL certificate is not listed as trusted certificates on the web server where the proxy is hosted. 

Can you try browsing the remote URL (``https://apps.myapps.com/arcgis/rest/services``) in the browser on the web server where the proxy is hosted ? You should see in the browser that the SSL certificate is not trusted. 

Also if you can try whether the same issue occurs when you proxy the same URL in HTTP instead of HTTPS

Hope this helps.

**Comment by roemhildtg** [comment]
That's correct. The arcgis (remote) server does not have a valid ssl certificate. The reason is it is not a publicly accessible server, we're using web-adapter to allow external access. Using HTTP instead of HTTPS doesn't work either since the service we're accessing is secured with arcgis credentials. The proxy script is forced to use HTTPS since it needs to acquire an access token. 

In the example urls above, https://apps.myapps.com/arcgis/rest/services is the url to our web adapter.

**Comment by roemhildtg** [comment]
Just a follow up, the url  https://apps.myapps.com/arcgis/rest/services does have a valid certificate. It is the internal arcgis server that does not. But that shouldn't matter since web adapter is being used, correct?

**Comment by roemhildtg** [comment]
Apparent fix is to change: 
```aspnet
 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```
to
```aspnet
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;
```

I realize this isn't "secure" but since we're accessing an internal server there shouldn't be an issue, right?

**Comment by steenhulthin** [comment]
I see 2 solutions, either require .net 4.5 or change to SecurityProtocolType.Tls11.

**Comment by bsvensson** [comment]
> I see 2 solutions, either require .net 4.5 or change to SecurityProtocolType.Tls11.

Thanks @steenhulthin for summarizing that.    

@esoekianto @jgravois - what do you think? Seems like neither solution is great... (I'm leaning towards the#406 solution -> thus changing the minimum requirement to .NET 4.5)

**Comment by esoekianto** [comment]
@bsvensson 
Can we have the best of the both world by somehow having this (security protocol type) as an option that you can be configured in config file?

**Comment by bsvensson** [comment]
... or maybe use feature detection to pick TLS1.2 when possible.

**Comment by esoekianto** [comment]
while working with few customers who faced the same issue, this seems to work all the time, 

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;

I can create PR for this @bsvensson, if we agree that this is how we want to fix this issue

**Comment by bsvensson** [comment]
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;

We should use TLS 1.2 whenever possible (for better security).

@esoekianto - If a user has a server that supports TLS 1.1 and TLS 1.2, and uses .NET 4.5, doesn't your suggestion mean they end up with the less secure TLS 1.1?

If we can't use feature detection, then your earlier suggestion about an option in the config file might be the better option. :)

**Comment by nicogis** [comment]
yes, also because there are server set in hsts

**Comment by Shadow997** [comment]
When that error appears, it's because you have a version that is not .Net Framework 4.6.1 or higher, or because the website you want to open using ssl method is not an https one, but probably an http.

**Comment by Shadow997** [comment]
oof

**Comment by bsvensson** [comment]
Closing issue.

Microsoft [ended support for .NET 4.0](https://en.wikipedia.org/wiki/.NET_Framework_version_history) (as well as for 4.5 and 4.5.1) back on 2016-01-12.
