### ISSUE TITLE
www-authenticate header?

### ISSUE THREAD

**Issue by simongis** [Esri/resource-proxy#400]
We have a client who is using the Java proxy in a portal 10.4.1 (federated with Server) implementation.

They have created a simple app with the Developer Edition of Web AppBuilder which has been registered with the Portal, AppID included, setup the **Java Proxy** with the secret, the app is accessing Web Map & content in the portal  that has been shared to Everyone (so to not breach the terms of use of App Logins).  The proxy is behaving as expected, and requests via a browser work as expected.

The app is being hosted in a separate domain to the portal - hosted in [Pega](https://pdn.pega.com/).  The app communicates to the internal portal through Netscaler and this is where the proxy then fails to work.

Citrix ruled that they need the requests from the proxy to include the [WWW-Authenticate header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2).   I have checked on my own deployment and can see that this indeed is missing when making requests through the proxy (screenshot is actually the .NET proxy) 

Q1. Any particular security reason why we do not include this header?

Q2. Any ideas on what would need to be modified in the proxy to enable this?

Q3. Should the header be: _WWW-Authenticate: Basic_

![image](https://cloud.githubusercontent.com/assets/2769383/20915428/e95b6a96-bbd9-11e6-9bcf-dd7b03868a4d.png)

**Comment by bsvensson** [comment]
> Q1. Any particular security reason why we do not include this header?

@jakc - It's most likely a bug in the proxy. For java proxy, I thought it was fixed as part of #164 but maybe not completely.  We also have open issue #175 about forwarding request headers (with an open PR for DotNet).

_"Proxies MUST be completely transparent regarding user agent authentication by origin servers. That is, they must forward the WWW-Authenticate and Authorization headers untouched..."_ (from http://www.ietf.org/rfc/rfc2617.txt)
