### ISSUE TITLE
PHP proxy returns 500 error when using PHP 7.1

### ISSUE THREAD

**Issue by dannyboycurtis** [Esri/resource-proxy#402]
There appears to be an issue with the PHP proxy when using PHP 7.1.

Calls to map services through the proxy returns a 500 error.  I confirmed that PHP 7.0 does work.
Specifically, I tested this with PHP 7.1.0 and PHP 7.0.12.

**Comment by wadesherman** [comment]
Check out my [pull request](https://github.com/Esri/resource-proxy/pull/401/files) - changing that one line got this library working in 7.1 for me.

**Comment by wadesherman** [comment]
Oh just kidding, I am using 7.0

**Comment by ELepolt** [comment]
Ran into this same issue. 7.1 doesn't allow mismatched arguments.

So there's a line that says

    $this->proxyGet();

That calls a function:

    function proxyGet($url)

And that's throwing an error. So replace that first line with:

    $this->proxyGet(null);

And you should be fine. There are other functions like this too. 7.1 is going to cause a fair amount of issues with this, I think. For the better.
