### ISSUE TITLE
Invalid token error with .NET proxy

### ISSUE THREAD

**Issue by nateshaub** [Esri/resource-proxy#403]
Hello,

I recently spent a decent amount of time troubleshooting a mysterious "invalid token" error that I was getting sporadically with one of my applications that accesses a secure service on our ArcGIS Server using the .NET proxy.  I set up a scheduled task that opened the application every fifteen minutes and found that at the 75 minute mark I would consistently receive the invalid token error.  To make my testing a little more manageable, I modified the expiration parameter in proxy.ashx to two minutes, scheduled my test for every five minutes and I was able to replicate the issue repeatedly.  I then discovered that if I set the recycling frequency for the application pool that the proxy is running within to one minute, the invalid token error vanished.

I've reset my proxy.ashx to retrieve a 60 minute token, set the recycling frequency for the proxy application pool to 45 minutes and am no longer experiencing the issue.  However, I'm still curious WHY this was happening.  In my limited understanding of how the proxy works, a retrieved token is stored in the application scope and this scope is checked each time a request is made to see if a token is already there.  Recycling the application pool makes sure that the token that is in the application scope isn't there past its expiry; however, wouldn't the proxy retrieve a new token when it was determined that the token in the application scope was expired?  I'm not sure if this is an issue with the proxy or possibly something with IIS 8.5 ... I want to make sure that I'm not simply applying a band-aid to another problem.

Cheers,
Nate Shaub

**Comment by jgravois** [comment]
hi @nateshaub! i think we're already tracking this in #338...

**Comment by nateshaub** [comment]
Sorry, should have checked the open issues first!  This is exactly what I was seeing, thanks.

Nate Shaub
Senior GIS Programmer-Analyst
City of Tigard
(503) 718-2661
nathans@tigard-or.gov

**Comment by jgravois** [comment]
no worries at all. our open issues are a bit of a rat's nest.
