### ISSUE TITLE
Send post to  Java proxy.jsp get java.io.EOFException error

### ISSUE THREAD

**Issue by JackBaoL** [Esri/resource-proxy#404]
I use identifytask to query features,where gemetrytype is polygon and point all is well,but  until I have geometries with data that is large,such as circle. This causes the request to use a POST instead of GET.Then I get java.io.EOFException error.

![image](https://cloud.githubusercontent.com/assets/24949781/21711693/35985f9a-d42b-11e6-9235-700962f47a77.png)

```java
private byte[] readRequestPostBody(HttpServletRequest request) throws IOException{
int clength = request.getContentLength();
if(clength > 0) {
byte[] bytes = new byte[clength];
DataInputStream dataIs = new DataInputStream(request.getInputStream());

dataIs.readFully(bytes);
dataIs.close();
return bytes;
}

return new byte[0];
}
```

I debug proxy.jsp,   dataIs.readFully(bytes)   cause error,I use querytask,it has same issue.

**Comment by cwang2002** [comment]
I am having the same issue. Did you resolve it?

**Comment by youngInnovator** [comment]
I am also facing the same issue.
