### ISSUE TITLE
Does the Java proxy handle HTTP 302 (URL redirect)?

### ISSUE THREAD

**Issue by mathiasdahl** [Esri/resource-proxy#408]
Hi,

I am trying to use the Java proxy to connect to private services on ArcGIS Online. In the proxy config file I have added the required username and password required to access my service. The end result is that I get back a small HTML page with Token required in it, if I test the proxy via my web browser. I have debugged the proxy heavily and found out that it correctly generates tokens from the server, and those tokens work if I add them manually to an URL and use the resulting URL in a web browser. However, when the resulting URL is used inside the proxy to connect, it does not work all the way.

I finally installed Wireshark to see what differs between the request done by the web browser and by the proxy, and the difference I see is that the web browser seem to follow the HTTP 302 (URL redirect) that the server responds with. The proxy does not seem to do that.

Could this be the cause of my problem? Am I using the proxy the wrong way?

Here are the contents of my proxy config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
logFile="c:/proxy.log"
logLevel="DEBUG"
mustMatch="true">
<serverUrls>
<serverUrl url="http://services.arcgis.com" matchAll="true" username="secretuser" password="secretpassword"/>
</serverUrls>
</ProxyConfig>
```

Thanks!

/Mathias

**Comment by weituotian** [comment]
Yeah! I have the same problem about how to change web browser url
