### ISSUE TITLE
Response Body for HTTP 4xx Errors

### ISSUE THREAD

**Issue by djrpascu** [Esri/resource-proxy#410]
Currently, the proxy returns HTTP 400 errors as exceptions and doesn't pass the body back to the client. Would it make sense to return all responses so that we might be able to get details on the errors passed back?

**Comment by esoekianto** [comment]
@djrpascu is the proxy returning the HTTP 400 error? or is the arcgis server or online returning the error 400 thru the proxy?

**Comment by djrpascu** [comment]
i'm testing it with a simple call to a .net web api service that returns validation error messages in a 400 (Bad Request) if data passed in is invalid. the web api service is returning the 400 to the proxy with json data of error messages, but the proxy only sends the status code 400 (Bad Request) to the client.

**Comment by MichaelRH** [comment]
Getting a similar issue that started today. Has anyone changed their cert recently? That's the only thing different on my application server from yesterday.

Troubleshot the issue with an Esri tech for about an hour and found that it wasn't the ArcGIS Server hosting our REST services (still work in many other apps via different hosting machines) and wasn't ArcGIS Online (the same web map and web apps built on the same REST services work on ArcGIS Online). Seems like the issue is with the proxy and the application or the application server but I don't have a solution yet.

Also getting the 400 Bad Request error when hitting the proxy directly.

**Comment by bsvensson** [comment]
@djrpascu - which proxy are you using?

When I tested `https://httpbin.org/status/418` as a simple test case, it seems to work in all three proxies.  The DotNet displays it 100% correct, while Java and PHP have newline issues in the browser but at least shows the content.

```
C:\test>curl https://httpbin.org/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`

C:\test>curl http://localhost/resource-proxy/PHP/proxy.php?https://httpbin.org/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
```
In your case, what does `curl` and `curl --verbose` show?

**Comment by djrpascu** [comment]
@bsvensson I'm using a release version of the .net proxy, I'll need to find exactly what version (mobile at the moment).. I think it has to do with an exception being thrown on the 400 instead of the serverResponse getting set as it would if a 200 came back.. I confirmed that I can see the error messages in from my Web api response in the body if I return it as a 200..

**Comment by djrpascu** [comment]
@bsvensson i'm using version 1.1.0 of the .NET proxy. When I test with your endpoint (https://httpbin.org/status/418) using Fiddler, I get the following:

HTTP/1.1 418
Cache-Control: private
Content-Type: text/html
Server: Microsoft-IIS/8.5
Access-Control-Allow-Origin: *
x-more-info: http://tools.ietf.org/html/rfc2324
Access-Control-Allow-Credentials: true
Server: nginx
X-AspNet-Version: 4.0.30319
MicrosoftOfficeWebServer: 5.0_Pub
X-Powered-By: ASP.NET
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Date: Tue, 28 Feb 2017 18:33:05 GMT
Content-Length: 54

The custom error module does not recognize this error.

**Comment by djrpascu** [comment]
ok i figured this out... sorry, it wasn't the proxy after all..

i'm on IIS 8.5. apparently, IIS strips the response body for errors.. need to add the following to your Web.config get the errors to "pass through":

<httpErrors existingResponse="PassThrough"></httpErrors>

Note: Add to the <system.webServer> section.
