### ISSUE TITLE
Querying the root catalog returns empty services array

### ISSUE THREAD

**Issue by maouida** [Esri/resource-proxy#411]
I'm using the .NET proxy to query the services installed on my account:
I've correctly added the credentials in the config file.

`http://myapplication.com/ArcGISProxy.ashx?https://services7.arcgis.com/xxx/arcgis/rest/services?f=json`

This returns an empty services array:

```
{
currentVersion: 10.41,
services: [ ]
}
```

But when I query a specific service, it works correctly.

`http://myapplication.com/ArcGISProxy.ashx?https://services7.arcgis.com/xxx/arcgis/rest/services/MY_SERVICE/FeatureServer?f=json`

Are there specific requirements to query the services list?

**Comment by garycjohnson** [comment]
Hi @maouida  .. we're looking at the same issue. I noticed you closed this off. Did you find a resolution?

**Comment by bsvensson** [comment]
@garycjohnson - are there any public services?  If there are no public services, the expected response is indeed to show `services: [ ]`. However, if there are public services, it should show those.  

If you go to a specific secured service, then the proxy should use the appropriate credentials.
