### ISSUE TITLE
Update proxy to support ArcGIS Runtime clients

### ISSUE THREAD

**Issue by rexhansen** [Esri/resource-proxy#414]
Currently, ArcGIS Runtime SDKs version 10.2.x and 100.0 do not work with the resource proxy if parameters are added by a Runtime API (which is common).  Note, Runtime SDKs do work with the utility proxy hosted by ArcGIS Online or an on-premise Portal.  

Using the .NET resource proxy as an example, here is a comparison between JavaScript API and Runtime APIs.  Note, the use of characters ? and &:

**JavaScript:** 
User defined in code:

```
esriConfig.defaults.io.proxyUrl = "http://eloy.esri.com/resourceproxy/net/proxy.ashx"
esriConfig.defaults.io.alwaysUseProxy = true;
var dynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer(http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer);
```
With proxy, actual url sent by API (two ?): http://eloy.esri.com/resourceproxy/net/proxy.ashx?http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer?f=json&dpi=96&transparent=true&format=jpeg&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

>Valid response returned. 
 
Without proxy, actual url sent by API (one ?):  http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer?f=json&dpi=96&transparent=true&format=jpeg&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

>Valid response returned.

**Runtime (tested .NET and Android):**
With proxy, user defined url in code (one ?):  http://eloy.esri.com/resourceproxy/net/proxy.ashx?http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer
Actual url constructed and sent by API (one ? and one &): http://eloy.esri.com/resourceproxy/net/proxy.ashx?http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer&f=json   

> Url is valid as the ? defines the beginning of a query params, but fails in resource proxy source code.  Bad request error returned.   

Without proxy, user defined url in code: http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer
Actual url constructed and sent by API (one ?): http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Population_World/MapServer?f=json

> Valid response returned.  

There are a couple options: 
1)  Change the resource proxy source code to account for the ? and & discrepancy.  This may involve a simple or pervasive change.  
Pros: Works for 10.2.x and 100.x Runtimes, and JavaScript keeps working.    
Cons: Requires a change to resource proxy source code, which will may be significant.  JavaScript will need to retest. 

Example of a simple fix to the existing resource proxy (.NET) is available here:  https://github.com/Esri/resource-proxy/pull/413 

2)  Change 100.x Runtime to ignore ? in layer/task url.
Pros: No change to resource proxy source code because Runtime should match what JavaScript does.  No extra testing for JavaScript.   
Cons: 10.2.x Runtime will not work with resource proxy.  May break use of other proxy services (eg AGOL/Developers which work today).   A simple, yet fairly pervasive change, it needs a lot of Runtime testing.  Technically the url being constructed by the Runtime is correct.   

3) Create another “Runtime” proxy in the resource-proxy repo
Pros:  Designed for explicit Runtime use.    
Cons:   Additional source to maintain.   In addition, there will be two proxies side by side, which may be confusing.

**Comment by esoekianto** [comment]
@rexhansen how about we add another property (parameter) in the configuration page (proxy.config), for example runtime=true, then additional code for runtime will be executed. 

@bsvensson  what do you think? to make sure that we are not breaking any request from  JS API, WAB, local govt template.

**Comment by dasa** [comment]
Another option could be to add support for an encoded `url` query parameter.

**Comment by LeoyangUp** [comment]
Hi everyone! We have been confront with some problem.
We have succeed in JS API via proxy(.NET).
Now we try to test it in mobile API(iOS&Android).
As we know,no related API defined in 10.2.x Runtime,we failed in testing all the time.
Can you show me some example code about this issue?
We need your help,thanks!
