### ISSUE TITLE
Request is Forbidden

### ISSUE THREAD

**Issue by Engineerumair** [Esri/resource-proxy#416]
I use Dot net proxy in my IIS server to request usgs earthquake xls file

but I get the following error

http://myip:myport/Proxy/?http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.csv 403 (Forbidden)

**Comment by dgwaldo** [comment]
A little more information would be nice, hard to take any action on this with so little information. Have you attached a debugger to the proxy.ashx file?
