### ISSUE TITLE
Some markdown headers broken

### ISSUE THREAD

**Issue by andygup** [Esri/resource-proxy#417]
Minor documentation issue - easy to fix. In the various readme files some of the markdown headers are broken. Github changed how they parse markdown headers.

The pattern ##xyz with no spacing between the header hastag and the title no longer works. These all need to be replaced with the pattern ##[space]xyz, e.g. ## xyz.

Example: scroll down just a little bit from this [header](https://github.com/Esri/resource-proxy/tree/master/PHP#when-i-ran-the-verification-test-my-browser-displays-raw-php-code) in the PHP readme to the header called "###PHP version check has failed". Also note "##Issues", "##Contributing" and "##Licensing".

**Comment by jgravois** [comment]
> easy to fix

PRs welcome! 😄

**Comment by bsvensson** [comment]
Fixed on https://github.com/Esri/resource-proxy/tree/master and https://github.com/Esri/resource-proxy/tree/master/PHP.
