### ISSUE TITLE
Corrupted XLSX output when geoenrichment report request is submitted through a proxy

### ISSUE THREAD

**Issue by ChristofKatsa** [Esri/resource-proxy#418]
The request below will succeed and generate an XLSX report which will however be corrupted:

http://artemisfl.esri.com/dotnet/proxy.ashx?https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/GeoEnrichment/CreateReport?studyAreas=%5B%7B%22geometry%22%3A%7B%22x%22%3A-9599789.42447999%2C%22y%22%3A3817822.853801482%7D%7D%5D&report=business_loc&format=xlsx&studyAreasOptions=%7B%22areaType%22%3A%22RingBufferBands%22%2C%22bufferUnits%22%3A%22esriMiles%22%2C%22bufferRadii%22%3A%5B2%5D%7D&f=bin&inSR=102100

When you open the generated output:

"We found a problem with some content in "2010 Census Profile (4).xlsx.Do you want us to try to recover as much as we can?"
-Click Yes : This errors as "The file is corrupt and cannot be opened"

If we remove the proxy and append an ArcGIS Online token this works with no issues, so this seems to be a proxy issue.

https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/GeoEnrichment/CreateReport?studyAreas=%5B%7B"geometry"%3A%7B"x"%3A-9599789.42447999%2C"y"%3A3817822.853801482%7D%7D%5D&report=business_loc&format=xlsx&studyAreasOptions=%7B"areaType"%3A"RingBufferBands"%2C"bufferUnits"%3A"esriMiles"%2C"bufferRadii"%3A%5B2%5D%7D&f=bin&inSR=102100&token=UF-ot1VntmIsh6smqTaRAcpaZIEbnBSmUuUChiFidwy2_JE07d9UjEuL9Lf6XLuBHHCLYTtSj9GjrfLhmEYHiEOmUIutq9fMlaTBuAkOgxziewXFEHdQlCZgX1MGuValzN_Ovu37sv5EWzkyjADpKg..

**Comment by bsvensson** [comment]
It seems to work fine if you set `format=pdf`...
Does both formats work with php/java?

**Comment by ChristofKatsa** [comment]
Thanks for the quick follow up. That is correct, for format=pdf it works fine. 
This has not been tested with php/java yet.
