### ISSUE TITLE
PHP Proxy error on test service

### ISSUE THREAD

**Issue by ves-krd** [Esri/resource-proxy#419]
proxy_log.log:
`Can not determine if OAuth or ArcGIS Server means of authentication.  Check config for errors.`

PHP proxy is on a MAMP instance
`http://localhost:8888/PHP/proxy.php?http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson`

Any ideas?

**Comment by aicelm** [comment]
@ves-krd  You can try checking the credentials that you have configured in your proxy.config file.

**Comment by kevwu** [comment]
I was able to work around this issue by rewriting my configuration in JSON rather than XML.

I'm on PHP 5.6.30.
