### ISSUE TITLE
Invalid Token error while accessing World_Topo_Map

### ISSUE THREAD

**Issue by gmeena** [Esri/resource-proxy#422]
I am trying to access ArcGIS Online Map using web builder generated app hosted on own servers.

I am getting below error
```
code:498
details:[]
message :"Invalid Token"
```
while app hits url
https://***/arcgisdev/proxy.ashx?https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer?f=json

Please help

Thanks

**Comment by esoekianto** [comment]
@gmeena 

https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer?f=json

This map service is shared publicly, you don't you even need use proxy for this map service (for token/security purpose)

**Comment by gmeena** [comment]
@esoekianto : Thanks, I later realised this.
