### ISSUE TITLE
Credentials are not being passed in encoded format

### ISSUE THREAD

**Issue by bchad** [Esri/resource-proxy#424]
I was working w/ a mutual client yesterday evening & this morning - SUEZ (their Long Island division) - configuring the Esri Resource Proxy.
 
That way they could access their secured GIS Services w/o getting the Esri credential prompts - as Esri is hosting both a staging & production ArcGIS Server 10.5 environment for them federated w/ Portal for ArcGIS.
 
I did the staging configuration a couple of weeks ago & all went smoothly.
 
I had the same sort of configuration set up across the line for the production configuration yesterday evening, as they were ready to move from staging to production, but it was not working & had me really perplexed.
 
I came back in this morning & looked at the password for the user in the proxy.config for the Esri Resource Proxy - b/c I had noticed some unusual characters in it the night before & made some notes to further investigate.
 
As such, I went ahead & encoded the password for the user in the proxy.config for the Esri Resource Proxy - then tried things & they worked previously, where before they had failed.
 
I traced this down using the developer tools in the browser - then had one our developers come in behind me just to confirm the results…
 
Esri is not passing those credentials in the Resource Proxy in an encoded fashion - so if & until that changes, it’s ultimately up to us as consumers to be aware that we may need to encode them ourselves.
 
In this case, the original password was 98%EUmVkqPdXJ1N0V^IN - the encoded password that works is 98%25EUmVkqPdXJ1N0V%5EIN.
 
So % was encoded to %25 & ^ was encoded to %5E.
 
Password/text randomizers are great for generating very secure credentials - but watch out for those special characters.

**Comment by bsvensson** [comment]
Thanks for reporting on your proxy experience @bchad .  Which one of the three proxies did you use?

**Comment by bchad** [comment]
Bjorn:

Thanks for asking - sorry I did not specify - we use the DotNet version b/c it matches our development platform.

Thanks,





Bryan A. Chadwick, GISP
 
System Architect | Public Asset Management Team
 
(801) 523-2751 ext 1903 office | (321) 304-7477 mobile
 
www.cityworks.com <http://www.cityworks.com/> | bchadwick@cityworks.com <http://www.cityworks.com/>
 

Empowering GIS® for Public Asset Management
A reflection of our innovative, GIS-centric design, Cityworks | Azteca Systems, LLC is now a Representative Vendor in the Gartner® 2015 Market Guide for North American Local Government IT Solutions! To learn more, check out Cityworks InSights <http://www.cityworks.com/cityworks-gartner/>.
This email and any included files are intended for the exclusive use of the individual(s) to whom it is addressed and may contain information that is proprietary, privileged and/or confidential. If you are not an intended recipient, please notify the sender and delete the message immediately. Unauthorized viewing, copying, disclosure or distribution is subject to legal restriction and penalty.
