### ISSUE TITLE
proxy with url ampersand parameters

### ISSUE THREAD

**Issue by dbusses** [Esri/resource-proxy#425]
Using the DotNet proxy, passing any url with an ampersand ('&') gets a parsing error for the entire proxy file:
http://www.example.com/?utm_source=adsite&utm_campaign=adcampaign&utm_term=adkeyword

The ampersand is an escape character in XML. 
Workaround:
Substitute any ampersand ('&') in the proxy.config file with the value `&#038;`

**Comment by bsvensson** [comment]
Hi @dbusses 

I think this is a "feature" of XML in general.

See e.g. http://support.esri.com/technical-article/000005870 or https://www.google.com/search?q=characters+in+xml+that+need+to+be+escaped
