### ISSUE TITLE
url rewrite help

### ISSUE THREAD

**Issue by dbusses** [Esri/resource-proxy#426]
I am using the proxy for a 3rd party app.

I have the proxy working in a browser, but the 3rd party app is appending the proxy url:
`?request=GetCapabilities&SERVICE=WMS&version=1.3.0` 

I need to append a token to that URL (i.e. `&token=xxx`)
any thoughts?

**Comment by esoekianto** [comment]
@dbusses you can try something similar to setrequestprecallback in ArcGIS Javascript API
https://developers.arcgis.com/javascript/3/jsapi/esri.request-amd.html#esrirequest.setrequestprecallback

**Comment by bsvensson** [comment]
@dbusses 
- is the 3rd party app using the ArcGIS API for JavaScript? If so, which exact version?
- which proxy are you using?

**Comment by dbusses** [comment]
The 3rd party app is not built on ArcGIS API for JavaScript.

I'm using the DotNet proxy.

**Comment by bsvensson** [comment]
@dbusses - there's no support in the proxies for adding token to URLs.

For your specific case, you could either implement support for a new property to the proxy.config, or maybe easier if this is just for one specific case, just add an `if` statement, maybe near the ` //if url is encoded, decode it.` comment.
