### ISSUE TITLE
PHP - Error json response with PHP 7.1

### ISSUE THREAD

**Issue by aicelm** [Esri/resource-proxy#427]
Hi,
I have a problem with the response of the request.
The GET request and the proxy works, but it does not return the json on Network(Chrome) or on the screen.

I’m using php version 1.1.1-beta and the configuration of proxy.config:
```
 <serverUrl url="route.arcgis.com"
        clientId=".."
        clientSecret=".."
        matchAll="true" />
```

My code is: 
```
      var routeTask = new RouteTask({
        url: "https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World/"
      })
```
[Click here to find the complete code](https://github.com/aicelm/proxy-route/blob/master/index.html)

In proxy_log_json.log it returns me,

>  | GET detected
>  | Using session token

Please, take into consideration that my colleague has found that same configuration works for him.

Previously, I had an error related with the credentials. It could be interesting to include a particular error message of it.

Thanks for you time and attention!

**Comment by bsvensson** [comment]
> Please, take into consideration that my colleague has found that same configuration works for him.

@aicelm - Strange, are you sure there isn't some difference between the machines? Webservers? php versions? proxy.configs?

**Comment by aicelm** [comment]
We both write the same URL, like that:
`//localhost:port/PHP/proxy.php?https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World/?f=pjso`

Then, I do not get any response and his machine shows it on json. 

The machine are not the same. We use the port of our Apache, but php version and proxy.config are the same.

Thanks!

**Comment by hhkaos** [comment]
Hi Bjorn!,
Sorry we didn't check our PHP versions. But she is right about the configuration. What is weird to me is the log, my log is a little bit different:

```
05-22-17 19:44:21 | GET detected
05-22-17 19:44:21 | Using session token
05-22-17 19:44:24 | Resource using OAuth
05-22-17 19:44:27 | Exchanging portal token for server-specific token for https://route.arcgis.com
05-22-17 19:44:29 | Adding token to session
```

We will check tomorrow her PHP version and also the Apache log in order to see if there is something broken there.

Thanks in advance.
Raul

**Comment by aicelm** [comment]
Well, we've been comparing the versions and this is the result:

||@aicelm|@hhkaos|
|---|---|---|
| Machine | Window | Mac |
|PHP Version| 7.1.1 | 7.0.15|
|Apache Version| 2.4 | 2.2|
|Curl| 7.51.0 | 7.52.1|

We have been doing manually debbuging in **proxy.php** and we have added a code line before the function (before get and after get) in order to find the error position:
Code's lines go from row 870 to row 876
 
  ```
 }else if($this->proxyMethod == "GET"){

            $this->proxyLog->log("Before Get");
            $this->proxyGet();
        }

        $this->proxyLog->log("After Get");
```

We also have added a code line when it calls the function to show if it runs:
Code's lines go from row 1045 to row 1047

```
public function proxyGet($url) {

        $this->proxyLog->log("Inside Get");
        $this->response = null;

```

Checking the **proxy_log.log** file returns this:


```
05-24-17 12:42:32 | GET detected
05-24-17 12:42:32 | Using session token
05-24-17 12:42:32 | Before Get
```

Apache does not display the log file. We think the problem may be in PHP. 


Thank you so much!
Regards, Leticia

**Comment by bsvensson** [comment]
There's big differences between PHP 7.0 and 7.1 - this is probably the reason why you see different results.

See for example #402 - which has some solutions for you :)

**Comment by bsvensson** [comment]
Closing.
This was related to using PHP 7.0/7.1.  Neither of them work properly with the current proxy, but there are workarounds mentioned in several issues and PRs.    

The plan is to end support for PHP 5x and move to PHP 7.1 as a minimum requirement. See https://github.com/Esri/resource-proxy/issues/449
