### ISSUE TITLE
Not working with AGOL after July 2017 update

### ISSUE THREAD

**Issue by bchastain** [Esri/resource-proxy#429]
The proxy doesn't seem to work for non-public AGOL items any more, after this month's AGOL update. Can anyone else confirm? It gives me a "You do not have permissions to access this resource or perform this operation" error.

**Comment by bsvensson** [comment]
@bchastain - could you give some more details?  Which proxy are you using?  What's the URL you are trying, and what does the config file look like?

**Comment by bchastain** [comment]
I'm using the DotNet proxy. Any non-public AGOL url I try doesn't work. For example, a private feature service query:
https://services.arcgis.com/<ORGID>/arcgis/rest/services/<SERVICENAME>/FeatureServer/0/query?where=1%3D1&outFields=*&f=pjson

If I request that URL directly, it gives a "Token Required" error, as expected with a private service. However, if I try to use a proxy:
https://<SERVERNAME>/gp_proxy/proxy.ashx?https://services.arcgis.com/<ORGID>/arcgis/rest/services/<SERVICENAME>/FeatureServer/0/query?where=1%3D1&outFields=*&f=pjson

It used to provide the results, but now it gives a "You do not have permissions to access this resource or perform this operation." error. I have the correct username/password for an AGOL account with administrator privileges saved in the proxy config file.

**Comment by bchastain** [comment]
Nevermind, my config file had gotten corrupted somehow. Thanks
