### ISSUE TITLE
Using JAVA resource-proxy in Third Party Map

### ISSUE THREAD

**Issue by jawendell** [Esri/resource-proxy#430]
I have developed a web map using OpenLayers, a Javascript API.  I would like to use the resource proxy on my web site, so that I can use an ESRI web service in my map.  Is it possible to use the JAVA version of the resource proxy in this way?

**Comment by bsvensson** [comment]
I don't see why not.

@jgravois ?

**Comment by jgravois** [comment]
our proxies aren't picky so you should definitely be able to use them to make requests to OGC services in an OpenLayers app.
