### ISSUE TITLE
Clarify support options - using SUPPORT.md

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#431]
Create SUPPORT.md to take advantage of new github functionality.  See https://github.com/blog/2400-support-file-support and https://help.github.com/articles/adding-support-resources-to-your-project/ for details.

#### Maybe something like the below:

If you need support for the resource-proxy,  you can:
* Review [existing resources](https://github.com/Esri/resource-proxy/wiki).
* Search [existing issues](https://github.com/Esri/resource-proxy/issues/), both open and closed.
* [Create an issue](https://github.com/Esri/resource-proxy/issues/) in this repo.
* Contact [Esri support](http://support.esri.com/en/contact-tech-support) - if you're a current Esri customer.

cc: @esoekianto

**Comment by esoekianto** [comment]
sounds good!

**Comment by bsvensson** [comment]
[File](https://github.com/Esri/resource-proxy/blob/master/SUPPORT.md) added.  The support link is now available when [creating new issues](https://github.com/Esri/resource-proxy/issues/new)
