### ISSUE TITLE
Proxy passes query string values in referer header resulting in invalid tokens

### ISSUE THREAD

**Issue by lscharen** [Esri/resource-proxy#434]
Browser: Using Chrome 60.0.3112.90
JSAPI Config: esri.config.io.alwaysUseProxy = true

Description: When loading a web page that includes query parameters in the URL, requests are being passing into the proxy with the referer header containing the full application URL within the jsapi init.js script.  The referer header is not sanitized and is passed along to the ArcGIS Online generateToken endpoint unaltered.

For example, loading the URL https://my.localhost.com/app/map.html?NAME=VALUE results is the proxy sending the following request to the token endpoint

`
2017-08-15 09:18:34 Sending POST request: https://www.arcgis.com/sharing/rest/generateToken?f=json&request=getToken&referer=https://my.localhost.com/app/map.html?NAME=VALUE&expiration=60&username=*********&password=*********
`

This causes an invalid token to be generated and results in an authentication loop while trying to initialize a Web Map via the createMap utility method.

Loading the page without query parameters results in a successful load and subsequent loads with query parameters works due to the proxy caching the token.

A pull request that fixes this issue by sanitizing the referer header is available.

**Comment by bsvensson** [comment]
Looking at the code for the other two procies, it seems like JSP and PHP would have the same problem...
