### ISSUE TITLE
Integrate test tool into repo

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#440]
We need a better way to check and verify changes/PR.

See discussion on #316 for plenty of details & suggestions.

To test the three different proxies requires setting up test environments for DotNet, php, and Java. This can be a bit challenging for automatic testing.  

I'm suggesting to add a `tests` folder and within there add the existing grunt-based test harness that I have been using.

This test tool would be used before merging any PRs. It would also be useful for anyone making changes to the proxies. It would be really nice if a PR with a bug fix also contained a test to verify the fix.

Basic Workflow:
* Set up a proxy
* Update test tool with the URL of the proxy to test.
  - The test harness don't care which proxy is being tested (DotNet, php or Java). It justs sends requests and validates the response (and it's headers).
* Run the test tool: `grunt`.

**Comment by nicogis** [comment]
T11-federation-only need return code 401 (You do not have permissions to use this resource)
