### ISSUE TITLE
Web_Map_as_Json 

### ISSUE THREAD

**Issue by Ricardh522** [Esri/resource-proxy#447]
It has been mentioned that we can append the token retrieved by the proxy to each url in the webmap json before sending to AGOL.  Is this a workaround that esri supports?

**Comment by dbened-denver-water** [comment]
Hello, I am unable to use the WebMapAsJson with secure services sind the service url's embedded in the WebMapJson object do not include the token

Is there a plan for this fix or do you have a suggestion on how to write the token into the webMapJson request?
