### ISSUE TITLE
400 Error editing AGOL hosted feature service

### ISSUE THREAD

**Issue by bmoregeo** [Esri/resource-proxy#448]
Good Afternoon,

I'm trying to track down a 400 error when I add new records to a feature service in AGOL. At the moment, I have the service unsecured in AGOL. However, I plan on securing it once I figure this out. I can confirm that I am able to upload features without the proxy service.

The other service returns the following error message `"The remote server returned an error: (400) Bad Request."` 

This makes me think that the request isn't being formatted correctly by the proxy.

I'm making the following request through the proxy.

POST http://localhost:20318/proxy.ashx?https://services6.arcgis.com/{organizationAGOLKey}/arcgis/rest/services/demo_feature_service/FeatureServer/0/applyEdits&wab_dv=2.5

`f=json&adds=%5B%7B%22geometry%22%3A%7B%22x%22%3A-10688064.34915602%2C%22y%22%3A6287712.483808069%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D%2C%22attributes%22%3A%7B%22Date%22%3Anull%2C%22Location%22%3Anull%2C%22Category%22%3A5%2C%22Name%22%3Anull%2C%22Comments%22%3Anull%7D%7D%5D`

The proxy config is configured the following:
 
`<ProxyConfig allowedReferers="*" mustMatch="true" logFile="C:\inetpub\logs\LogFiles\proxy\log.txt" logLevel="4">
  <serverUrls>
    <serverUrl url="http://services.arcgis.com/" matchAll="true" />
    
    <serverUrl url="https://{organization}.maps.arcgis.com" 
               matchAll="true"
               clientId="{applicationClientID}"
               clientSecret="{applicationSecretKey}"
               oauth2Endpoint="https://{organization}.maps.arcgis.com/sharing/oauth2/"
               />
<serverUrl url="https://services6.arcgis.com/{organizationAGOLKey}"
               matchAll="true"
               clientId="{applicationClientID}"
               clientSecret="{applicationSecretKey}"
               oauth2Endpoint="https://{organization}.maps.arcgis.com/sharing/oauth2/"
               />
  </serverUrls>
</ProxyConfig>`

**Comment by esoekianto** [comment]
@bmoregeo 

Error 400 is normally returned from the ArcGIS Server or ArcGIS Online feature layer on your case, related to bad parameters. Your proxy setting seems to be fine.
