### ISSUE TITLE
End support for PHP 5.x ?

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#449]
PHP 5.6 was the last 5.x release.  It's no longer in "active" support.  However, there is still "security support until December 2018.  See http://php.net/supported-versions.php for details.

PHP 7.0 was released in 2015 (with "active" support until December 2017, and "security" support until December 2018).

We have several open isses and PRs related to code needing to be different for 5.x vs 7.0 vs 7.1.

My proposal is to make php 7.1 the minimum required version.  Currently we have:
`* PHP 5.4.2 or higher (recommended)`.

Does this need a "major" version bump? Or is enough to go from `1.1.2` to `1.2.0`?

@jgravois @esoekianto et al

**Comment by jgravois** [comment]
i'd be comfortable shipping it as `1.2.0` and calling support for PHP 7.0 a **feature** if the `<xml>` syntax of the proxy itself isn't changing.
