### ISSUE TITLE
Java  proxy : Why return HTML when get json?

### ISSUE THREAD

**Issue by laixiangran** [Esri/resource-proxy#450]
**Request URL:**
http://localhost:4200/projectStart/proxy.jsp?https://assets.agi.com/stk-terrain/world/layer.json

**Comment by bsvensson** [comment]
I don't think that's specific to the proxy.  I get the same result if I try https://assets.agi.com/stk-terrain/world/layer.json in a browser.  That agi.com service seems to return different responses based on the request headers.

Seems like that server is returning HTML for this:
```
>curl "https://assets.agi.com/stk-terrain/world/layer.json" -H "Accept: text/html" --head
HTTP/1.1 200 OK
Content-Type: text/html
...
```

While returning JSON for this request
```
>curl "https://assets.agi.com/stk-terrain/world/layer.json"  --head
HTTP/1.1 200 OK
Content-Type: application/json
...
```

**Comment by laixiangran** [comment]
@bsvensson I'm stupid, thanks for the answer
