### ISSUE TITLE
Error on node.js http-server

### ISSUE THREAD

**Issue by Giserwu** [Esri/resource-proxy#453]
Hello there!
Esri.config.defaults.io.proxyUrl is not set. "When using the arcgisapi code in the http-server folder server debug in node.js, how to configure Esri / resource-proxy in this case? @bsvensson

**Comment by jgravois** [comment]
we currently only maintain proxies that run in .NET, Java and PHP.

you can track (a lack of) progress on a Node.js proxy in #63
