### ISSUE TITLE
tokenServiceUri not implemented in proxy.ashx

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/resource-proxy#456]
The following webpage https://github.com/Esri/resource-proxy, says that the tag has an attribute name tokenServiceUri. When you use this attribute, it´s said that “If username and password are specified, the proxy will use the supplied token service uri to request a token. If this value is left blank, the proxy will request a token URL from the ArcGIS server.” When configuring a service with this attribute this does not seem to work.

Analyzing the “proxy.ashx” we see that this attribute does not seem to be used.
```
if (infoUrl != "") {
log(TraceLevel.Info," Querying security endpoint...");
infoUrl += "/rest/info?f=json";
//lets send a request to try and determine the URL of a token generator
string infoResponse = webResponseToString(doHTTPRequest(infoUrl, "GET"));
String tokenServiceUri = getJsonValue(infoResponse, "tokenServicesUrl");
if (string.IsNullOrEmpty(tokenServiceUri)) {
string owningSystemUrl = getJsonValue(infoResponse, "owningSystemUrl");
if (!string.IsNullOrEmpty(owningSystemUrl)) {
tokenServiceUri = owningSystemUrl + "/sharing/generateToken";
}
}
if (tokenServiceUri != "") {
log(TraceLevel.Info," Service is secured by " + tokenServiceUri + ": getting new token...");
string uri = tokenServiceUri + "?f=json&request=getToken&referer=" + PROXY_REFERER + "&expiration=60&username=" + su.Username + "&password=" + su.Password;
string tokenResponse = webResponseToString(doHTTPRequest(uri, "POST"));
token = extractToken(tokenResponse, "token");
}
}
```
In the Java version of the proxy: “proxy.jsp”

```
if (!infoUrl.isEmpty()) {
_log(Level.INFO, "[Info]: Querying security endpoint...");
String tokenServiceUri = su.getTokenServiceUri();
if (tokenServiceUri == null || tokenServiceUri.isEmpty()){
_log(Level.INFO, "Token URL not cached. Querying rest info page...");
String infoResponse = webResponseToString(doHTTPRequest(infoUrl, "GET"));
tokenServiceUri = getJsonValue(infoResponse, "tokenServicesUrl");
//If the tokenServiceUri does not exist, check the owningSystemUrl for token endpoint
if (tokenServiceUri.isEmpty()){
String owningSystemUrl = getJsonValue(infoResponse, "owningSystemUrl");
if (!owningSystemUrl.isEmpty()){
tokenServiceUri = owningSystemUrl + "/sharing/generateToken";
}
}
su.setTokenServiceUri(tokenServiceUri);
}
```
Could you publish a version of “proxy.ashx that does use this configuration attribute "tokenServiceUri"?

**Comment by bsvensson** [comment]
Hi @LuisRguezEsriSpain 

> Analyzing the “proxy.ashx” we see that this attribute does not seem to be used.

To me, it seems to be used:
```
string uri = tokenServiceUri + ...
string tokenResponse = webResponseToString(doHTTPRequest(uri, "POST"));
token = extractToken(tokenResponse, "token");
```

Maybe I'm missing something?

If you have a case where it doesn't work. Could you help us create a repro case?

There was also an earlier issue that might be of interested: #337

**Comment by LuisRguezEsriSpain** [comment]
I'm sure  “proxy.ashx” does not use the tokenServiceUri attribute from config file. You can see the Java version of the proxy (“proxy.jsp”). The java version uses this attribute.

Besides, you can see the class "public class ServerUrl" in the “proxy.ashx” file, that stores the configuration of tag "serverUrl". This class hasn't an attribute for tokenServiceUri and doesn't load the configuration of the tokenServiceUri attribute from proxy.config.

How can I help you create a repro case?

**Comment by bsvensson** [comment]
@LuisRguezEsriSpain - could you test with the https://github.com/Esri/resource-proxy/pull/455 pull request and see if that fixes your issue?

cc: @esoekianto
