### ISSUE TITLE
Error when I use a password containing the ampersand character

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/resource-proxy#457]
When I use a password containing the ampersand character (“&”) in "serverUrl" tag, an error is being raised like the one you can see in image attached to the case.

![errorpassword](https://user-images.githubusercontent.com/13570124/35104524-5a195646-fc69-11e7-8032-7fcc0c2a4375.png)

**Comment by MikeTschudi** [comment]
Because the password is an XML attribute, the ampersand character needs to be escaped:
```
<serverUrl url="http://geoenrich.arcgis.com/arcgis/rest/"
    username="username"
    password="pass&amp;word"
    matchAll="true">
</serverUrl>
```

But the server is rejecting this with "Invalid token", so perhaps the proxy needs to un-escape passwords before using them.

**Comment by MikeTschudi** [comment]
The proxy is escaping the password. A colleague pointed out to me that the geoenrichment service may not accept password characters such as the ampersand. I re-escaped the ampersand, but I still get "Invalid token"

**Comment by bsvensson** [comment]
There's an earlier related ampersand issue for this too - https://github.com/Esri/resource-proxy/issues/425

**Comment by tchapin** [comment]
I would add to this in addition to ampersand (&), the characters percent (%) and plus (+) also fail to obtain a token. If the password contains quote ("), less than (<), or greater than (>) I was able to get these to work by escaping them in the proxy.config file as &quot; &lt; and &gt; but &amp; did not work for ampersand. All other special characters work.
