### ISSUE TITLE
Unable to access secure vector tile cache

### ISSUE THREAD

**Issue by tsemroc** [Esri/resource-proxy#458]
I'm trying unsuccessfully to access a secured (not shared) vector tile cache from Portal or ArcGIS Online via the .NET proxy.

I am able to access a FeatureLayer that is not shared by using username/password in the proxy.config, but this does not work for vector tile layers. 

If I remove the proxy from the app and provide username/password when prompted by Portal, my vector tile layer displays, but if I use the proxy with the same username/password no vector tile layer displays. 

I don't see any errors in the network traffic in the browser console, just that requests to the vector tile layer are not being relayed. 

Toby

**Comment by bsvensson** [comment]
Hello @tsemroc - which version of the JSAPI are you using?

For example, in version 3.24 and 4.6 we fixed:
`BUG-000109264 - Fixed an issue where some secured VectorTileLayers would not load properly if handled via a proxy file.`
See https://developers.arcgis.com/javascript/latest/guide/release-notes/index.html#bug-fixes-and-enhancements and https://developers.arcgis.com/javascript/3/jshelp/whats_new.html.

**Comment by tsemroc** [comment]
I'm using 4.6.  Doesn't appear that the bug was fixed. I have a case open with Esri tech support and they have confirmed that the problem still exists. Though, I don't know for sure whether the problem is in the jsapi or the proxy. Though as I said above, if I remove the proxy page and access the vector tile via the login presented by Portal/ArcGIS online I am able to access the tiles.

**Comment by bsvensson** [comment]
@tsemroc - do you have the bug number from Esri Tech Support?

**Comment by tsemroc** [comment]
@bsvensson the bug # is BUG-000111290. It's fixed already! It turns out the bug was in the JSAPI and not the proxy page. I was able to test a dev version of the 4.7 api yesterday and was able to access a secure vector tile that contained point geometry using the proxy.aspx. Sorry for the fire alarm.
