### ISSUE TITLE
All versions of PHP proxy fail on Ubuntu 17.10.1 and PHP 7.1 

### ISSUE THREAD

**Issue by kefayati** [Esri/resource-proxy#461]
I have tried everything with almost all versions of the php proxy, from 0.9 all the way to the nightly as of today and while they work on PHP v5, I cannot get the proxy.php to produce anything, including error messages. I have checked it on cli as well with zero result. Needless to say, proxy-verification.php passes all the tests (see below for sample result on 1.1.2 and all logging options are turned on).

I have been able to get 1.1.0-beta to work, but it responds with error:

> GET detectedCan not determine if OAuth or ArcGIS Server means of authentication. Check config for errors.

Needless to say, the service being proxied above is not protected at all. Also, I am pretty sure it has something to do with PHP/Apache since same machine used to work relatively well with PHP 7.0 except that file uploads where not working (basically GET seemed to work and POST did not). I tried switching to PHP 7.1, hoping for better and now nothing works.

php-verfication.php response:

> Check PHP version 5.4.2 or newer? | Pass [v7.1.11-0ubuntu0.17.10.1]
> Check if directory is writable? | Pass
> Check for PDO Sqlite extension? | Pass
> Check for Curl? | Pass [v.7.55.1]

**Comment by kefayati** [comment]
on 1.1.0-beta I changed error_reporting(-1); in the proxy.php and now I get the following error. So seems some bug with the script and not really with PHP, just uncovered with PHP 7.1.

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function Proxy::proxyGet(), 0 passed in /var/www/html/esri/php/proxy.php on line 871 and exactly 1 expected in /var/www/html/esri/php/proxy.php:1043 Stack trace: #0 /var/www/html/esri/php/proxy.php(871): Proxy->proxyGet() #1 /var/www/html/esri/php/proxy.php(276): Proxy->runProxy() #2 /var/www/html/esri/php/proxy.php(2846): Proxy->__construct(Object(ProxyConfig), Object(ProxyLog)) #3 {main} thrown in /var/www/html/esri/php/proxy.php on line 1043

**Comment by kefayati** [comment]
Enabling the error reporting which was disabled in app the versions, I noticed couple of issues:

1. The proxy expects only XML configs, although I could use JSON config back in 1.1.0-beta.
2. php-xml is needed (at least for config reasons) which is not mentioned in the requirements and checked by verification page.
3. Many fields in the config are needed to be present, although being irrelevant. Through trial and error, I found hostRedirect, ratelimitperiod, ratelimit need to be present before things work at all.
4. Even after all that, versions from nightly all the way back to 1.1.0 fail with the below error; probably due to some other missing fields.

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function Proxy::proxyGet(), 0 passed in /var/www/html/esri/php_master/proxy.php on line 872 and exactly 1 expected in /var/www/html/esri/php_master/proxy.php:1044 Stack trace: #0 /var/www/html/esri/php_master/proxy.php(872): Proxy->proxyGet() #1 /var/www/html/esri/php_master/proxy.php(266): Proxy->runProxy() #2 /var/www/html/esri/php_master/proxy.php(2847): Proxy->__construct(Object(ProxyConfig), Object(ProxyLog)) #3 {main} thrown in /var/www/html/esri/php_master/proxy.php on line 1044

5. v1.0 works, but still complains with the below errors. Switching error reporting back to 0 level hides these.

> <br />
> <b>Notice</b>:  Undefined property: stdClass::$error in <b>/var/www/html/esri/php_1.0/proxy.php</b> on line <b>735</b><br />
> <br />
> <b>Notice</b>:  Trying to get property of non-object in <b>/var/www/html/esri/php_1.0/proxy.php</b> on line <b>735</b><br />

6. File uploads, which was my main issue to begin with, still does not work. The proxy log detects it as FILES and says proxy complete but the esri.request of the JSAPI side fails.

**Comment by kefayati** [comment]
Regarding the file upload issue. It seems that the core problem is the url to which the redirect comes back, particularly, instead of a proxied url, the response url gets added to the proxy server base url. E.g.
Response url: 
> http://px.server/arcgis/rest/services/SV_NAME/GPServer/uploads/upload

Expected response: 

> http://px.server/esri/php/proxy.php?http://gis.server:6080/arcgis/rest/services/SV_NAME/GPServer/uploads/upload

**Comment by kefayati** [comment]
I did some digging on the newer versions of the proxy script as well as 7.0 vs 7.1, and there are obvious bugs and compatibility issues. 
1. In one instance (line 872), proxyGet() is called with no argument. 7.1 force matches number of arguments, so that needs to be passed a null.
2. Even after that, the isUnauthorized() function apparently cannot handle missing credentials, for unprotected services. That could have the same culprit as forcing missing arguments compatibility between 7.0 and 7.1 and probably other issues mentioned above.

**Comment by bsvensson** [comment]
Thank you @kefayati for the issue reporting and testing.

The PHP proxy doesn't currently support PHP 7.1 (nor 7.0).  The plan is to end support for PHP 5x and move to PHP 7.1 as a minimum requirement. See https://github.com/Esri/resource-proxy/issues/449

There are several other issues and PRs related to this.

**Comment by kefayati** [comment]
Is there any work around? Our VMs are now upgraded to 17.10.

**Comment by kefayati** [comment]
OK, we switched back to PHP 5.6 in our environment and while everything else seem to work, file upload still has issues and fails.
Should I open another issue?

**Comment by kefayati** [comment]
[This](https://github.com/Esri/resource-proxy/issues/59) issue seems to be the closest to it, not sure if it is the same though. I have Apache 2.4.7 + PHP 5.4 on Windows 10 and it works fine with PHP Proxy 1.1.0-beta so I am wondering what is the root cause.

**Comment by bsvensson** [comment]
> 2. php-xml is needed (at least for config reasons) which is not mentioned in the requirements and checked by verification page.

Thanks for pointing this out. We had one earlier related report of that (for nginx) in #409 , and doc'd it at https://github.com/Esri/resource-proxy/blob/master/PHP/README.md#when-running-this-proxy-on-nginx-its-been-reported-that-following-php-extensions-are-needed

**Comment by g3n1us** [comment]
This issue will be addressed with the recently merged: PR #443

**Comment by bsvensson** [comment]
Assumed fixed:

> This issue will be addressed with the recently merged: PR #443
