### ISSUE TITLE
PHP: Remove support for json config format

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#463]
All three proxies support the same XML configuration for proxy.config.  In addition, the PHP proxy supports an additional format for the proxy.config file: JSON. See for example https://github.com/Esri/resource-proxy/blob/master/PHP/README.md#example-configurations

My proposal is to simplify the proxies, keep them in sync, and simplify testing - by removing the JSON support.

**Comment by djeraseit** [comment]
JSON is the way of the future
