### ISSUE TITLE
.Net Proxy treats IWA and Token based authentication as mutually exclusive events

### ISSUE THREAD

**Issue by dgwaldo** [Esri/resource-proxy#464]
Currently the proxy does not work if the server is using token based security, and is locked down with IWA.

**Issue Description:** 
Our architecture consists of a custom-built GIS application utilizing the ArcGIS JS 3.x API’s. It is hosted inside a .NET MVC application. The ArcGIS Server (AGS) .Net Resource Proxy is used to allow users access into AGS. The application needs to connect to a standalone instance of AGS using IWA (Integrated Windows Authentication), as well as an AGS connected to ArcGIS Portal Enterprise. Both servers are configured with ArcGIS Server Web Adapter (ASWA). 
If you hit the AGS info endpoint for the standalone AGS server through the ASWA, you will see that it does not use token-based security.

```
// Instance 1: https://server.domain.com/aswat/rest/info?f=json
{
    currentVersion: 10.41,
    fullVersion: "10.5.1",
    soapUrl: "https://server.domain.com/aswa/services",
    secureSoapUrl: null,
    authInfo: {
       isTokenBasedSecurity: false
   }
}
```
If you hit the AGS info endpoint for the AGS instance connected to Portal through the ASWA, you will see that it shows an “owningSystemUrl” (Portal) as well as having the token based security flag set to true.

```
// Instance 2: https://server.domain.com/aswa/rest/info?f=json
{
    currentVersion: 10.5,
    fullVersion: "10.5.0",
    soapUrl: "https://server.domain.com/aswa/services",
    secureSoapUrl: null,
    owningSystemUrl: "https://server.domain.com/aswa",
    authInfo: {
        isTokenBasedSecurity: true,
        tokenServicesUrl: "https://server.domain.com/aswa/sharing/generateToken"
   }
}
```
The above is visible if you are authenticated on the web adapter. Because IWA is used on both servers, when any endpoint at the root url of https://server.domain.com/ is hit on either server a modal dialog such as the one below is shown in browsers.

![image](https://user-images.githubusercontent.com/7613342/35983037-d36743ca-0cb6-11e8-9699-0de404338e97.png)
IWA is going to require login to hit any endpoints.

Utilizing the .Net Resource Proxy works with user name login on AGS Instance 1.
However, utilizing the proxy as the code currently exists does not work. Instance 2 is connected to Portal and requires token based security. To get a token, the /sharing/generateToken endpoint must be used. The issue is that this endpoint is protected by IWA, when the proxy calls this code it get’s a 401 (Unauthorized) returned to the caller. Why?

The proxy handles multiple authentication cases, and it is written to assume that each use case is exclusive. The code at fault is below, shortened to make the point.

```
//App Pool identity, great let’s use default network credentials
if (serverUrl.UseAppPoolIdentity) {
    credentials = CredentialCache.DefaultNetworkCredentials;
    // The config has a domain parameter passed in, lets use IWA credentials
} else if (serverUrl.Domain != null) {
    credentials = new System.Net.NetworkCredential(serverUrl.Username, serverUrl.Password, 
    serverUrl.Domain);
} else {
    // Well they didn’t pass a domain parameter so lets assume we need to use a token, but lets not pass IWA credentials, because why should we?
}
```
The above code assumes that if we aren’t passing a domain or using app pool identity, we must be doing token-based auth. The missing code in the last else does quite a lot, one of the calls it makes it to get the token if the token is not already in the request. Note that in the following method call, there is not a parameter for credentials, getNewTokenIfCredentialsAreSpecified(serverUrl,requestUri).
The result of the above logic is that if your architecture mixes IWA and token based auth, the proxy is going to error with a 401. 

One possible fix for this is below.

```
if (String.IsNullOrEmpty(serverUrl.OAuth2Endpoint) || String.IsNullOrEmpty(serverUrl.TokenServiceUri)) {
    // The user is indicating by configuration that they’d like to use a token. 
    //Pass the credentials down through the call chain as well, because if the use has specified them, they   
    might be trying to get around IWA
    getNewTokenIfCredentialsAreSpecified(serverUrl,requestUri,credentials).
}
```

**Comment by jgravois** [comment]
thank you for the detailed feedback!

as with #465, since you're proposing a fix for the problem you've identified, we would _love_ to see a contribution in the form of a pull request.

**Comment by dgwaldo** [comment]
I'd _love_ to see less ugly code :)
