### ISSUE TITLE
.Net Proxy exchangePortalTokenForServerToken method passes parameters to generateToken that don't work

### ISSUE THREAD

**Issue by dgwaldo** [Esri/resource-proxy#465]
The current code seems to be passing parameters that are for an older API maybe? The below code seems to work better :)

```
private string exchangePortalTokenForServerToken(string portalToken, ServerUrl su, System.Net.NetworkCredential credentials = null) {
		//ideally, we should POST the token request
		log(TraceLevel.Info, " Exchanging Portal token for Server-specific token for " + su.Url + "...");
		string uri = su.OAuth2Endpoint.Substring(0, su.OAuth2Endpoint.IndexOf("/oauth2/", StringComparison.OrdinalIgnoreCase)) +
				"/generateToken?grant_type=authorization_code" + "&client_id=" + su.ClientId + "&redirect_uri="
				+ PROXY_REFERER + "&code=" + portalToken + "&f=json";
		string tokenResponse = webResponseToString(doHTTPRequest(uri, "GET", credentials));
		return extractToken(tokenResponse, "token");
}
```

**Comment by jgravois** [comment]
thanks for this contribution @dgwaldo!

since you're proposing an improvement it would make more sense to open a pull request than an issue. providing an explanation of what specific problem you've solved would also be helpful if you can manage it.

**Comment by dgwaldo** [comment]
I already have 3 days into this garbage pile of a proxy :) Have fun fellas

**Comment by jgravois** [comment]
🙄

**Comment by dgwaldo** [comment]
I submitted a PR, turned out to be a little tedious with the code formatting, or lack of it. 

https://github.com/Esri/resource-proxy/pull/467

Would be interested to know of our scenario of using IWA and Tokens together is encountered much? Reading different forums, it sounds like a common issue that people are experiencing, but hard to know from what people write.

Also to be clear, I started with the PR from this issue. https://github.com/Esri/resource-proxy/issues/456 so that should probably be merged first. Also, without a test suite, how do you guys sleep at night after merging stuff into master? :) 

Also, note that I am probably breaking the rule about committing in logical units, but these changes all had to be made to get the proxy running in our environment, so that's a logical unit in a way ;)

**Comment by jgravois** [comment]
much appreciated @dgwaldo!

> how do you guys sleep at night after merging stuff into `master`? :)

awhile ago @bsvensson hacked together a test suite that spawns a variety of requests to services and instrospects responses. we created a placeholder issue to include it in this repo in #440, but it just hasn't happened (yet). all PRs _do_ undergo code review and a round of manual testing. its as tedious on our side as it is on yours and as everyone can see, the lack of internal process has resulted in lots of contributions sitting idle longer than any of us would like.

if could go back to 2013 i'd definitely go a different direction than housing a Java, .NET and PHP proxy in the same repo and trying and keep individual releases entirely in sync, but at this point our obligations building the ArcGIS API for JavaScript and ArcGIS Hub, along with other open source projects like Esri Leaflet and arcgis-rest-js have gotten in the way of taking on any major overhauls here.

I appreciate your frustration (substantially more so when its delivered constructively), but it also just _is what it is_.
