### ISSUE TITLE
Accessing secured service with SAML Portal Authentification

### ISSUE THREAD

**Issue by zjankovsky** [Esri/resource-proxy#471]
I am trying to access secured Map Service on federated SAML ArcGIS Server/Portal on 10.5.1 with .NET proxy.
I tried two approaches:
1. Portal Build-In User/password configured in proxy config with username/password attributes.
In this case, generating server token works, but after some time, proxy does not return the map service output, but send to client only logging redirect page of the Portal. From my point of view, the problem [is on those lines ](https://github.com/Esri/resource-proxy/blob/f54171f3089765fe522f0ce351551b59c6a4a58a/DotNet/proxy.ashx#L502-L506), because with SAML, the server doesn't return error code, but the loggin page - proxy cannot recognize that the token is not valid anymore (it gets valid response).

2. I tried setup application login to the service: with clientId + clientSecret + oauth2Endpoint. In the proxy log there is a message that token is generated, than it is switched to server token, but from the service come only the logging page of the portal as well. My application item on portal is owned by the same user as the service I am requesting.

Is the point 1. known limitation, or should I setup proxy in a different way?

**Comment by umbe1987** [comment]
I am facing a similar issue as in point 2. I opened [a thread in Geonet](https://community.esri.com/thread/217044-invalid-token-498-from-portal-for-arcgis-with-oauth2-app-login) for this.
In my proxy.config in Geonet there's no "oauth2endpoint" but I also tried with it with the same result as @zjankovsky.
Can app login be used to authorize an app to access secured service on a Portal?
from [Limitations of App Login](https://community.esri.com/external-link.jspa?url=https%3A%2F%2Fdevelopers.arcgis.com%2Fdocumentation%2Fcore-concepts%2Fsecurity-and-authentication%2Flimitations-of-application-authentication%2F) it seems it is not possible...
Can anybody shed a light on this please?

**Comment by fleray** [comment]
> I am facing a similar issue as in point 2. I opened [a thread in Geonet]
> Can app login be used to authorize an app to access secured service on a Portal?
> from [Limitations of App Login](https://community.esri.com/external-link.jspa?url=https%3A%2F%2Fdevelopers.arcgis.com%2Fdocumentation%2Fcore-concepts%2Fsecurity-and-authentication%2Flimitations-of-application-authentication%2F) it seems it is not possible...
> Can anybody shed a light on this please?

About point 2, I share your opinion @umbe1987 : I observe the same erroneous behavior like the one you described in your [[thread in Geonet]](https://community.esri.com/thread/217044-invalid-token-498-from-portal-for-arcgis-with-oauth2-app-login).

To me the current [Limitations of App Login](https://community.esri.com/external-link.jspa?url=https%3A%2F%2Fdevelopers.arcgis.com%2Fdocumentation%2Fcore-concepts%2Fsecurity-and-authentication%2Flimitations-of-application-authentication%2F) explains why we are not able to access private content through App login.

And I think there WAS a time we could access private contents using this security pattern (App Login), specially about ArcGIS Online content, but this is now no more possible...

So, does it mean, inside the code (proxy.jsp anf others), that the current conditions  :
- IF [AppLogin is used](https://github.com/Esri/resource-proxy/blob/master/Java/proxy.jsp#L315) 
AND
- IF [we are able to genrtae a Poral token](https://github.com/Esri/resource-proxy/blob/master/Java/proxy.jsp#L325-L328)
THEN [exchangePortalTokenForServerToken](https://github.com/Esri/resource-proxy/blob/master/Java/proxy.jsp#L329)

has no more meaning ?
If so, this code needs to be removed, don't you think ?
