### ISSUE TITLE
PHP proxy fails when using PHP 7

### ISSUE THREAD

**Issue by andygup** [Esri/resource-proxy#473]
I'm using `route.arcgis.com` and It looks like just a minor change to the constructor here https://github.com/Esri/resource-proxy/blob/master/PHP/proxy.php#L1095 will fix my issue. 

CURRENT:

```
    public function proxyPost($url, $params) { . . . 
```
PROPOSED:

```
    public function proxyPost($url = null, $params = null) { . . .

```

@bsvensson I can do a PR?

**Comment by bsvensson** [comment]
@andygup - Yes, please submit a PR.

**Comment by andygup** [comment]
@bsvensson PR https://github.com/Esri/resource-proxy/pull/476.
