### ISSUE TITLE
Solve route on older ArcGISRuntime

### ISSUE THREAD

**Issue by buffbutler** [Esri/resource-proxy#479]
There is an issue with older ArcGISRuntime libraries in regards to routing/network analysis.  Basically routing will append a "/solve" to the end of the url path not the path in the query string.  So the url:

http://myproxy/proxy.ashx?https://route.arcgis.com/myservicepath/

Would be supplied to the client library.  This would work for metadata exchange, however once a route request is done the url would be:

http://myproxy/proxy.ashx/solve?https://route.arcgis.com/myservicepath/

The path that should be emitted is:

https://route.arcgis.com/myservicepath/solve

This involves taking everything that was appended after proxy.ashx and appending it at the end of the query path.

The solution (I can't extract a pull/merge because it depends on other customizations):

```
string urlSuffix = this.ExtractUrlPathSuffix(context.Request);

//inject any appended suffix
if (!string.IsNullOrEmpty(urlSuffix))
{
    if (requestUri.Contains("?"))
    {
        requestUri = requestUri.ReplaceFirst("?", urlSuffix + "?");
    }
    else
    {
        requestUri = requestUri + urlSuffix;
    }
}
```

**Comment by buffbutler** [comment]
This is for the .net proxy :)

**Comment by anaskanaan** [comment]
DotNet proxy encounters the same error with tiled layer and map image layer
for example
https://wanka.esri-sgroup.com/dnproxy/proxy.ashx/tile/1/11/22?https%3A%2F%2Farcgis-mapstst.arcgis.se%2Farcgis%2Frest%2Fservices%2Fmmpo%2FMapServer=

any near solution to this ?

**Comment by bsvensson** [comment]
@anaskanaan - does it work if you use the suggested solution above?

**Comment by buffbutler** [comment]
The solution is basically what is above.  I cant make a pull request because it has some business specific logic being parsed out and the code base has changed so much now.  I have routing, tiling and feature server content all passing through it... so it can work.

You'll have to configure the handler to capture all urls rather then just the ashx.  This involves changing how the handler class is being built and adding an entry into web.config:

```
<add name="ReverseProxyRelay" verb="*" path="*" type="yournamespace.esriproxy.Proxy, yournamespace.esriproxy" />
```

All that's really missing is the extract function which would be something like below.  I've chopped out all of the extra custom logic; a better solution would be prefixPath.Substring rather than looping, but my changes required this (I don't know if this code works - I just did it in notepad).

I remember there being some problems with the logging code too because it was using server.MapPath in relation to the change to the web.config.

```
public string ExtractUrlPathSuffix(HttpRequest request)
        {
            string prefixPath = request.Url.AbsolutePath;;

            StringBuilder suffix = new StringBuilder();
            bool matched = false;

            foreach (string currentSegment in prefixPath.Split("/".ToCharArray()))
            {
                //first we look for the "proxy.ashx" discarding everything beforehand
                if (!matched)
                {
                     if ("proxy.ashx".Equals(currentSegment, StringComparison.InvariantCultureIgnoreCase)
                         matched = true;
                } else{
                        //append everything after proxy.ashx
                        suffix.append(currentSegment);
                }
            }

            return suffix.ToString();
        }
```

**Comment by anaskanaan** [comment]
HI again and thanks for your fast responses.
I Have tried ExtractURLPathSuffix against https://wanka.esri-sgroup.com/dnproxy/proxy.ashx/export?https%3A%2F%2Farcgis-mapstst.metria.se%2Farcgis%2Frest%2Fservices%2FMetriaMapsOrto%2FMapServer=&dpi=96&transparent=true&format=png32&layers=show%3A3&bbox=781966.1235121362%2C8696214.228568077%2C2588325.975946941%2C9806691.375494823&bboxSR=102100&imageSR=102100&size=1477%2C908&f=image
and i got the suffix as 
export?https%3A%2F%2Farcgis-mapstst.metria.se%2Farcgis%2Frest%2Fservices%2FMetriaMapsOrto%2FMapServer=&dpi=96&transparent=true&format=png32&layers=show%3A3&bbox=781966.1235121362%2C8696214.228568077%2C2588325.975946941%2C9806691.375494823&bboxSR=102100&imageSR=102100&size=1477%2C908&f=image

so i do not think if the following code should help with having a valid request
string urlSuffix = this.ExtractUrlPathSuffix(context.Request);

//inject any appended suffix
if (!string.IsNullOrEmpty(urlSuffix))
{
    if (requestUri.Contains("?"))
    {
        requestUri = requestUri.ReplaceFirst("?", urlSuffix + "?");
    }
    else
    {
        requestUri = requestUri + urlSuffix;
    }
}

any input is appreciated?
