### ISSUE TITLE
A security issue when troubleshooting ArcGIS JavaScript API and Web AppBuilder applications with the Esri Resource Proxy.

### ISSUE THREAD

**Issue by kGhime** [Esri/resource-proxy#492]
The proxy is accessing secured material (services or web maps) even when credentials are not supplied.

The workflow is the following:
1. Create a JS API application that consumes a secure service or Webmap.
2. Set proxy rules in the application.
3. Add the server URL with the UN/pass or ClientId/ClientSecret to access these secure services into the proxy.config file.
4. Run the app (token is generated with this UN/pass ClientId/ClientSecret) and you can see the secure data.
5. Edit the proxy.config file and remove the UN/pass or ClientId/ClientSecret properties just added in step 3.
6. Refresh the application in the browser and the application does not ask for credentials and displays the secure data.

This has been tested on many different browsers and different machines within the network. I believe that the token generated is stored in the server for 24 hours or so until it expires but I am not sure where or if this is actually what is occurring.

Anyone can access this application on the network without the UN/pass or ClientId/ClientSecret in the proxy.config file for about 24 hours.

I want to know how to overcome this issue or if this is a bug or an expected behavior?
What should be the resolution?

**Comment by esoekianto** [comment]
@kGhime I assume this is .NET version of the resource-proxy? 

If yes, then you can try changing the `recycling` interval of the `Application Pool` being used by resource proxy application in IIS. Try changing it to smaller number like 59 minutes. 

https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/applicationpools/add/recycling/ 

Let me know if this works.

**Comment by kGhime** [comment]
@esoekianto Thanks Erwin. Yes, this is .NET version of the resource-proxy. And it worked too but with following exception.

In the IIS settings, I changed the value of "Regular time intervals" under Recycling conditions for the pool from 1740 to 1 minute. And so, now, the application which is proxy configured, does not asks for credentials for the secured service for 1 minute (instead of the earlier 1740 minutes), even though they are not provided in "proxy.config". But after waiting for this 1 minute, the application asks for credentials (since they are not provided in proxy.config file), and this behavior is not changed afterwards.

It seems, for security purpose, the Time interval should be 0 minutes, because for any other time interval, it is providing the window to access secured services without asking for credentials. What should be done in such case?
