### ISSUE TITLE
app does not go through the proxy when the app is in the same domain as the arcgis server

### ISSUE THREAD

**Issue by Danielpx** [Esri/resource-proxy#493]
app does not go through the proxy when the app is in the same domain as the arcgis server, when the app is in another domain it works perfectly, is there any way around this?

**Comment by bsvensson** [comment]
Hi @Danielpx Usually that shouldn't happen.  
Could you provide some more details?  For example which proxy you are using, what call is not being proxied, is the service secured, is it still working in the app, and maybe a repro case?

**Comment by Danielpx** [comment]
I'm using proxy.jsp.

1. The arcgisserver server is hosted with webaaptor java at https: //www1.serverarcgis.intranet;
2. The Proxy is at https: //www1.serverarcgis/proxy/proxy.jsp
3. The protected service I'm using is Analysis;

When the app is running on another https: //www2.server.intranet/app authenticated server usually through the proxy at https: //www1.serverarcgis/proxy/proxy.jsp and use the Analyze tool in the app.

If I put the app on https: //www1.serverarcgis/app I'm directed to the arcgis https: //www1.serverarcgis.intranet/arcgisportal/home/signin.html

Sorry about my English
