### ISSUE TITLE
Accessing ARCGIS end point using a proxy returns a 500 error (No subject alternative names present)

### ISSUE THREAD

**Issue by humantornado9** [Esri/resource-proxy#495]
Should the proxy be configured on the same machine that host arc gis services?

**Comment by bsvensson** [comment]
@humantornado9 - The proxy runs on your local web server, not on an Esri server or on the computer where ArcGIS Server is installed (unless your web server also hosts the ArcGIS Server instance).

See https://developers.arcgis.com/javascript/latest/guide/proxies/index.html
