### ISSUE TITLE
Failed do detect expired token with callback param

### ISSUE THREAD

**Issue by lucianoac** [Esri/resource-proxy#496]
After digging around a bit I found a case scenario that fail to renew a token.

Some details:
Proxy version: 1.1.2
ArcGis: 10.6 (supposedly this issue was not occurring with 10.3)
Relevant Url params: f=json and callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback
Token Expiration: 1 minute 
https://github.com/Esri/resource-proxy/blob/e73edd1b922ce4cb5a96bc02f53cb18706e4e9e9/DotNet/proxy.ashx#L642

1) First run, token created and everything looks good;
2) After a minute or so, token expires
3) Proxy calls fetchAndPassBackToClient()
https://github.com/Esri/resource-proxy/blob/e73edd1b922ce4cb5a96bc02f53cb18706e4e9e9/DotNet/proxy.ashx#L493

This function expects a ContentType within text, json or xml. It then proceeds to check the body for error codes (498 or 499). However, due to the callback param, the response type is an 'application/javascript' like this:

> "dojo.io.script.jsonp_dojoIoScript1._jsonpCallback({"error":{"code":498,"message":"Invalid Token","details":[]}});"

Since it doesn't fit the initial criteria, the proxy class considers the old token as valid, therefore happily returns the response for the client.

**Comment by haibingwang** [comment]
We are experiencing the exact same issue when accessing a 10.6 rest service with DotNet proxy.

After working with ESRI support for quite some time, this is the proposed workaround: set a shorter recycling time in IIS for the proxy’s application pool, say 55 minutes.

I consider this fix as temporary, and I am looking forward to a true fix in the proxy.
