### ISSUE TITLE
Requests that exceed 2048 characters

### ISSUE THREAD

**Issue by powel-jeso** [Esri/resource-proxy#497]
From the readme file I can see that "These proxy files support: Requests that exceed 2048 characters"

How is this supported? Is there something I need to do in the configuration file? Or am I missing something else?

If I submit a long url (> 2048 chars) to the proxy using GET my arcgis server will return a 404.15 (Not found - long url). I was hoping that the proxy would somehow change my (too long) GET request to a POST request with a proper formatted body and the forward this request to the gis server.

PS. I am not using an esri javascript client but I am using viewers and workflows from latitude geographic as my client. 

- Jesper

**Comment by powel-jeso** [comment]
Okay - thanks for quick reply.

I think someone should update the documentation that redirects people to this github project, eg. the javascript api documentation (https://developers.arcgis.com/javascript/3/jshelp/ags_proxy.html) because it states:

You may need to use a proxy in the following situations:

Requests exceed the limit on the length of the uniform resource locators (URLs) imposed by the browser. Common scenarios where you may run into URL length issues are when you use the buffer from a complex polygon as the input to a query task or if you specify a spatial reference using well-known text (WKT).
Note: Using a proxy works around this issue by performing a POST request rather than a GET request. POST requests are not limited by the 2048 character maximum because the information is transferred in the header instead of the URL.

- Jesper

**Comment by jgravois** [comment]
> I think someone should update the documentation that redirects people to this github project

updated how exactly?

The ArcGIS API for JavaScript ensures internally that a POST will be used if the parameters being passed in a request would exceed the limit and that a valid proxy will be utilized if a cross domain request needs to be made to a server that isn't known to support CORS.

**Comment by powel-jeso** [comment]
I think this section is misleading:

Requests exceed the limit on the length of the uniform resource locators (URLs) imposed by the browser. Common scenarios where you may run into URL length issues are when you use the buffer from a complex polygon as the input to a query task or if you specify a spatial reference using well-known text (WKT).
Note: Using a proxy works around this issue by performing a POST request rather than a GET request. POST requests are not limited by the 2048 character maximum because the information is transferred in the header instead of the URL.

English is not my native language, but when I read the documentation I thought that the proxy did the conversion from GET to POST. Keep in mind I am not necessarily using the other functionalities of the proxy (token, cross domain etc.). So if the JS API does the conversion from GET to POST I do not really need the proxy for the long requests right? 

- Jesper

**Comment by jgravois** [comment]
> So if the JS API does the conversion from GET to POST I do not really need the proxy for the long requests right?

since all modern browsers now support CORS, you only _need_ a proxy if they web server you're making the request to does not.
