### ISSUE TITLE
SOAP - It is not possible to proxy a SOAP endpoint.

### ISSUE THREAD

**Issue by ca0v** [Esri/resource-proxy#498]
It is not possible to proxy a SOAP endpoint.  Is that by-design or is it easily overcome?

**Comment by ca0v** [comment]
[This](http://enterprise.arcgis.com/en/server/latest/administer/linux/enable-token-acquisition-through-an-http-get-request.htm) seems to resolve my problem.  Now the proxy can GET using a "token" as a query string parameter.  It also required modifying proxy.ashx to not require /rest/ or /sharing/:

```
                else if (reqUrl.ToLower().Contains("/services/")) {
                    log(TraceLevel.Info," Adds support for WSDL-based endpoint");
                    infoUrl = reqUrl.Substring(0, reqUrl.IndexOf("/services/", StringComparison.OrdinalIgnoreCase));
                }
                else
                    throw new ApplicationException("Unable to determine the correct URL to request a token to access private resources.");
```

**Comment by bsvensson** [comment]
Hi @ca0v,
I'm curious about the use case for getting the token via SOAP instead of REST.  Is there a case when the REST endpoint isn't working for getting a token?

**Comment by ca0v** [comment]
We have a legacy product that uses the SOAP endpoint and we want to prefix that endpoint with the proxy.  How would I use the REST endpoint without writing additional code?

The current solution configuration expects something like this:
```
<config geomservice="https://machine.acme.com/arcgis/services/Utilities/Geometry/GeometryServer"/>
```

But when that service is secure there's no way to setup a proxy and re-configure this endpoint like this:

```
geomservice="https://machine.acme.com/proxy.ashx?https://machine.acme.com/arcgis/services/Utilities/Geometry/GeometryServer"/>
```

So swapping in the /rest/ in the proxy does get a token using REST instead of SOAP but I can still proxy a SOAP endpoint.
