### ISSUE TITLE
Error:"User does not have permissions to access 'aaa.mapserver'",or "Unexpected token <"[DotNet]

### ISSUE THREAD

**Issue by yiersl** [Esri/resource-proxy#500]
Thanks first!
as I user the ArcGIS Server10.4+Token Releases 1.1.2+arcgis js api 3.20,use proxy.ashx to store my username and password which registed in ArcGIS Server,my app has 2 main problems(debugging in chrome):
**(1)regularly show"User does not have permissions to access 'aaa.mapserver'",and the TiledLayer( aaa.mapserver) count not show in my app**
![1](https://user-images.githubusercontent.com/44186698/46998257-97db7480-d154-11e8-8ba8-b0c63ed2b19d.png)
**(2)token is not stable ,sometimes show "Unexpected token <"**
![2](https://user-images.githubusercontent.com/44186698/46998296-bc375100-d154-11e8-855f-fd384980f46c.png)
![3](https://user-images.githubusercontent.com/44186698/46998308-c5282280-d154-11e8-87ae-85ff1daec39e.png)
there is some tiny problems ,too
**(3)layer do not show ,and output 498 error,403 error**
![image](https://user-images.githubusercontent.com/44186698/46999088-3bc61f80-d157-11e8-8315-3a67a63f790b.png)
**(4)first open the app,show "ERR_CERT_AUTHORITY_INVALID"**
![4](https://user-images.githubusercontent.com/44186698/46998345-d96c1f80-d154-11e8-9898-e6db5eeddef3.png)

**Comment by dmurillo-geotec** [comment]
Hello @yiersl Were you able to resolve this issue?
