### ISSUE TITLE
Proxy not forwarding requests when matchAll = true

### ISSUE THREAD

**Issue by mkf62** [Esri/resource-proxy#501]
My understanding is that the matchAll property set to true will forward any request that **begins** with the url specified. I have a GP service that appends parameters to the end of the url when making a request, thus is constantly changing. I have set the proxy config like so:

`<serverUrl url="https://www.mydomain.com/myServer/rest/services/HabitatManagement/HabitatManagement/GPServer"
                 username="username"
                 password="pw"
                 matchAll="true"/>`

Given that matchAll is set to "true" the above URL should allows requests to the tasks in the GPServer like `/HabitatManagement/uploads/upload` (which it does) and `/HabitatManagement/submitJob` (which it does not). Looking at the proxy.ashx file in the `GetConfigServerUrl` function, is it splitting on the slashes and question mark after `/submitJob` and making it so the `configUriParts` don't match the length of the `uriParts`?

With this I get a 403 error because my URL does not match exactly since the parameters are added to the end. For instance:

> {"error": {"code": 403,"message":"Proxy has not been set up for this URL. Make sure there is a serverUrl in the configuration file that matches: https://www.mydomain.com/myServer/rest/services/HabitatManagement/HabitatManagement/GPServer/HabitatManagement/submitJob?f=json&Input_Zip_File=%7B%22itemID%22%3A%22ib98735f1-f9d7-4858-a723-1e2dbec6acd7%22%7D&State_Abbreviation=PA&Email_Address=xxx%40xxx.xxx  https://www.mydomain.com/myServer/rest/services/HabitatManagement/HabitatManagement/GPServer/HabitatManagement/submitJob?f=json&Input_Zip_File=%7B%22itemID%22%3A%22ib98735f1-f9d7-4858-a723-1e2dbec6acd7%22%7D&State_Abbreviation=PA&Email_Address=xxx%40xxx.xxx

It repeats the URL in the error message twice, but that's just the way the error message is set up in the proxy.ashx file. I think the "matchAll" property is not working as it should.

**Comment by mkf62** [comment]
No idea how or why, but I got it working (even though I didn't change much of anything), so disregard or delete this issue.

**Comment by bsvensson** [comment]
Thanks @mkf62 for reporting back - glad you got it to work :)
