### ISSUE TITLE
Respurce-proxy fails to generate a token for a secure WebMap

### ISSUE THREAD

**Issue by hars9082** [Esri/resource-proxy#516]
Esri resource proxy fails to generate a token for JavaScript application when it is built using a secure (non-public) webmap.

Before ArcGIS TLS 1.2 update, the same application configured with Esri resource proxy used to work fine.

The common URL for the issue -
https://hostname/DotNet/proxy.ashx?https://organizatoin.arcgis.com/sharing/rest/portals/self?f=json

There are two error codes observed -
-  498 Invalid Token
- 403 Forbidden 

This issue arises when a JavaScript application is created with reference to a secure webmap in it.

When the JavaScript application is created using the same secure REST services, used for creating webmap mentioned above, it works perfectly fine. The issue only arises with webmap shared with the organization. 

Tested with IIS .NET framework 4.5
Tested with Esri Resource Proxy 1.1.2

**Tested scenarios and their Results**

Secured service and Webmap	                                        Works
Secured ArcGIS hosted services and webmap	        Fails
Secured ArcGIS hosted services and Secured webmap	Fails
ArcGIS hosted services and Secured webmap	        Fails

**Comment by davewilton** [comment]
We are suddenly getting this too. I think the error is:

![image](https://user-images.githubusercontent.com/2278405/56887145-22ae0c00-6ab4-11e9-8f8e-18591b68d7b4.png)

**Comment by bsvensson** [comment]
@davewilton - which version of the resource proxy are you using?

**Comment by davewilton** [comment]
@bsvensson I just upgraded to the latest version (1.1.2) which doesn't have the same issue, another issue arose. The issue with the latest version is that it gets a token and when it attempts to "exchangePortalTokenForServerToken" it returns the below error message. Removing these lines the proxy works fine. To be clear I'm using a client id and client secret in the proxy.

![image](https://user-images.githubusercontent.com/2278405/56941208-69ecd900-6b56-11e9-84f7-085f2b56b6df.png)
