### ISSUE TITLE
Site producing unexpected error upon reload

### ISSUE THREAD

**Issue by nitsrik** [Esri/resource-proxy#518]
Hello,

I have a [site](https://gis.valleywater.org/zobissue) where external users load it, use it a bit, but if  the page is reloaded, you get an error, something like

> Unable to create map: Unable to load https://gis.valleywater.org/DotNet/proxy.ashx?https://valleywater.maps.arcgis.com/sharing/rest/content/items/c5d5719521ff4d3cab97c99cab9af312/data?f=json status: 0

I think you can regain functionality of the site if you clear your browser cache.

This site was created using the [Information Lookup template](https://solutions.arcgis.com/shared/help/information-lookup) in ArcGIS Online and then downloaded to my web server, where I further configured it to use my proxy page (v. 1.1.2) so that users don't have to login for the ArcGIS Server secured services to show.

Internally, I don't get this error when I reload.  Also I had been working with @harshjpathak and but he was not able to duplicate the problem when I provided my site files to him.  He directed me to submit this issue to see if someone here can help shed some light on what I can do about this.

Thank you in advance.

**Comment by bsvensson** [comment]
Hi @nitsrik 

1. I'm curios as to why you are using the proxy even for public services?
For example, for https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer - is that on purpose?
2. When testing in Chrome, it seems like it's failing with https://gis.valleywater.org/DotNet/proxy.ashx?https://valleywater.maps.arcgis.com/sharing/rest/content/items/c5d5719521ff4d3cab97c99cab9af312/data?f=json when refreshing the page.  The first time (of if you turn on "Disable cache"), the request has 13 request headers.  On refresh (when "Disable cache" is off), there are only 5 request headers.  I'm not sure why, but I think this is related to why it fails.
