### ISSUE TITLE
ArcGIS JavaScript API v4.11, .Net Proxy v1.1.2, ArcGIS Online Scene Layers; "Root node missing

### ISSUE THREAD

**Issue by tthompsonESRI** [Esri/resource-proxy#520]
Hey Folks,

There appears to be an issue when passing Scene Layers hosted in ArcGIS Online through the .NET Proxy v1.1.2 within a JavaScript API v4.11 application. When passing authentication through the proxy, the Scene Layer fails to load with the error message 'name: "sceneservice:root-node-missing", message: "Root node missing."'

This was replicated by three other users using three different scene layers. 
This issue does not occur when accessing public Scene Layers.
This issue does not occur when not using the proxy, but relying on the ArcGIS Online prompt for username and password.

STEPS TO REPO:

Take the attached sample downloaded the from JavaScript API Sandbox (https://developers.arcgis.com/javascript/3/sandbox/sandbox.html)
Replace the Proxy Rule with your own .NET Proxy v1.1.2
Replace the SceneLayer URL with a URL to your own secured Scene Layer hosted in ArcGIS Online
Notice the failure in the console
Remove the Proxy Rule, and login using the AGOL login prompt
Notice the layer loads without issues

[SceneLayer411.NETProxyIssue.txt](https://github.com/Esri/resource-proxy/files/3213688/SceneLayer411.NETProxyIssue.txt)

Thanks,

Tom

**Comment by bsvensson** [comment]
@tthompsonESRI - does it work fine when using the "ArcGIS Online hosted proxy"?  (This is usually a better solution than hosting your own proxy)
https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/working-with-proxies/#arcgis-online-hosted-proxy

**Comment by tthompsonESRI** [comment]
@bsvensson - Yes, leveraging the AGOL hosted proxy is a workaround for this issue. We've suggested this to the client experiencing this issue. They have not responded yet.

He's been leveraging the resource proxy successfully for some time now with his JavaScript API v3.x applications, so he may be hesitant to move fully to the AGOL hosted proxy as he migrates to JS API v4.x.

**Comment by stanleyck** [comment]
Leveraging the AGOL hosted proxy is not possible for everyone. There's a lot of people using the resource-proxy, and this issue is basically hindering all those users from displaying secure scenelayers in their applications (unless the applications are going to force users to log in).

**Comment by atomaly** [comment]
@tthompsonESRI - thanks for posting the issue

I've now successfully tested the workaround but it adds a little bit more stuff to have to do in the workflow - every layer will need to essentially reference itself in AGOL to then share to my 'custom' hosted solution. not ideal - let's hope we can get this one sorted soon.
