### ISSUE TITLE
Occurance of BUG-000093507

### ISSUE THREAD

**Issue by ryankelso** [Esri/resource-proxy#527]
I am running into the bug [BUG-000093507](https://support.esri.com/en/bugs/nimbus/QlVHLTAwMDA5MzUwNw==) in my deployment of a Web AppBuilder (Developer Edition v2.10) app.  The bug occurs with a cached map service (ArcGIS Server 10.5.1) that is requested through the DotNet proxy (v1.1.2).

I have resampling enabled on the map service.  I partially built tiles at scale 282/Level 21 in areas where I have the highest resolution imagery, but I rely on resampling from the previous scale level outside of this high resolution area.  When navigating to areas with the resampled tiles, it makes a continuous infinite number of requests for null tiles (e.g. .../MapServer/tile/NaN/NaN/NaN?blankTile=false).

I am using the proxy for this service because I want it to be secured, but I want the imagery available in this public app, so the proxy handles the credentials.

**Comment by bsvensson** [comment]
Hi @ryankelso - have you tried using the ArcGIS Online hosted proxy instead of your own proxy?

**Comment by ryankelso** [comment]
Well @bsvensson I wish I had a better answer to your question.  If it's possible to use the ArcGIS Online hosted proxy with your own ArcGIS Server map service, one that is secured using web-tier authentication, then I couldn't figure out how to do it.
