### ISSUE TITLE
Proxy performance issues

### ISSUE THREAD

**Issue by acanivano** [Esri/resource-proxy#533]
After setting the proxy to my features, the application is very slow, takes a long time to load and refresh when I move around the map. I see that what takes are the requests that it makes for the proxy. Do you know why this happens? Thanks

**Comment by srunk** [comment]
We had enough throughput issues with the 1.0/1.1 .net proxy that we chose to switch from IHttpHandler to the multithreaded code using HttpTaskAsyncHandler.  Our version is still based on 1.0 with some of the 1.1 changes added.

e.g.:

`public class proxy : HttpTaskAsyncHandler
{
    private HttpContext httpContext;
    public override bool IsReusable { get { return true; } }

    public override async Task ProcessRequestAsync(HttpContext context)
    {
        try
        {
            httpContext = context;
            await ProcessRequest();`

etc....

**Comment by acanivano** [comment]
I have changed the Proxy, from PHP to .Net and it seems to work better than before.

**Comment by bsvensson** [comment]
Thank you @acanivano for reporting back and closing the issue :)

**Comment by larotech** [comment]
@srunk I would be interested in seeing your full implementation of an sync ESRI proxy. I'm having performance issues as well with the .NET and have converted it to async but curios if you have any tricks or how implementations differ.
