### ISSUE TITLE
PHP Proxy returning 500 Internal Server Error for POST

### ISSUE THREAD

**Issue by BharathKonaganti** [Esri/resource-proxy#536]
Hi 

I am using PHP proxy to load web map which has secured layers with pop-up enabled. The webmap is loading with layers. but when i click on any feature, then the popup is not displayed as the query is failing with 500 Internal server Error.

Please let me know if i need to change anything in proxy in order to work with POST requests.

**Comment by BharathKonaganti** [comment]
I found the solution. 

In proxy.php file while calling the post method in runProxy() method at line number 868 () we have to pass null parameters.

$this->proxyPost(); change to $this->proxyPost(null,null);

**Comment by bsvensson** [comment]
@BharathKonaganti - I'm glad you got it working. 

What version of php are you using?

**Comment by BharathKonaganti** [comment]
@bsvensson: php version is 7.1.33
