### ISSUE TITLE
The proxy server application php version does not work with php version 7 and higher

### ISSUE THREAD

**Issue by JeruJeru** [Esri/resource-proxy#541]
Will the php version of the proxy be updated to php version for example 7.2 ?

**Comment by bsvensson** [comment]
Hi @JeruJeru can you give more info about what's not working. It worked with php 7.2.2 in [2018](https://github.com/Esri/resource-proxy/pull/443#issuecomment-363286547) and the php resource proxy code hasn't changed since then.

**Comment by JeruJeru** [comment]
When there is a proxy on the server in php 5.6.40, the map layers are loaded. But when I run proxi with php version 7.2.31, the layers don't load.
Example: https://mapy.preferably.eu/oblast-zona-bb.html
