### ISSUE TITLE
304 Not modified errors created in log files for all request.

### ISSUE THREAD

**Issue by bayramucuncu** [Esri/resource-proxy#548]
Proxy is configured with logging strategy like following:

`<ProxyConfig allowedReferers="*"`
`      mustMatch="true" `
`			 logFile="logs/proxyLog.txt"`
`             logLevel="Error"`
`			 xmlns="proxy.xsd">`

But it proxyLog.txt is filled up with 304 errors. The file size is growing very quickly (about 20Mb per 8 hours). 

- Can I except 304 errors?
- Can I split log files by days?

**Comment by bsvensson** [comment]
@bayramucuncu - You could change the log level from `Error` to something less verbose:
https://github.com/Esri/resource-proxy#proxy-configuration-settings

If you wanted to specifically exclude some errors you would have to change the code of the proxy.

**Comment by bayramucuncu** [comment]
> @bayramucuncu - You could change the log level from `Error` to something less verbose:
> https://github.com/Esri/resource-proxy#proxy-configuration-settings
> 
> If you wanted to specifically exclude some errors you would have to change the code of the proxy.

**Comment by bsvensson** [comment]
Sorry, I forgot that `Error` is the least verbose of them.

Then I think you're left with two options:
* Turn off all logging
* Change the code to not log specific messages.
