### ISSUE TITLE
Proxy has not been set up for this URL

### ISSUE THREAD

**Issue by ginfinityhq** [Esri/resource-proxy#551]
Dear all,

  I am trying to use the php proxy. The prerequisites seems to be ok but we are getting the following error. Can anyone help us solve this? 

{"error":{"code":403,"details":["Proxy has not been set up for this URL. Make sure there is a serverUrl in the configuration file that matches: https:\/\/gissrv.deda.gr\/server\/rest\/services\/WebDiathesimotita\/WebDiathesimotitaQuery\/MapServer\/"],"message":"Proxy has not been set up for this URL."}}

**Comment by bsvensson** [comment]
@ginfinityhq - what does your proxy.config look like? Does it have an entry that should match that server?

**Comment by ginfinityhq** [comment]
Hello,

   This is my config details:

<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
		mustMatch="true">
    
		<serverUrl url='//gissrv.deda.gr/*'
    matchAll="true">
</serverUrl>
	
</ProxyConfig>



  

   Can you see anything wrong?

**Comment by jjface** [comment]
missing the / at the end of the xml? 
i.e.: <serverUrl url="https://gissrv.deda.gr/server/rest/services/WebDiathesimotita/WebDiathesimotitaQuery/MapServer/"
matchAll="true"/>
