### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by jocelimjr2000** [Esri/resource-proxy#558]
Hello,
I have a problem and I need your help. 
I included two diferents users in proxy.config (Java) and need choose an account in differents webapp, but i don't know solve this problem.
Thank's so much.

<serverUrls>
     <serverUrl url="..." username="user01" password="password" matchAll="true" />
     <serverUrl url="..." username="user02" password="password" matchAll="true" />
</serverUrls>

WebApp 01 - Access account 01 (user01)
WebApp 02 - Access account 02 (user02)

**Comment by bsvensson** [comment]
@jocelimjr2000 If you want two different apps to use different authentications, the easiest way is probably to just
* use two different proxy files.

**Comment by jocelimjr2000** [comment]
@bsvensson I duplicated the proxy.jsp and proxy.config files (proxy1.jsp / proxy1.config) into current project, but there was a error on the second connection (recursive endpoint caller, returning error code 403, message: "You do not have permissions to access this resource or perform this operation.", messageCode: "GWM_0003").  
I duplicated the project and it worked.
Thank you.

**Comment by bsvensson** [comment]
Glad you got it working @jocelimjr2000 :)
