### ISSUE TITLE
preliminary calls not using proxy

### ISSUE THREAD

**Issue by cdempewolf** [Esri/resource-proxy#564]
We have an application that is configured to use the .net proxy. We are seeing some of the preliminary calls fail to use the proxy, which results in them giving an error. We are using the proxy for authentication, but also to map to an internal server from a public load balancer. There are two calls that are not using the proxy, and when on an external server they return failures. How can we ensure that these calls utilize the proxy correctly?

> [serverURL]/arcgis/rest/services/[serviceName]/MapServer/?f=json&callback=jQuery20309293575837176473_1640207000238&_=1640207000239

> [serverUrl]/arcgis/rest/info?f=json

**Comment by bsvensson** [comment]
Hi @cdempewolf - If the application isn't sending the requests to the proxy for some use cases, then it sounds like the problem is with the application - not with the resource proxy.

**Comment by cdempewolf** [comment]
I appreciate your quick response. However, part of the problem that we're seeing is that these calls are not ones that the code is making explicitly. We can find no origination for them, and the proxy is configured to intercept all traffic to these servers before the calls are sent over. So these calls should be intercepted by the proxy, but for some reason are not using the proxy rules defined.

**Comment by bsvensson** [comment]
With "application", I meant any request coming from the application when used in the browser, whether it's specifically the application code or some other library used by the application.  
* Are you using the ArcGIS API for JavaScript? If so, which version?
* Are the "preliminary requests" something you only noticed it the console?  ie is the application still working, but the initial requests are failing?
