### ISSUE TITLE
How to use esri-resource-proxy in an application running on a different port?

### ISSUE THREAD

**Issue by slead** [Esri/resource-proxy#565]
Hi there. 

In the ArcGIS Server JavaScript API v4, I'm using esri-resource-proxy to access a WMS layer from a server that doesn't support CORS:

```
urlUtils.addProxyRule({
    urlPrefix: "https://environment.data.gov.uk/",
    proxyUrl: "http://localhost/proxy/proxy.php"
});

let layer = new WMSLayer({
  url: "https://environment.data.gov.uk/spatialdata/special-protection-areas-england/wms",
  sublayers: [{name: "Special_Protection_Areas_England"}]
});

map.add(layer);
```

The proxy approach is working correctly in a stand-alone HTML file when the proxy is also on the same port (ie both are served by http://localhost) as the requests are sent via:

http://localhost/proxy/proxy.php?https://environment.data.gov.uk/spatialdata/special-protection-areas-england/wms......

The question is how to use esri-resource-proxy with a React application that's running via http://localhost:3000

Since this is on a different port to the proxy at http://localhost/proxy/proxy.php the request fails:

_Access to fetch at 'http://localhost/proxy/proxy.php?https://environment.data.gov.uk/arcgis/rest/services/NE/SitesOfSpecialScientificInterestEngland/FeatureServer/0?f=json' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

How can I use the Esri reverse proxy when it's on a different port to the React application?

(I'm undertaking the development on http://localhost:3000 but eventually this application will be served by Amazon Amplify, if that makes any difference.)

Many thanks

**Comment by andygup** [comment]
@slead You used to be able to set the Create React App default port to 80.  Maybe give that a try.

**Comment by slead** [comment]
Hi @andygup,

Thanks for the suggestion. I'm already running Apache on port 80, which (I believe) is necessary in order to run the PHP component fo the Esri resource proxy.

```
✔ Something is already running on port 80. Probably:
  /usr/sbin/httpd -D FOREGROUND (pid 332)
  in /

Would you like to run the app on another port instead?
```

So if I stop Apache on port 80 and instead run React there, how would I run the proxy?

Thanks,
Steve

**Comment by slead** [comment]
Thanks Andy. I'm out of my depth here so I'll park it for the meanwhile. 

In case it helps anyone else, as a workaround I'm manually deploying the React app using `npm build` and FTPing it to a web server where I've installed the PHP version of the Esri resource proxy.
