### ISSUE TITLE
node.js proxy page

### ISSUE THREAD

**Issue by rpepato** [Esri/resource-proxy#63]
Considering the growth of node.js and pervasiveness of javascript, what about to build a proxy page that executes in node.js?

This would remove the requirement for a php, or java, or .net server engine for a full-stack javascript programmer.

**Comment by tannerjt** [comment]
Has there been any more demand for a node resource proxy?  This would also be helpful when testing locally without having to run IIS or any other heavy environment setups.

**Comment by jgravois** [comment]
the only way we are tracking demand is through looking at the number of comments and 👍  reactions to the first comment in this thread.  to date, its mostly been Esri folks going back and forth.

if you're interested in a node proxy, you can find a very stripped down sample here:
https://github.com/Esri/geotrigger-editor/blob/master/examples/proxy/proxy.js

**Comment by tannerjt** [comment]
Thanks @jgravois.  It would be nice to use a simple proxy like the geotrigger example, but add support for a config.json with the same settings (username, password, clientId, ratelimit, etc) provided by the other libraries in this repo.

**Comment by jgravois** [comment]
> It would be nice... 

agreed.  thats why we're leaving the issue open.  

just to throw a couple more alternatives out there though, when testing locally, its a lot simpler than it used to both:
1. create tokens in https://developers.arcgis.com that will last 24 hours 
2. spin up hosted 'Service Proxies' to broker requests to individual services that consume credits

**Comment by esoekianto** [comment]
Service proxies from ArcGIS for Developers is definitely the best workflow when accessing premium services in ArcGIS Online. no need to host local proxy in web server

**Comment by tannerjt** [comment]
I've used that proxy before to access premium services, but I was mostly interested for ArcGIS server services accessed with either a token or credentials.  The AGOL proxy service is nice though.

**Comment by patrickarlt** [comment]
@tannerjt if you want to proxy server services with tokens or credentials you can do that too. Just follow https://doc.arcgis.com/en/arcgis-online/reference/arcgis-server-services.htm.

**Comment by tannerjt** [comment]
Thanks @patrickarlt - Storing credentials in ArcGIS Online works perfect for accessing the secure services.

**Comment by RoyTinker** [comment]
On the BA web app team, we currently rely on a local IIS instance with the .NET proxy installed when developing locally. This setup alienates other platforms and increases finickyness required to get started (I still don't have it set up locally).

I built a tiny node-based local file server (incl. HTTPS) using a functional chain of connect() middleware, and it's working great. Only thing is I'd like to have a /proxy endpoint available.

It would be great if there was a node-based resource proxy implemented as connect() middleware.

**Comment by DavidSpriggs** [comment]
In case someone comes to this thread looking for a solution: https://github.com/jf990/resource-proxy-node
