### ISSUE TITLE
JSP: Rate Limiting: Throw error 429 instead of 402

### ISSUE THREAD

**Issue by MehulChoksey** [Esri/resource-proxy#69]
If number of requests exceed specified limit with in a given time, use error code 429 (Too Many Requests) instead of 402 (reserved for payment required)

It would be nice to change the http status code as well..

**Comment by bsvensson** [comment]
@jgravois - in https://github.com/Esri/resource-proxy/issues/69#issuecomment-39499877 above you asked if your suggested DotNet solution would work.  I think it would work fine :)

Could you submit a PR with that fix (returning 429 error when hitting the ratelimit)?

[JSP code has](https://github.com/esri/resource-proxy/blob/master/Java/proxy.jsp#L1024-L1025): 
```
sendErrorResponse(response, "This is a metered resource, number of requests have exceeded the rate limit interval.",
      "Error 429 - Too Many Requests", 429);
```
