### ISSUE TITLE
DotNet : Throw "Error 500-Protocol Error" when passing ArcGIS Server uri with windows authentication 

### ISSUE THREAD

**Issue by esoekianto** [Esri/resource-proxy#7]
I know that proxy should only work with token-based arcgis server, but is there any way to allow the url for arcgis server that is not set for token based but window authentication only

![proxy1](https://f.cloud.github.com/assets/5265339/2200402/b3c2a566-98e1-11e3-94fa-48824fa690ee.PNG)
![proxy2](https://f.cloud.github.com/assets/5265339/2200404/b5c8cff2-98e1-11e3-82df-00e92f824a04.PNG)

**Comment by pfoppe** [comment]
We are configuring our IIS application pool identity to a 'headless service account' that has been configured for access to our 'web-tier' secured services.  [PR 309](https://github.com/Esri/resource-proxy/pull/309) was merged into the master in MAY 2017.  Technically we are getting web-tier authentication working from the proxy making requests to the back-end servers running Microsoft Integrated Windows Authentication.  You might find this useful getting you proxy working with web-tier services...
